// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Performs login and returns a bearer token and tenant context.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Authenticate user",
                "parameters": [
                    {
                        "description": "Credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.LoginRequestDoc"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.LoginResponseDoc"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    }
                }
            }
        },
        "/schedules": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns schedules from the authenticated tenant.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedules"
                ],
                "summary": "List schedules",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.ScheduleListResponseDoc"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a schedule for the authenticated tenant.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedules"
                ],
                "summary": "Create schedule",
                "parameters": [
                    {
                        "description": "Schedule payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.ScheduleCreateRequestDoc"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handler.ScheduleItemResponseDoc"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    }
                }
            }
        },
        "/schedules/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a single schedule from the authenticated tenant.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedules"
                ],
                "summary": "Get schedule by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Schedule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.ScheduleItemResponseDoc"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates a schedule for the authenticated tenant.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedules"
                ],
                "summary": "Update schedule",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Schedule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Schedule payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.ScheduleUpdateRequestDoc"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.ScheduleItemResponseDoc"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Soft deletes a schedule from the authenticated tenant.",
                "tags": [
                    "schedules"
                ],
                "summary": "Delete schedule",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Schedule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    }
                }
            }
        },
        "/schedules/{id}/history": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns status history for a schedule in the authenticated tenant.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedules"
                ],
                "summary": "Get schedule history",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Schedule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.ScheduleHistoryResponseDoc"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.APIErrorResponseDoc": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "correlation_id": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "handler.LoginRequestDoc": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "admin@petcontrol.local"
                },
                "password": {
                    "type": "string",
                    "example": "password123"
                }
            }
        },
        "handler.LoginResponseDoc": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/service.LoginResult"
                }
            }
        },
        "handler.ScheduleCreateRequestDoc": {
            "type": "object",
            "properties": {
                "client_id": {
                    "type": "string",
                    "example": "11111111-1111-1111-1111-111111111111"
                },
                "estimated_end": {
                    "type": "string",
                    "example": "2026-04-10T16:00:00Z"
                },
                "notes": {
                    "type": "string",
                    "example": "Banho e tosa"
                },
                "pet_id": {
                    "type": "string",
                    "example": "22222222-2222-2222-2222-222222222222"
                },
                "scheduled_at": {
                    "type": "string",
                    "example": "2026-04-10T15:00:00Z"
                },
                "status": {
                    "type": "string",
                    "example": "waiting"
                },
                "status_notes": {
                    "type": "string",
                    "example": "Aguardando confirmação"
                }
            }
        },
        "handler.ScheduleDoc": {
            "type": "object",
            "properties": {
                "client_id": {
                    "type": "string",
                    "example": "44444444-4444-4444-4444-444444444444"
                },
                "company_id": {
                    "type": "string",
                    "example": "11111111-1111-1111-1111-111111111111"
                },
                "created_at": {
                    "type": "string",
                    "example": "2026-04-10T10:00:00Z"
                },
                "current_status": {
                    "type": "string",
                    "example": "confirmed"
                },
                "deleted_at": {
                    "type": "string",
                    "example": "2026-04-11T11:00:00Z"
                },
                "estimated_end": {
                    "type": "string",
                    "example": "2026-04-10T16:00:00Z"
                },
                "id": {
                    "type": "string",
                    "example": "33333333-3333-3333-3333-333333333333"
                },
                "notes": {
                    "type": "string",
                    "example": "Banho e tosa"
                },
                "pet_id": {
                    "type": "string",
                    "example": "55555555-5555-5555-5555-555555555555"
                },
                "scheduled_at": {
                    "type": "string",
                    "example": "2026-04-10T15:00:00Z"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2026-04-10T11:00:00Z"
                }
            }
        },
        "handler.ScheduleHistoryItemDoc": {
            "type": "object",
            "properties": {
                "changed_at": {
                    "type": "string",
                    "example": "2026-04-10T11:00:00Z"
                },
                "changed_by": {
                    "type": "string",
                    "example": "22222222-2222-2222-2222-222222222222"
                },
                "id": {
                    "type": "string",
                    "example": "66666666-6666-6666-6666-666666666666"
                },
                "notes": {
                    "type": "string",
                    "example": "Confirmado por telefone"
                },
                "schedule_id": {
                    "type": "string",
                    "example": "33333333-3333-3333-3333-333333333333"
                },
                "status": {
                    "type": "string",
                    "example": "confirmed"
                }
            }
        },
        "handler.ScheduleHistoryResponseDoc": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.ScheduleHistoryItemDoc"
                    }
                }
            }
        },
        "handler.ScheduleItemResponseDoc": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/handler.ScheduleDoc"
                }
            }
        },
        "handler.ScheduleListResponseDoc": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.ScheduleDoc"
                    }
                }
            }
        },
        "handler.ScheduleUpdateRequestDoc": {
            "type": "object",
            "properties": {
                "client_id": {
                    "type": "string",
                    "example": "11111111-1111-1111-1111-111111111111"
                },
                "estimated_end": {
                    "type": "string",
                    "example": "2026-04-10T16:00:00Z"
                },
                "notes": {
                    "type": "string",
                    "example": "Confirmado com o cliente"
                },
                "pet_id": {
                    "type": "string",
                    "example": "22222222-2222-2222-2222-222222222222"
                },
                "scheduled_at": {
                    "type": "string",
                    "example": "2026-04-10T15:00:00Z"
                },
                "status": {
                    "type": "string",
                    "example": "confirmed"
                },
                "status_notes": {
                    "type": "string",
                    "example": "Confirmado por telefone"
                }
            }
        },
        "service.LoginResult": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "company_id": {
                    "type": "string"
                },
                "kind": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "token_type": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Use o formato: Bearer \u003ctoken\u003e",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "PetControl API",
	Description:      "API HTTP do PetControl para autenticação, módulos de tenant e agendamentos.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
