// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Performs login and returns a bearer token and tenant context.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Authenticate user",
                "parameters": [
                    {
                        "description": "Credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.LoginRequestDoc"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.LoginResponseDoc"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    }
                }
            }
        },
        "/clients": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns clients from the authenticated tenant.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients"
                ],
                "summary": "List clients",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.ClientListResponseDoc"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a client for the authenticated tenant.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients"
                ],
                "summary": "Create client",
                "parameters": [
                    {
                        "description": "Client payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.ClientCreateRequestDoc"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handler.ClientItemResponseDoc"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    }
                }
            }
        },
        "/clients/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a single client from the authenticated tenant.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients"
                ],
                "summary": "Get client by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Client ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.ClientItemResponseDoc"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates a client from the authenticated tenant.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clients"
                ],
                "summary": "Update client",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Client ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Client payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.ClientUpdateRequestDoc"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.ClientItemResponseDoc"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deactivates the tenant association for a client.",
                "tags": [
                    "clients"
                ],
                "summary": "Deactivate client",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Client ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    }
                }
            }
        },
        "/pets": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns pets from the authenticated tenant.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pets"
                ],
                "summary": "List pets",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.PetListResponseDoc"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a pet for the authenticated tenant.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pets"
                ],
                "summary": "Create pet",
                "parameters": [
                    {
                        "description": "Pet payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.PetCreateRequestDoc"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handler.PetItemResponseDoc"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    }
                }
            }
        },
        "/pets/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a single pet from the authenticated tenant.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pets"
                ],
                "summary": "Get pet by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pet ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.PetItemResponseDoc"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates a pet from the authenticated tenant.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pets"
                ],
                "summary": "Update pet",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pet ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Pet payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.PetUpdateRequestDoc"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.PetItemResponseDoc"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Soft deletes a pet from the authenticated tenant.",
                "tags": [
                    "pets"
                ],
                "summary": "Delete pet",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pet ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    }
                }
            }
        },
        "/schedules": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns schedules from the authenticated tenant.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedules"
                ],
                "summary": "List schedules",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.ScheduleListResponseDoc"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a schedule for the authenticated tenant.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedules"
                ],
                "summary": "Create schedule",
                "parameters": [
                    {
                        "description": "Schedule payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.ScheduleCreateRequestDoc"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handler.ScheduleItemResponseDoc"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    }
                }
            }
        },
        "/schedules/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a single schedule from the authenticated tenant.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedules"
                ],
                "summary": "Get schedule by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Schedule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.ScheduleItemResponseDoc"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates a schedule for the authenticated tenant.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedules"
                ],
                "summary": "Update schedule",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Schedule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Schedule payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.ScheduleUpdateRequestDoc"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.ScheduleItemResponseDoc"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Soft deletes a schedule from the authenticated tenant.",
                "tags": [
                    "schedules"
                ],
                "summary": "Delete schedule",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Schedule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    }
                }
            }
        },
        "/schedules/{id}/history": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns status history for a schedule in the authenticated tenant.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedules"
                ],
                "summary": "Get schedule history",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Schedule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.ScheduleHistoryResponseDoc"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    }
                }
            }
        },
        "/services": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns services from the authenticated tenant.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "services"
                ],
                "summary": "List services",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.ServiceListResponseDoc"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a service for the authenticated tenant.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "services"
                ],
                "summary": "Create service",
                "parameters": [
                    {
                        "description": "Service payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.ServiceCreateRequestDoc"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handler.ServiceItemResponseDoc"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    }
                }
            }
        },
        "/services/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a single service from the authenticated tenant.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "services"
                ],
                "summary": "Get service by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Service ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.ServiceItemResponseDoc"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates a service from the authenticated tenant.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "services"
                ],
                "summary": "Update service",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Service ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Service payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.ServiceUpdateRequestDoc"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.ServiceItemResponseDoc"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deactivates a service from the authenticated tenant.",
                "tags": [
                    "services"
                ],
                "summary": "Delete service",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Service ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.APIErrorResponseDoc"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.APIErrorResponseDoc": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "correlation_id": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "handler.ClientCreateRequestDoc": {
            "type": "object",
            "properties": {
                "birth_date": {
                    "type": "string",
                    "example": "1992-06-15"
                },
                "cellphone": {
                    "type": "string",
                    "example": "+5511999990001"
                },
                "client_since": {
                    "type": "string",
                    "example": "2026-04-01"
                },
                "cpf": {
                    "type": "string",
                    "example": "12345678901"
                },
                "email": {
                    "type": "string",
                    "example": "maria.silva@petcontrol.local"
                },
                "full_name": {
                    "type": "string",
                    "example": "Maria Silva"
                },
                "gender_identity": {
                    "type": "string",
                    "example": "woman_cisgender"
                },
                "has_whatsapp": {
                    "type": "boolean",
                    "example": true
                },
                "marital_status": {
                    "type": "string",
                    "example": "single"
                },
                "notes": {
                    "type": "string",
                    "example": "Cliente recorrente"
                },
                "phone": {
                    "type": "string",
                    "example": "+551130000000"
                },
                "short_name": {
                    "type": "string",
                    "example": "Maria"
                }
            }
        },
        "handler.ClientDoc": {
            "type": "object",
            "properties": {
                "birth_date": {
                    "type": "string",
                    "example": "1992-06-15"
                },
                "cellphone": {
                    "type": "string",
                    "example": "+5511999990001"
                },
                "client_since": {
                    "type": "string",
                    "example": "2026-04-01"
                },
                "company_id": {
                    "type": "string",
                    "example": "11111111-1111-1111-1111-111111111111"
                },
                "cpf": {
                    "type": "string",
                    "example": "12345678901"
                },
                "created_at": {
                    "type": "string",
                    "example": "2026-04-10T10:00:00Z"
                },
                "email": {
                    "type": "string",
                    "example": "maria.silva@petcontrol.local"
                },
                "full_name": {
                    "type": "string",
                    "example": "Maria Silva"
                },
                "gender_identity": {
                    "type": "string",
                    "example": "woman_cisgender"
                },
                "has_whatsapp": {
                    "type": "boolean",
                    "example": true
                },
                "id": {
                    "type": "string",
                    "example": "44444444-4444-4444-4444-444444444444"
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "joined_at": {
                    "type": "string",
                    "example": "2026-04-10T10:00:00Z"
                },
                "left_at": {
                    "type": "string",
                    "example": "2026-04-11T11:00:00Z"
                },
                "marital_status": {
                    "type": "string",
                    "example": "single"
                },
                "notes": {
                    "type": "string",
                    "example": "Cliente recorrente"
                },
                "person_id": {
                    "type": "string",
                    "example": "55555555-5555-5555-5555-555555555555"
                },
                "phone": {
                    "type": "string",
                    "example": "+551130000000"
                },
                "short_name": {
                    "type": "string",
                    "example": "Maria"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2026-04-10T11:00:00Z"
                }
            }
        },
        "handler.ClientItemResponseDoc": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/handler.ClientDoc"
                }
            }
        },
        "handler.ClientListResponseDoc": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.ClientDoc"
                    }
                }
            }
        },
        "handler.ClientUpdateRequestDoc": {
            "type": "object",
            "properties": {
                "birth_date": {
                    "type": "string",
                    "example": "1992-06-15"
                },
                "cellphone": {
                    "type": "string",
                    "example": "+5511999990002"
                },
                "client_since": {
                    "type": "string",
                    "example": "2026-04-01"
                },
                "cpf": {
                    "type": "string",
                    "example": "12345678901"
                },
                "email": {
                    "type": "string",
                    "example": "maria.souza@petcontrol.local"
                },
                "full_name": {
                    "type": "string",
                    "example": "Maria Souza"
                },
                "gender_identity": {
                    "type": "string",
                    "example": "woman_cisgender"
                },
                "has_whatsapp": {
                    "type": "boolean",
                    "example": true
                },
                "marital_status": {
                    "type": "string",
                    "example": "married"
                },
                "notes": {
                    "type": "string",
                    "example": "Preferência por contato via WhatsApp"
                },
                "phone": {
                    "type": "string",
                    "example": "+551130000000"
                },
                "short_name": {
                    "type": "string",
                    "example": "Mari"
                }
            }
        },
        "handler.LoginRequestDoc": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "admin@petcontrol.local"
                },
                "password": {
                    "type": "string",
                    "example": "password123"
                }
            }
        },
        "handler.LoginResponseDoc": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/service.LoginResult"
                }
            }
        },
        "handler.PetCreateRequestDoc": {
            "type": "object",
            "properties": {
                "birth_date": {
                    "type": "string",
                    "example": "2021-08-20"
                },
                "image_url": {
                    "type": "string",
                    "example": "https://example.com/thor.png"
                },
                "kind": {
                    "type": "string",
                    "example": "dog"
                },
                "name": {
                    "type": "string",
                    "example": "Thor"
                },
                "notes": {
                    "type": "string",
                    "example": "Gosta de brincar"
                },
                "owner_id": {
                    "type": "string",
                    "example": "44444444-4444-4444-4444-444444444444"
                },
                "size": {
                    "type": "string",
                    "example": "medium"
                },
                "temperament": {
                    "type": "string",
                    "example": "playful"
                }
            }
        },
        "handler.PetDoc": {
            "type": "object",
            "properties": {
                "birth_date": {
                    "type": "string",
                    "example": "2021-08-20"
                },
                "company_id": {
                    "type": "string",
                    "example": "11111111-1111-1111-1111-111111111111"
                },
                "created_at": {
                    "type": "string",
                    "example": "2026-04-10T10:00:00Z"
                },
                "deleted_at": {
                    "type": "string",
                    "example": "2026-04-11T11:00:00Z"
                },
                "id": {
                    "type": "string",
                    "example": "77777777-7777-7777-7777-777777777777"
                },
                "image_url": {
                    "type": "string",
                    "example": "https://example.com/thor.png"
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "kind": {
                    "type": "string",
                    "example": "dog"
                },
                "name": {
                    "type": "string",
                    "example": "Thor"
                },
                "notes": {
                    "type": "string",
                    "example": "Gosta de brincar"
                },
                "owner_id": {
                    "type": "string",
                    "example": "44444444-4444-4444-4444-444444444444"
                },
                "owner_name": {
                    "type": "string",
                    "example": "Maria Silva"
                },
                "size": {
                    "type": "string",
                    "example": "medium"
                },
                "temperament": {
                    "type": "string",
                    "example": "playful"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2026-04-10T11:00:00Z"
                }
            }
        },
        "handler.PetItemResponseDoc": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/handler.PetDoc"
                }
            }
        },
        "handler.PetListResponseDoc": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.PetDoc"
                    }
                }
            }
        },
        "handler.PetUpdateRequestDoc": {
            "type": "object",
            "properties": {
                "birth_date": {
                    "type": "string",
                    "example": "2021-08-20"
                },
                "image_url": {
                    "type": "string",
                    "example": "https://example.com/thor.png"
                },
                "kind": {
                    "type": "string",
                    "example": "dog"
                },
                "name": {
                    "type": "string",
                    "example": "Thorzinho"
                },
                "notes": {
                    "type": "string",
                    "example": "Atualizado após consulta"
                },
                "owner_id": {
                    "type": "string",
                    "example": "44444444-4444-4444-4444-444444444444"
                },
                "size": {
                    "type": "string",
                    "example": "large"
                },
                "temperament": {
                    "type": "string",
                    "example": "loving"
                }
            }
        },
        "handler.ScheduleCreateRequestDoc": {
            "type": "object",
            "properties": {
                "client_id": {
                    "type": "string",
                    "example": "11111111-1111-1111-1111-111111111111"
                },
                "estimated_end": {
                    "type": "string",
                    "example": "2026-04-10T16:00:00Z"
                },
                "notes": {
                    "type": "string",
                    "example": "Banho e tosa"
                },
                "pet_id": {
                    "type": "string",
                    "example": "22222222-2222-2222-2222-222222222222"
                },
                "scheduled_at": {
                    "type": "string",
                    "example": "2026-04-10T15:00:00Z"
                },
                "service_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "status": {
                    "type": "string",
                    "example": "waiting"
                },
                "status_notes": {
                    "type": "string",
                    "example": "Aguardando confirmação"
                }
            }
        },
        "handler.ScheduleDoc": {
            "type": "object",
            "properties": {
                "client_id": {
                    "type": "string",
                    "example": "44444444-4444-4444-4444-444444444444"
                },
                "client_name": {
                    "type": "string",
                    "example": "Maria Silva"
                },
                "company_id": {
                    "type": "string",
                    "example": "11111111-1111-1111-1111-111111111111"
                },
                "created_at": {
                    "type": "string",
                    "example": "2026-04-10T10:00:00Z"
                },
                "current_status": {
                    "type": "string",
                    "example": "confirmed"
                },
                "deleted_at": {
                    "type": "string",
                    "example": "2026-04-11T11:00:00Z"
                },
                "estimated_end": {
                    "type": "string",
                    "example": "2026-04-10T16:00:00Z"
                },
                "id": {
                    "type": "string",
                    "example": "33333333-3333-3333-3333-333333333333"
                },
                "notes": {
                    "type": "string",
                    "example": "Banho e tosa"
                },
                "pet_id": {
                    "type": "string",
                    "example": "55555555-5555-5555-5555-555555555555"
                },
                "pet_name": {
                    "type": "string",
                    "example": "Thor"
                },
                "scheduled_at": {
                    "type": "string",
                    "example": "2026-04-10T15:00:00Z"
                },
                "service_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "service_titles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "updated_at": {
                    "type": "string",
                    "example": "2026-04-10T11:00:00Z"
                }
            }
        },
        "handler.ScheduleHistoryItemDoc": {
            "type": "object",
            "properties": {
                "changed_at": {
                    "type": "string",
                    "example": "2026-04-10T11:00:00Z"
                },
                "changed_by": {
                    "type": "string",
                    "example": "22222222-2222-2222-2222-222222222222"
                },
                "id": {
                    "type": "string",
                    "example": "66666666-6666-6666-6666-666666666666"
                },
                "notes": {
                    "type": "string",
                    "example": "Confirmado por telefone"
                },
                "schedule_id": {
                    "type": "string",
                    "example": "33333333-3333-3333-3333-333333333333"
                },
                "status": {
                    "type": "string",
                    "example": "confirmed"
                }
            }
        },
        "handler.ScheduleHistoryResponseDoc": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.ScheduleHistoryItemDoc"
                    }
                }
            }
        },
        "handler.ScheduleItemResponseDoc": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/handler.ScheduleDoc"
                }
            }
        },
        "handler.ScheduleListResponseDoc": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.ScheduleDoc"
                    }
                }
            }
        },
        "handler.ScheduleUpdateRequestDoc": {
            "type": "object",
            "properties": {
                "client_id": {
                    "type": "string",
                    "example": "11111111-1111-1111-1111-111111111111"
                },
                "estimated_end": {
                    "type": "string",
                    "example": "2026-04-10T16:00:00Z"
                },
                "notes": {
                    "type": "string",
                    "example": "Confirmado com o cliente"
                },
                "pet_id": {
                    "type": "string",
                    "example": "22222222-2222-2222-2222-222222222222"
                },
                "scheduled_at": {
                    "type": "string",
                    "example": "2026-04-10T15:00:00Z"
                },
                "service_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "status": {
                    "type": "string",
                    "example": "confirmed"
                },
                "status_notes": {
                    "type": "string",
                    "example": "Confirmado por telefone"
                }
            }
        },
        "handler.ServiceCreateRequestDoc": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "Banho com secagem e perfume"
                },
                "discount_rate": {
                    "type": "string",
                    "example": "0.00"
                },
                "image_url": {
                    "type": "string",
                    "example": "https://example.com/services/bath.png"
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "notes": {
                    "type": "string",
                    "example": "Inclui perfume hipoalergênico"
                },
                "price": {
                    "type": "string",
                    "example": "89.90"
                },
                "title": {
                    "type": "string",
                    "example": "Banho completo"
                },
                "type_name": {
                    "type": "string",
                    "example": "Banho"
                }
            }
        },
        "handler.ServiceDoc": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "Banho com secagem e perfume"
                },
                "discount_rate": {
                    "type": "string",
                    "example": "0.00"
                },
                "id": {
                    "type": "string",
                    "example": "88888888-8888-8888-8888-888888888888"
                },
                "image_url": {
                    "type": "string",
                    "example": "https://example.com/services/bath.png"
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "notes": {
                    "type": "string",
                    "example": "Inclui perfume hipoalergênico"
                },
                "price": {
                    "type": "string",
                    "example": "89.90"
                },
                "title": {
                    "type": "string",
                    "example": "Banho completo"
                },
                "type_id": {
                    "type": "string",
                    "example": "99999999-9999-9999-9999-999999999999"
                },
                "type_name": {
                    "type": "string",
                    "example": "Banho"
                }
            }
        },
        "handler.ServiceItemResponseDoc": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/handler.ServiceDoc"
                }
            }
        },
        "handler.ServiceListResponseDoc": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.ServiceDoc"
                    }
                }
            }
        },
        "handler.ServiceUpdateRequestDoc": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "Tosa leve para manutenção"
                },
                "discount_rate": {
                    "type": "string",
                    "example": "10.00"
                },
                "image_url": {
                    "type": "string",
                    "example": "https://example.com/services/tosa.png"
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "notes": {
                    "type": "string",
                    "example": "Adicionar avaliação do pelo"
                },
                "price": {
                    "type": "string",
                    "example": "59.90"
                },
                "title": {
                    "type": "string",
                    "example": "Tosa higiênica"
                },
                "type_name": {
                    "type": "string",
                    "example": "Tosa"
                }
            }
        },
        "service.LoginResult": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "company_id": {
                    "type": "string"
                },
                "kind": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "token_type": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Use o formato: Bearer \u003ctoken\u003e",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "PetControl API",
	Description:      "API HTTP do PetControl para autenticação, módulos de tenant e agendamentos.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
