// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: addresses.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAddress = `-- name: CreateAddress :one
INSERT INTO addresses(zip_code, street, number, complement, district, city, state, country)
    VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING
    id, zip_code, street, number, complement, district, city, state, country, created_at, updated_at
`

type CreateAddressParams struct {
	ZipCode    string      `db:"ZipCode" json:"ZipCode"`
	Street     string      `db:"Street" json:"Street"`
	Number     string      `db:"Number" json:"Number"`
	Complement pgtype.Text `db:"Complement" json:"Complement"`
	District   string      `db:"District" json:"District"`
	City       string      `db:"City" json:"City"`
	State      string      `db:"State" json:"State"`
	Country    string      `db:"Country" json:"Country"`
}

func (q *Queries) CreateAddress(ctx context.Context, arg CreateAddressParams) (Address, error) {
	row := q.db.QueryRow(ctx, createAddress,
		arg.ZipCode,
		arg.Street,
		arg.Number,
		arg.Complement,
		arg.District,
		arg.City,
		arg.State,
		arg.Country,
	)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.ZipCode,
		&i.Street,
		&i.Number,
		&i.Complement,
		&i.District,
		&i.City,
		&i.State,
		&i.Country,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAddress = `-- name: GetAddress :one
SELECT
    a.zip_code,
    a.street,
    a.number,
    a.complement,
    a.district,
    a.city,
    a.state,
    a.country,
    a.created_at,
    a.updated_at
FROM
    addresses a
WHERE
    a.id = $1
`

type GetAddressRow struct {
	ZipCode    string             `db:"zip_code" json:"zip_code"`
	Street     string             `db:"street" json:"street"`
	Number     string             `db:"number" json:"number"`
	Complement pgtype.Text        `db:"complement" json:"complement"`
	District   string             `db:"district" json:"district"`
	City       string             `db:"city" json:"city"`
	State      string             `db:"state" json:"state"`
	Country    string             `db:"country" json:"country"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetAddress(ctx context.Context, id pgtype.UUID) (GetAddressRow, error) {
	row := q.db.QueryRow(ctx, getAddress, id)
	var i GetAddressRow
	err := row.Scan(
		&i.ZipCode,
		&i.Street,
		&i.Number,
		&i.Complement,
		&i.District,
		&i.City,
		&i.State,
		&i.Country,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAddress = `-- name: InsertAddress :execrows
INSERT INTO addresses(zip_code, street, number, complement, district, city, state, country)
    VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertAddressParams struct {
	ZipCode    string      `db:"ZipCode" json:"ZipCode"`
	Street     string      `db:"Street" json:"Street"`
	Number     string      `db:"Number" json:"Number"`
	Complement pgtype.Text `db:"Complement" json:"Complement"`
	District   string      `db:"District" json:"District"`
	City       string      `db:"City" json:"City"`
	State      string      `db:"State" json:"State"`
	Country    string      `db:"Country" json:"Country"`
}

func (q *Queries) InsertAddress(ctx context.Context, arg InsertAddressParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertAddress,
		arg.ZipCode,
		arg.Street,
		arg.Number,
		arg.Complement,
		arg.District,
		arg.City,
		arg.State,
		arg.Country,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAddress = `-- name: UpdateAddress :execrows
UPDATE
    addresses
SET
    zip_code = COALESCE($1, zip_code),
    street = COALESCE($2, street),
    number = COALESCE($3, number),
    complement = COALESCE($4, complement),
    district = COALESCE($5, district),
    city = COALESCE($6, city),
    state = COALESCE($7, state),
    country = COALESCE($8, country),
    updated_at = now()
WHERE
    id = $9
`

type UpdateAddressParams struct {
	ZipCode    pgtype.Text `db:"ZipCode" json:"ZipCode"`
	Street     pgtype.Text `db:"Street" json:"Street"`
	Number     pgtype.Text `db:"Number" json:"Number"`
	Complement pgtype.Text `db:"Complement" json:"Complement"`
	District   pgtype.Text `db:"District" json:"District"`
	City       pgtype.Text `db:"City" json:"City"`
	State      pgtype.Text `db:"State" json:"State"`
	Country    pgtype.Text `db:"Country" json:"Country"`
	ID         pgtype.UUID `db:"ID" json:"ID"`
}

func (q *Queries) UpdateAddress(ctx context.Context, arg UpdateAddressParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAddress,
		arg.ZipCode,
		arg.Street,
		arg.Number,
		arg.Complement,
		arg.District,
		arg.City,
		arg.State,
		arg.Country,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
