// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_system_chat.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAdminSystemMessage = `-- name: InsertAdminSystemMessage :one
INSERT INTO admin_system_messages(conversation_id, company_id, sender_user_id, body)
VALUES (
  $1,
  $2,
  $3,
  $4
)
RETURNING id, conversation_id, company_id, sender_user_id, body, created_at, updated_at, deleted_at
`

type InsertAdminSystemMessageParams struct {
	ConversationID pgtype.UUID `db:"ConversationID" json:"ConversationID"`
	CompanyID      pgtype.UUID `db:"CompanyID" json:"CompanyID"`
	SenderUserID   pgtype.UUID `db:"SenderUserID" json:"SenderUserID"`
	Body           string      `db:"Body" json:"Body"`
}

func (q *Queries) InsertAdminSystemMessage(ctx context.Context, arg InsertAdminSystemMessageParams) (AdminSystemMessage, error) {
	row := q.db.QueryRow(ctx, insertAdminSystemMessage,
		arg.ConversationID,
		arg.CompanyID,
		arg.SenderUserID,
		arg.Body,
	)
	var i AdminSystemMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.CompanyID,
		&i.SenderUserID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAdminSystemMessages = `-- name: ListAdminSystemMessages :many
SELECT
  asm.id,
  asm.conversation_id,
  asm.company_id,
  asm.sender_user_id,
  asm.body,
  asm.created_at,
  asm.updated_at,
  asm.deleted_at,
  COALESCE(pi.short_name, pi.full_name, sender.email) AS sender_name,
  pi.image_url AS sender_image_url,
  sender.role AS sender_role
FROM
  admin_system_messages asm
  INNER JOIN admin_system_conversations ascv ON ascv.id = asm.conversation_id
  INNER JOIN users sender ON sender.id = asm.sender_user_id
  LEFT JOIN user_profiles up ON up.user_id = sender.id
  LEFT JOIN people_identifications pi ON pi.person_id = up.person_id
WHERE
  ascv.company_id = $1
  AND ascv.admin_user_id = $2
  AND ascv.system_user_id = $3
  AND asm.deleted_at IS NULL
ORDER BY
  asm.created_at ASC
`

type ListAdminSystemMessagesParams struct {
	CompanyID    pgtype.UUID `db:"CompanyID" json:"CompanyID"`
	AdminUserID  pgtype.UUID `db:"AdminUserID" json:"AdminUserID"`
	SystemUserID pgtype.UUID `db:"SystemUserID" json:"SystemUserID"`
}

type ListAdminSystemMessagesRow struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	ConversationID pgtype.UUID        `db:"conversation_id" json:"conversation_id"`
	CompanyID      pgtype.UUID        `db:"company_id" json:"company_id"`
	SenderUserID   pgtype.UUID        `db:"sender_user_id" json:"sender_user_id"`
	Body           string             `db:"body" json:"body"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	SenderName     string             `db:"sender_name" json:"sender_name"`
	SenderImageUrl pgtype.Text        `db:"sender_image_url" json:"sender_image_url"`
	SenderRole     UserRoleType       `db:"sender_role" json:"sender_role"`
}

func (q *Queries) ListAdminSystemMessages(ctx context.Context, arg ListAdminSystemMessagesParams) ([]ListAdminSystemMessagesRow, error) {
	rows, err := q.db.Query(ctx, listAdminSystemMessages, arg.CompanyID, arg.AdminUserID, arg.SystemUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminSystemMessagesRow
	for rows.Next() {
		var i ListAdminSystemMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.CompanyID,
			&i.SenderUserID,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SenderName,
			&i.SenderImageUrl,
			&i.SenderRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAdminSystemConversation = `-- name: UpsertAdminSystemConversation :one
INSERT INTO admin_system_conversations(company_id, admin_user_id, system_user_id, updated_at)
VALUES (
  $1,
  $2,
  $3,
  NOW()
)
ON CONFLICT (company_id, admin_user_id, system_user_id)
DO UPDATE SET
  updated_at = NOW()
RETURNING id, company_id, admin_user_id, system_user_id, created_at, updated_at
`

type UpsertAdminSystemConversationParams struct {
	CompanyID    pgtype.UUID `db:"CompanyID" json:"CompanyID"`
	AdminUserID  pgtype.UUID `db:"AdminUserID" json:"AdminUserID"`
	SystemUserID pgtype.UUID `db:"SystemUserID" json:"SystemUserID"`
}

func (q *Queries) UpsertAdminSystemConversation(ctx context.Context, arg UpsertAdminSystemConversationParams) (AdminSystemConversation, error) {
	row := q.db.QueryRow(ctx, upsertAdminSystemConversation, arg.CompanyID, arg.AdminUserID, arg.SystemUserID)
	var i AdminSystemConversation
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.AdminUserID,
		&i.SystemUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
