// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserAuthByUserID = `-- name: GetUserAuthByUserID :one
SELECT
    ua.user_id,
    ua.password_hash,
    ua.password_changed_at,
    ua.must_change_password,
    ua.login_attempts,
    ua.locked_until,
    ua.last_login_at,
    ua.created_at,
    ua.updated_at
FROM
    user_auth ua
WHERE
    ua.user_id = $1
LIMIT 1
`

func (q *Queries) GetUserAuthByUserID(ctx context.Context, userid pgtype.UUID) (UserAuth, error) {
	row := q.db.QueryRow(ctx, getUserAuthByUserID, userid)
	var i UserAuth
	err := row.Scan(
		&i.UserID,
		&i.PasswordHash,
		&i.PasswordChangedAt,
		&i.MustChangePassword,
		&i.LoginAttempts,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasActiveCompanyModuleByCode = `-- name: HasActiveCompanyModuleByCode :one
SELECT
    EXISTS (
        SELECT
            1
        FROM
            company_modules cm
            INNER JOIN modules m ON m.id = cm.module_id
        WHERE
            cm.company_id = $1
            AND cm.is_active = TRUE
            AND m.code = $2
            AND m.is_active = TRUE
            AND m.deleted_at IS NULL) AS has_access
`

type HasActiveCompanyModuleByCodeParams struct {
	CompanyID pgtype.UUID `db:"CompanyID" json:"CompanyID"`
	Code      string      `db:"Code" json:"Code"`
}

func (q *Queries) HasActiveCompanyModuleByCode(ctx context.Context, arg HasActiveCompanyModuleByCodeParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveCompanyModuleByCode, arg.CompanyID, arg.Code)
	var has_access bool
	err := row.Scan(&has_access)
	return has_access, err
}

const incrementUserAuthLoginAttempts = `-- name: IncrementUserAuthLoginAttempts :exec
UPDATE
    user_auth
SET
    login_attempts = login_attempts + 1,
    updated_at = now()
WHERE
    user_id = $1
`

func (q *Queries) IncrementUserAuthLoginAttempts(ctx context.Context, userid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementUserAuthLoginAttempts, userid)
	return err
}

const insertLoginHistory = `-- name: InsertLoginHistory :exec
INSERT INTO login_history(user_id, ip_address, user_agent, result, failure_detail)
    VALUES ($1, $2, $3, $4, $5)
`

type InsertLoginHistoryParams struct {
	UserID        pgtype.UUID `db:"UserID" json:"UserID"`
	IPAddress     netip.Addr  `db:"IPAddress" json:"IPAddress"`
	UserAgent     string      `db:"UserAgent" json:"UserAgent"`
	Result        LoginResult `db:"Result" json:"Result"`
	FailureDetail pgtype.Text `db:"FailureDetail" json:"FailureDetail"`
}

func (q *Queries) InsertLoginHistory(ctx context.Context, arg InsertLoginHistoryParams) error {
	_, err := q.db.Exec(ctx, insertLoginHistory,
		arg.UserID,
		arg.IPAddress,
		arg.UserAgent,
		arg.Result,
		arg.FailureDetail,
	)
	return err
}

const resetUserAuthLoginAttempts = `-- name: ResetUserAuthLoginAttempts :exec
UPDATE
    user_auth
SET
    login_attempts = 0,
    locked_until = NULL,
    last_login_at = now(),
    updated_at = now()
WHERE
    user_id = $1
`

func (q *Queries) ResetUserAuthLoginAttempts(ctx context.Context, userid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, resetUserAuthLoginAttempts, userid)
	return err
}

const setUserAuthLockedUntil = `-- name: SetUserAuthLockedUntil :exec
UPDATE
    user_auth
SET
    locked_until = $1,
    updated_at = now()
WHERE
    user_id = $2
`

type SetUserAuthLockedUntilParams struct {
	LockedUntil pgtype.Timestamptz `db:"LockedUntil" json:"LockedUntil"`
	UserID      pgtype.UUID        `db:"UserID" json:"UserID"`
}

func (q *Queries) SetUserAuthLockedUntil(ctx context.Context, arg SetUserAuthLockedUntilParams) error {
	_, err := q.db.Exec(ctx, setUserAuthLockedUntil, arg.LockedUntil, arg.UserID)
	return err
}
