// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: company_people_addresses.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCompanyPeopleAddresses = `-- name: DeleteCompanyPeopleAddresses :execrows
DELETE FROM company_people_addresses
WHERE company_id = $1
    AND person_id = $2
`

type DeleteCompanyPeopleAddressesParams struct {
	CompanyID pgtype.UUID `db:"CompanyID" json:"CompanyID"`
	PersonID  pgtype.UUID `db:"PersonID" json:"PersonID"`
}

func (q *Queries) DeleteCompanyPeopleAddresses(ctx context.Context, arg DeleteCompanyPeopleAddressesParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCompanyPeopleAddresses, arg.CompanyID, arg.PersonID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCompanyPeopleAddresses = `-- name: GetCompanyPeopleAddresses :one
SELECT
    cpa.id,
    cpa.company_id,
    cpa.person_id,
    cpa.address_id,
    cpa.is_main,
    cpa.created_at
FROM
    company_people_addresses cpa
WHERE
    cpa.company_id = $1
    AND cpa.person_id = $2
LIMIT 1
`

type GetCompanyPeopleAddressesParams struct {
	CompanyID pgtype.UUID `db:"CompanyID" json:"CompanyID"`
	PersonID  pgtype.UUID `db:"PersonID" json:"PersonID"`
}

func (q *Queries) GetCompanyPeopleAddresses(ctx context.Context, arg GetCompanyPeopleAddressesParams) (CompanyPeopleAddress, error) {
	row := q.db.QueryRow(ctx, getCompanyPeopleAddresses, arg.CompanyID, arg.PersonID)
	var i CompanyPeopleAddress
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.PersonID,
		&i.AddressID,
		&i.IsMain,
		&i.CreatedAt,
	)
	return i, err
}

const insertCompanyPeopleAddresses = `-- name: InsertCompanyPeopleAddresses :execrows
INSERT INTO company_people_addresses(company_id, person_id, address_id, is_main)
    VALUES ($1, $2, $3, $4)
`

type InsertCompanyPeopleAddressesParams struct {
	CompanyID pgtype.UUID `db:"CompanyID" json:"CompanyID"`
	PersonID  pgtype.UUID `db:"PersonID" json:"PersonID"`
	AddressID pgtype.UUID `db:"AddressID" json:"AddressID"`
	IsMain    pgtype.Bool `db:"IsMain" json:"IsMain"`
}

func (q *Queries) InsertCompanyPeopleAddresses(ctx context.Context, arg InsertCompanyPeopleAddressesParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertCompanyPeopleAddresses,
		arg.CompanyID,
		arg.PersonID,
		arg.AddressID,
		arg.IsMain,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listCompanyPeopleAddresses = `-- name: ListCompanyPeopleAddresses :many
SELECT
    cpa.id,
    cpa.company_id,
    cpa.person_id,
    cpa.address_id,
    cpa.is_main,
    cpa.created_at,
    a.street,
    a.number,
    a.complement,
    a.district,
    a.city,
    a.state,
    a.zip_code,
    a.created_at AS address_created_at,
    a.updated_at AS address_updated_at
FROM
    company_people_addresses cpa
    JOIN addresses a ON cpa.address_id = a.id
WHERE
    cpa.company_id = $1
ORDER BY
    cpa.created_at DESC
LIMIT $3
OFFSET $2
`

type ListCompanyPeopleAddressesParams struct {
	CompanyID pgtype.UUID `db:"CompanyID" json:"CompanyID"`
	Offset    int32       `db:"Offset" json:"Offset"`
	Limit     int32       `db:"Limit" json:"Limit"`
}

type ListCompanyPeopleAddressesRow struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	CompanyID        pgtype.UUID        `db:"company_id" json:"company_id"`
	PersonID         pgtype.UUID        `db:"person_id" json:"person_id"`
	AddressID        pgtype.UUID        `db:"address_id" json:"address_id"`
	IsMain           bool               `db:"is_main" json:"is_main"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	Street           string             `db:"street" json:"street"`
	Number           string             `db:"number" json:"number"`
	Complement       pgtype.Text        `db:"complement" json:"complement"`
	District         string             `db:"district" json:"district"`
	City             string             `db:"city" json:"city"`
	State            string             `db:"state" json:"state"`
	ZipCode          string             `db:"zip_code" json:"zip_code"`
	AddressCreatedAt pgtype.Timestamptz `db:"address_created_at" json:"address_created_at"`
	AddressUpdatedAt pgtype.Timestamptz `db:"address_updated_at" json:"address_updated_at"`
}

func (q *Queries) ListCompanyPeopleAddresses(ctx context.Context, arg ListCompanyPeopleAddressesParams) ([]ListCompanyPeopleAddressesRow, error) {
	rows, err := q.db.Query(ctx, listCompanyPeopleAddresses, arg.CompanyID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompanyPeopleAddressesRow
	for rows.Next() {
		var i ListCompanyPeopleAddressesRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.PersonID,
			&i.AddressID,
			&i.IsMain,
			&i.CreatedAt,
			&i.Street,
			&i.Number,
			&i.Complement,
			&i.District,
			&i.City,
			&i.State,
			&i.ZipCode,
			&i.AddressCreatedAt,
			&i.AddressUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompanyPersonAddresses = `-- name: ListCompanyPersonAddresses :many
SELECT
    cpa.id,
    cpa.company_id,
    cpa.person_id,
    cpa.address_id,
    cpa.is_main,
    cpa.created_at,
    a.street,
    a.number,
    a.complement,
    a.district,
    a.city,
    a.state,
    a.zip_code,
    a.created_at AS address_created_at,
    a.updated_at AS address_updated_at
FROM
    company_people_addresses cpa
    JOIN addresses a ON cpa.address_id = a.id
WHERE
    cpa.company_id = $1
    AND cpa.person_id = $2
ORDER BY
    cpa.created_at DESC
LIMIT $4
OFFSET $3
`

type ListCompanyPersonAddressesParams struct {
	CompanyID pgtype.UUID `db:"CompanyID" json:"CompanyID"`
	PersonID  pgtype.UUID `db:"PersonID" json:"PersonID"`
	Offset    int32       `db:"Offset" json:"Offset"`
	Limit     int32       `db:"Limit" json:"Limit"`
}

type ListCompanyPersonAddressesRow struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	CompanyID        pgtype.UUID        `db:"company_id" json:"company_id"`
	PersonID         pgtype.UUID        `db:"person_id" json:"person_id"`
	AddressID        pgtype.UUID        `db:"address_id" json:"address_id"`
	IsMain           bool               `db:"is_main" json:"is_main"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	Street           string             `db:"street" json:"street"`
	Number           string             `db:"number" json:"number"`
	Complement       pgtype.Text        `db:"complement" json:"complement"`
	District         string             `db:"district" json:"district"`
	City             string             `db:"city" json:"city"`
	State            string             `db:"state" json:"state"`
	ZipCode          string             `db:"zip_code" json:"zip_code"`
	AddressCreatedAt pgtype.Timestamptz `db:"address_created_at" json:"address_created_at"`
	AddressUpdatedAt pgtype.Timestamptz `db:"address_updated_at" json:"address_updated_at"`
}

func (q *Queries) ListCompanyPersonAddresses(ctx context.Context, arg ListCompanyPersonAddressesParams) ([]ListCompanyPersonAddressesRow, error) {
	rows, err := q.db.Query(ctx, listCompanyPersonAddresses,
		arg.CompanyID,
		arg.PersonID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompanyPersonAddressesRow
	for rows.Next() {
		var i ListCompanyPersonAddressesRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.PersonID,
			&i.AddressID,
			&i.IsMain,
			&i.CreatedAt,
			&i.Street,
			&i.Number,
			&i.Complement,
			&i.District,
			&i.City,
			&i.State,
			&i.ZipCode,
			&i.AddressCreatedAt,
			&i.AddressUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCompanyPeopleAddresses = `-- name: UpdateCompanyPeopleAddresses :execrows
UPDATE
    company_people_addresses
SET
    address_id = coalesce($1, address_id),
    is_main = coalesce($2, is_main),
    updated_at = now()
WHERE
    company_id = $3
    AND person_id = $4
`

type UpdateCompanyPeopleAddressesParams struct {
	AddressID pgtype.UUID `db:"AddressID" json:"AddressID"`
	IsMain    pgtype.Bool `db:"IsMain" json:"IsMain"`
	CompanyID pgtype.UUID `db:"CompanyID" json:"CompanyID"`
	PersonID  pgtype.UUID `db:"PersonID" json:"PersonID"`
}

func (q *Queries) UpdateCompanyPeopleAddresses(ctx context.Context, arg UpdateCompanyPeopleAddressesParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCompanyPeopleAddresses,
		arg.AddressID,
		arg.IsMain,
		arg.CompanyID,
		arg.PersonID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
