// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: company_finances.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCompanyFinance = `-- name: DeleteCompanyFinance :execrows
DELETE FROM company_finances
WHERE company_id = $1
    AND finance_id = $2
`

type DeleteCompanyFinanceParams struct {
	CompanyID pgtype.UUID `db:"CompanyID" json:"CompanyID"`
	FinanceID pgtype.UUID `db:"FinanceID" json:"FinanceID"`
}

func (q *Queries) DeleteCompanyFinance(ctx context.Context, arg DeleteCompanyFinanceParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCompanyFinance, arg.CompanyID, arg.FinanceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCompanyFinanceByCompanyID = `-- name: GetCompanyFinanceByCompanyID :one
SELECT
    cf.id,
    cf.company_id,
    cf.finance_id,
    cf.is_primary,
    cf.created_at
FROM
    company_finances cf
WHERE
    cf.company_id = $1
    AND cf.finance_id = $2
LIMIT 1
`

type GetCompanyFinanceByCompanyIDParams struct {
	CompanyID pgtype.UUID `db:"CompanyID" json:"CompanyID"`
	FinanceID pgtype.UUID `db:"FinanceID" json:"FinanceID"`
}

func (q *Queries) GetCompanyFinanceByCompanyID(ctx context.Context, arg GetCompanyFinanceByCompanyIDParams) (CompanyFinance, error) {
	row := q.db.QueryRow(ctx, getCompanyFinanceByCompanyID, arg.CompanyID, arg.FinanceID)
	var i CompanyFinance
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.FinanceID,
		&i.IsPrimary,
		&i.CreatedAt,
	)
	return i, err
}

const insertCompanyFinance = `-- name: InsertCompanyFinance :execrows
INSERT INTO company_finances(company_id, finance_id, is_primary)
    VALUES ($1, $2, $3)
`

type InsertCompanyFinanceParams struct {
	CompanyID pgtype.UUID `db:"CompanyID" json:"CompanyID"`
	FinanceID pgtype.UUID `db:"FinanceID" json:"FinanceID"`
	IsPrimary pgtype.Bool `db:"IsPrimary" json:"IsPrimary"`
}

func (q *Queries) InsertCompanyFinance(ctx context.Context, arg InsertCompanyFinanceParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertCompanyFinance, arg.CompanyID, arg.FinanceID, arg.IsPrimary)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listCompanyFinances = `-- name: ListCompanyFinances :many
SELECT
    cf.id,
    cf.company_id,
    cf.finance_id,
    cf.is_primary,
    cf.created_at,
    f.id AS finance_id,
    f.bank_name,
    f.bank_code,
    f.bank_branch,
    f.bank_account,
    f.bank_account_digit,
    f.bank_account_type,
    f.has_pix,
    f.pix_key,
    f.pix_key_type,
    f.created_at AS finance_created_at,
    f.updated_at AS finance_updated_at
FROM
    company_finances cf
    JOIN finances f ON cf.finance_id = f.id
WHERE
    cf.company_id = $1
ORDER BY
    cf.created_at DESC
LIMIT $3
OFFSET $2
`

type ListCompanyFinancesParams struct {
	CompanyID pgtype.UUID `db:"CompanyID" json:"CompanyID"`
	Offset    int32       `db:"Offset" json:"Offset"`
	Limit     int32       `db:"Limit" json:"Limit"`
}

type ListCompanyFinancesRow struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	CompanyID        pgtype.UUID        `db:"company_id" json:"company_id"`
	FinanceID        pgtype.UUID        `db:"finance_id" json:"finance_id"`
	IsPrimary        bool               `db:"is_primary" json:"is_primary"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	FinanceID_2      pgtype.UUID        `db:"finance_id_2" json:"finance_id_2"`
	BankName         string             `db:"bank_name" json:"bank_name"`
	BankCode         pgtype.Text        `db:"bank_code" json:"bank_code"`
	BankBranch       string             `db:"bank_branch" json:"bank_branch"`
	BankAccount      string             `db:"bank_account" json:"bank_account"`
	BankAccountDigit string             `db:"bank_account_digit" json:"bank_account_digit"`
	BankAccountType  BankAccountKind    `db:"bank_account_type" json:"bank_account_type"`
	HasPix           bool               `db:"has_pix" json:"has_pix"`
	PixKey           pgtype.Text        `db:"pix_key" json:"pix_key"`
	PixKeyType       NullPixKeyKind     `db:"pix_key_type" json:"pix_key_type"`
	FinanceCreatedAt pgtype.Timestamptz `db:"finance_created_at" json:"finance_created_at"`
	FinanceUpdatedAt pgtype.Timestamptz `db:"finance_updated_at" json:"finance_updated_at"`
}

func (q *Queries) ListCompanyFinances(ctx context.Context, arg ListCompanyFinancesParams) ([]ListCompanyFinancesRow, error) {
	rows, err := q.db.Query(ctx, listCompanyFinances, arg.CompanyID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompanyFinancesRow
	for rows.Next() {
		var i ListCompanyFinancesRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.FinanceID,
			&i.IsPrimary,
			&i.CreatedAt,
			&i.FinanceID_2,
			&i.BankName,
			&i.BankCode,
			&i.BankBranch,
			&i.BankAccount,
			&i.BankAccountDigit,
			&i.BankAccountType,
			&i.HasPix,
			&i.PixKey,
			&i.PixKeyType,
			&i.FinanceCreatedAt,
			&i.FinanceUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCompanyFinance = `-- name: UpdateCompanyFinance :execrows
UPDATE
    company_finances
SET
    is_primary = coalesce($1, is_primary),
    updated_at = now()
WHERE
    company_id = $2
    AND finance_id = $3
`

type UpdateCompanyFinanceParams struct {
	IsPrimary pgtype.Bool `db:"IsPrimary" json:"IsPrimary"`
	CompanyID pgtype.UUID `db:"CompanyID" json:"CompanyID"`
	FinanceID pgtype.UUID `db:"FinanceID" json:"FinanceID"`
}

func (q *Queries) UpdateCompanyFinance(ctx context.Context, arg UpdateCompanyFinanceParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCompanyFinance, arg.IsPrimary, arg.CompanyID, arg.FinanceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
