// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: company_employees.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCompanyEmployee = `-- name: DeleteCompanyEmployee :exec
UPDATE
    company_employees
SET
    deleted_at = now()
WHERE
    company_id = $1
    AND person_id = $2
    AND deleted_at IS NULL
`

type DeleteCompanyEmployeeParams struct {
	CompanyID pgtype.UUID `db:"CompanyID" json:"CompanyID"`
	PersonID  pgtype.UUID `db:"PersonID" json:"PersonID"`
}

func (q *Queries) DeleteCompanyEmployee(ctx context.Context, arg DeleteCompanyEmployeeParams) error {
	_, err := q.db.Exec(ctx, deleteCompanyEmployee, arg.CompanyID, arg.PersonID)
	return err
}

const getCompanyEmployee = `-- name: GetCompanyEmployee :one
SELECT
    ce.id AS company_employee_id,
    ce.company_id,
    ce.person_id,
    ce.created_at AS company_employee_created_at,
    ce.deleted_at AS company_employee_deleted_at,
    p.id AS person_id,
    p.kind AS person_kind,
    p.is_active AS person_is_active,
    p.has_system_user AS person_has_system_user,
    p.created_at AS person_created_at,
    p.updated_at AS person_updated_at,
    pi.full_name AS identifications_full_name,
    pi.short_name AS identifications_short_name,
    pi.created_at AS identifications_created_at,
    pi.updated_at AS identifications_updated_at,
    e.id AS employment_id,
    e.company_employee_id AS employee_id,
    e."role",
    e.admission_date,
    e.resignation_date,
    e.salary,
    e.created_at AS employment_created_at,
    e.updated_at AS employment_updated_at
FROM
    company_employees ce
    JOIN people p ON ce.person_id = p.id
    LEFT JOIN people_identifications pi ON p.id = pi.person_id
    LEFT JOIN employments e ON ce.id = e.company_employee_id
WHERE
    ce.company_id = $1
    AND ce.person_id = $2
LIMIT 1
`

type GetCompanyEmployeeParams struct {
	CompanyID pgtype.UUID `db:"CompanyID" json:"CompanyID"`
	PersonID  pgtype.UUID `db:"PersonID" json:"PersonID"`
}

type GetCompanyEmployeeRow struct {
	CompanyEmployeeID        pgtype.UUID        `db:"company_employee_id" json:"company_employee_id"`
	CompanyID                pgtype.UUID        `db:"company_id" json:"company_id"`
	PersonID                 pgtype.UUID        `db:"person_id" json:"person_id"`
	CompanyEmployeeCreatedAt pgtype.Timestamptz `db:"company_employee_created_at" json:"company_employee_created_at"`
	CompanyEmployeeDeletedAt pgtype.Timestamptz `db:"company_employee_deleted_at" json:"company_employee_deleted_at"`
	PersonID_2               pgtype.UUID        `db:"person_id_2" json:"person_id_2"`
	PersonKind               PersonKind         `db:"person_kind" json:"person_kind"`
	PersonIsActive           bool               `db:"person_is_active" json:"person_is_active"`
	PersonHasSystemUser      bool               `db:"person_has_system_user" json:"person_has_system_user"`
	PersonCreatedAt          pgtype.Timestamptz `db:"person_created_at" json:"person_created_at"`
	PersonUpdatedAt          pgtype.Timestamptz `db:"person_updated_at" json:"person_updated_at"`
	IdentificationsFullName  pgtype.Text        `db:"identifications_full_name" json:"identifications_full_name"`
	IdentificationsShortName pgtype.Text        `db:"identifications_short_name" json:"identifications_short_name"`
	IdentificationsCreatedAt pgtype.Timestamptz `db:"identifications_created_at" json:"identifications_created_at"`
	IdentificationsUpdatedAt pgtype.Timestamptz `db:"identifications_updated_at" json:"identifications_updated_at"`
	EmploymentID             pgtype.UUID        `db:"employment_id" json:"employment_id"`
	EmployeeID               pgtype.UUID        `db:"employee_id" json:"employee_id"`
	Role                     pgtype.Text        `db:"role" json:"role"`
	AdmissionDate            pgtype.Date        `db:"admission_date" json:"admission_date"`
	ResignationDate          pgtype.Date        `db:"resignation_date" json:"resignation_date"`
	Salary                   pgtype.Numeric     `db:"salary" json:"salary"`
	EmploymentCreatedAt      pgtype.Timestamptz `db:"employment_created_at" json:"employment_created_at"`
	EmploymentUpdatedAt      pgtype.Timestamptz `db:"employment_updated_at" json:"employment_updated_at"`
}

func (q *Queries) GetCompanyEmployee(ctx context.Context, arg GetCompanyEmployeeParams) (GetCompanyEmployeeRow, error) {
	row := q.db.QueryRow(ctx, getCompanyEmployee, arg.CompanyID, arg.PersonID)
	var i GetCompanyEmployeeRow
	err := row.Scan(
		&i.CompanyEmployeeID,
		&i.CompanyID,
		&i.PersonID,
		&i.CompanyEmployeeCreatedAt,
		&i.CompanyEmployeeDeletedAt,
		&i.PersonID_2,
		&i.PersonKind,
		&i.PersonIsActive,
		&i.PersonHasSystemUser,
		&i.PersonCreatedAt,
		&i.PersonUpdatedAt,
		&i.IdentificationsFullName,
		&i.IdentificationsShortName,
		&i.IdentificationsCreatedAt,
		&i.IdentificationsUpdatedAt,
		&i.EmploymentID,
		&i.EmployeeID,
		&i.Role,
		&i.AdmissionDate,
		&i.ResignationDate,
		&i.Salary,
		&i.EmploymentCreatedAt,
		&i.EmploymentUpdatedAt,
	)
	return i, err
}

const insertCompanyEmployee = `-- name: InsertCompanyEmployee :one
INSERT INTO company_employees(company_id, person_id)
    VALUES ($1, $2)
RETURNING
    id, company_id, person_id, created_at, deleted_at
`

type InsertCompanyEmployeeParams struct {
	CompanyID pgtype.UUID `db:"CompanyID" json:"CompanyID"`
	PersonID  pgtype.UUID `db:"PersonID" json:"PersonID"`
}

func (q *Queries) InsertCompanyEmployee(ctx context.Context, arg InsertCompanyEmployeeParams) (CompanyEmployee, error) {
	row := q.db.QueryRow(ctx, insertCompanyEmployee, arg.CompanyID, arg.PersonID)
	var i CompanyEmployee
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.PersonID,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listCompanyEmployees = `-- name: ListCompanyEmployees :many
SELECT
    ce.id AS company_employee_id,
    ce.company_id,
    ce.person_id,
    ce.created_at AS company_employee_created_at,
    ce.deleted_at AS company_employee_deleted_at,
    p.id AS person_id,
    p.kind AS person_kind,
    p.is_active AS person_is_active,
    p.has_system_user AS person_has_system_user,
    p.created_at AS person_created_at,
    p.updated_at AS person_updated_at,
    pi.full_name AS identifications_full_name,
    pi.short_name AS identifications_short_name,
    pi.created_at AS identifications_created_at,
    pi.updated_at AS identifications_updated_at,
    e.id AS employment_id,
    e.company_employee_id AS employee_id,
    e."role",
    e.admission_date,
    e.resignation_date,
    e.salary,
    e.created_at AS employment_created_at,
    e.updated_at AS employment_updated_at
FROM
    company_employees ce
    JOIN people p ON ce.person_id = p.id
    LEFT JOIN people_identifications pi ON p.id = pi.person_id
    LEFT JOIN employments e ON ce.id = e.company_employee_id
WHERE
    ce.company_id = $1
ORDER BY
    ce.created_at DESC
LIMIT $3
OFFSET $2
`

type ListCompanyEmployeesParams struct {
	CompanyID pgtype.UUID `db:"CompanyID" json:"CompanyID"`
	Offset    int32       `db:"Offset" json:"Offset"`
	Limit     int32       `db:"Limit" json:"Limit"`
}

type ListCompanyEmployeesRow struct {
	CompanyEmployeeID        pgtype.UUID        `db:"company_employee_id" json:"company_employee_id"`
	CompanyID                pgtype.UUID        `db:"company_id" json:"company_id"`
	PersonID                 pgtype.UUID        `db:"person_id" json:"person_id"`
	CompanyEmployeeCreatedAt pgtype.Timestamptz `db:"company_employee_created_at" json:"company_employee_created_at"`
	CompanyEmployeeDeletedAt pgtype.Timestamptz `db:"company_employee_deleted_at" json:"company_employee_deleted_at"`
	PersonID_2               pgtype.UUID        `db:"person_id_2" json:"person_id_2"`
	PersonKind               PersonKind         `db:"person_kind" json:"person_kind"`
	PersonIsActive           bool               `db:"person_is_active" json:"person_is_active"`
	PersonHasSystemUser      bool               `db:"person_has_system_user" json:"person_has_system_user"`
	PersonCreatedAt          pgtype.Timestamptz `db:"person_created_at" json:"person_created_at"`
	PersonUpdatedAt          pgtype.Timestamptz `db:"person_updated_at" json:"person_updated_at"`
	IdentificationsFullName  pgtype.Text        `db:"identifications_full_name" json:"identifications_full_name"`
	IdentificationsShortName pgtype.Text        `db:"identifications_short_name" json:"identifications_short_name"`
	IdentificationsCreatedAt pgtype.Timestamptz `db:"identifications_created_at" json:"identifications_created_at"`
	IdentificationsUpdatedAt pgtype.Timestamptz `db:"identifications_updated_at" json:"identifications_updated_at"`
	EmploymentID             pgtype.UUID        `db:"employment_id" json:"employment_id"`
	EmployeeID               pgtype.UUID        `db:"employee_id" json:"employee_id"`
	Role                     pgtype.Text        `db:"role" json:"role"`
	AdmissionDate            pgtype.Date        `db:"admission_date" json:"admission_date"`
	ResignationDate          pgtype.Date        `db:"resignation_date" json:"resignation_date"`
	Salary                   pgtype.Numeric     `db:"salary" json:"salary"`
	EmploymentCreatedAt      pgtype.Timestamptz `db:"employment_created_at" json:"employment_created_at"`
	EmploymentUpdatedAt      pgtype.Timestamptz `db:"employment_updated_at" json:"employment_updated_at"`
}

func (q *Queries) ListCompanyEmployees(ctx context.Context, arg ListCompanyEmployeesParams) ([]ListCompanyEmployeesRow, error) {
	rows, err := q.db.Query(ctx, listCompanyEmployees, arg.CompanyID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompanyEmployeesRow
	for rows.Next() {
		var i ListCompanyEmployeesRow
		if err := rows.Scan(
			&i.CompanyEmployeeID,
			&i.CompanyID,
			&i.PersonID,
			&i.CompanyEmployeeCreatedAt,
			&i.CompanyEmployeeDeletedAt,
			&i.PersonID_2,
			&i.PersonKind,
			&i.PersonIsActive,
			&i.PersonHasSystemUser,
			&i.PersonCreatedAt,
			&i.PersonUpdatedAt,
			&i.IdentificationsFullName,
			&i.IdentificationsShortName,
			&i.IdentificationsCreatedAt,
			&i.IdentificationsUpdatedAt,
			&i.EmploymentID,
			&i.EmployeeID,
			&i.Role,
			&i.AdmissionDate,
			&i.ResignationDate,
			&i.Salary,
			&i.EmploymentCreatedAt,
			&i.EmploymentUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
