// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: company_users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCompanyUser = `-- name: CreateCompanyUser :one
INSERT INTO company_users(company_id, user_id, kind, is_active)
    VALUES ($1, $2, $3, $4)
RETURNING
    id, company_id, user_id, kind, is_active, created_at, updated_at, deleted_at
`

type CreateCompanyUserParams struct {
	CompanyID pgtype.UUID `db:"CompanyID" json:"CompanyID"`
	UserID    pgtype.UUID `db:"UserID" json:"UserID"`
	Kind      UserKind    `db:"Kind" json:"Kind"`
	IsActive  pgtype.Bool `db:"IsActive" json:"IsActive"`
}

func (q *Queries) CreateCompanyUser(ctx context.Context, arg CreateCompanyUserParams) (CompanyUser, error) {
	row := q.db.QueryRow(ctx, createCompanyUser,
		arg.CompanyID,
		arg.UserID,
		arg.Kind,
		arg.IsActive,
	)
	var i CompanyUser
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.Kind,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deactivateCompanyUser = `-- name: DeactivateCompanyUser :exec
UPDATE
    company_users
SET
    is_active = FALSE,
    deleted_at = now()
WHERE
    company_id = $1
    AND user_id = $2
`

type DeactivateCompanyUserParams struct {
	CompanyID pgtype.UUID `db:"CompanyID" json:"CompanyID"`
	UserID    pgtype.UUID `db:"UserID" json:"UserID"`
}

func (q *Queries) DeactivateCompanyUser(ctx context.Context, arg DeactivateCompanyUserParams) error {
	_, err := q.db.Exec(ctx, deactivateCompanyUser, arg.CompanyID, arg.UserID)
	return err
}

const getActiveCompanyUserByUserID = `-- name: GetActiveCompanyUserByUserID :one
SELECT
    cu.id,
    cu.company_id,
    cu.user_id,
    cu.kind,
    cu.is_active,
    cu.created_at,
    cu.updated_at,
    cu.deleted_at
FROM
    company_users cu
WHERE
    cu.user_id = $1
    AND cu.is_active = TRUE
ORDER BY
    cu.kind DESC,
    cu.created_at ASC
LIMIT 1
`

func (q *Queries) GetActiveCompanyUserByUserID(ctx context.Context, userid pgtype.UUID) (CompanyUser, error) {
	row := q.db.QueryRow(ctx, getActiveCompanyUserByUserID, userid)
	var i CompanyUser
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.Kind,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCompanyUser = `-- name: GetCompanyUser :one
SELECT
    cu.id,
    cu.company_id,
    cu.user_id,
    cu.kind,
    cu.is_active,
    cu.created_at,
    cu.updated_at,
    cu.deleted_at
FROM
    company_users cu
WHERE
    cu.company_id = $1
    AND cu.user_id = $2
LIMIT 1
`

type GetCompanyUserParams struct {
	CompanyID pgtype.UUID `db:"CompanyID" json:"CompanyID"`
	UserID    pgtype.UUID `db:"UserID" json:"UserID"`
}

func (q *Queries) GetCompanyUser(ctx context.Context, arg GetCompanyUserParams) (CompanyUser, error) {
	row := q.db.QueryRow(ctx, getCompanyUser, arg.CompanyID, arg.UserID)
	var i CompanyUser
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.Kind,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCompanyUserByID = `-- name: GetCompanyUserByID :one
SELECT
    cu.id,
    cu.company_id,
    cu.user_id,
    cu.kind,
    cu.is_active,
    cu.created_at,
    cu.updated_at,
    cu.deleted_at
FROM
    company_users cu
WHERE
    cu.id = $1
LIMIT 1
`

func (q *Queries) GetCompanyUserByID(ctx context.Context, id pgtype.UUID) (CompanyUser, error) {
	row := q.db.QueryRow(ctx, getCompanyUserByID, id)
	var i CompanyUser
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.Kind,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listCompanyUsersByCompanyID = `-- name: ListCompanyUsersByCompanyID :many
SELECT
    cu.id,
    cu.company_id,
    cu.user_id,
    cu.kind,
    cu.is_active,
    cu.created_at,
    cu.updated_at,
    cu.deleted_at
FROM
    company_users cu
WHERE
    cu.company_id = $1
    AND cu.is_active = TRUE
ORDER BY
    cu.created_at DESC
`

func (q *Queries) ListCompanyUsersByCompanyID(ctx context.Context, companyid pgtype.UUID) ([]CompanyUser, error) {
	rows, err := q.db.Query(ctx, listCompanyUsersByCompanyID, companyid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompanyUser
	for rows.Next() {
		var i CompanyUser
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.UserID,
			&i.Kind,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompanyUsersByKind = `-- name: ListCompanyUsersByKind :many
SELECT
    cu.id,
    cu.company_id,
    cu.user_id,
    cu.kind,
    cu.is_active,
    cu.created_at,
    cu.updated_at,
    cu.deleted_at
FROM
    company_users cu
WHERE
    cu.company_id = $1
    AND cu.kind = $2
    AND cu.is_active = TRUE
ORDER BY
    cu.created_at DESC
LIMIT $4
OFFSET $3
`

type ListCompanyUsersByKindParams struct {
	CompanyID pgtype.UUID `db:"CompanyID" json:"CompanyID"`
	Kind      UserKind    `db:"Kind" json:"Kind"`
	Offset    int32       `db:"Offset" json:"Offset"`
	Limit     int32       `db:"Limit" json:"Limit"`
}

func (q *Queries) ListCompanyUsersByKind(ctx context.Context, arg ListCompanyUsersByKindParams) ([]CompanyUser, error) {
	rows, err := q.db.Query(ctx, listCompanyUsersByKind,
		arg.CompanyID,
		arg.Kind,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompanyUser
	for rows.Next() {
		var i CompanyUser
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.UserID,
			&i.Kind,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
