// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: company_business_costs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCompanyBusinessCost = `-- name: DeleteCompanyBusinessCost :execrows
UPDATE
    company_business_costs
SET
    deleted_at = now(),
    updated_at = now()
WHERE
    id = $1
    AND company_id = $2
    AND deleted_at IS NULL
`

type DeleteCompanyBusinessCostParams struct {
	ID        pgtype.UUID `db:"ID" json:"ID"`
	CompanyID pgtype.UUID `db:"CompanyID" json:"CompanyID"`
}

func (q *Queries) DeleteCompanyBusinessCost(ctx context.Context, arg DeleteCompanyBusinessCostParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCompanyBusinessCost, arg.ID, arg.CompanyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCompanyBusinessCostByID = `-- name: GetCompanyBusinessCostByID :one
SELECT
    cbc.id,
    cbc.company_id,
    cbc.invoice_number,
    cbc.invoice_url,
    cbc.description,
    cbc.total_cost,
    cbc.reference_month,
    cbc.comments,
    cbc.created_at,
    cbc.updated_at,
    cbc.deleted_at
FROM
    company_business_costs cbc
WHERE
    cbc.id = $1
    AND cbc.company_id = $2
    AND cbc.deleted_at IS NULL
LIMIT 1
`

type GetCompanyBusinessCostByIDParams struct {
	ID        pgtype.UUID `db:"ID" json:"ID"`
	CompanyID pgtype.UUID `db:"CompanyID" json:"CompanyID"`
}

func (q *Queries) GetCompanyBusinessCostByID(ctx context.Context, arg GetCompanyBusinessCostByIDParams) (CompanyBusinessCost, error) {
	row := q.db.QueryRow(ctx, getCompanyBusinessCostByID, arg.ID, arg.CompanyID)
	var i CompanyBusinessCost
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.InvoiceNumber,
		&i.InvoiceUrl,
		&i.Description,
		&i.TotalCost,
		&i.ReferenceMonth,
		&i.Comments,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertCompanyBusinessCost = `-- name: InsertCompanyBusinessCost :one
INSERT INTO company_business_costs(company_id, invoice_number, invoice_url, description, total_cost, reference_month, comments)
    VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING
    id, company_id, invoice_number, invoice_url, description, total_cost, reference_month, comments, created_at, updated_at, deleted_at
`

type InsertCompanyBusinessCostParams struct {
	CompanyID      pgtype.UUID    `db:"CompanyID" json:"CompanyID"`
	InvoiceNumber  pgtype.Text    `db:"InvoiceNumber" json:"InvoiceNumber"`
	InvoiceURL     pgtype.Text    `db:"InvoiceURL" json:"InvoiceURL"`
	Description    string         `db:"Description" json:"Description"`
	TotalCost      pgtype.Numeric `db:"TotalCost" json:"TotalCost"`
	ReferenceMonth pgtype.Date    `db:"ReferenceMonth" json:"ReferenceMonth"`
	Comments       pgtype.Text    `db:"Comments" json:"Comments"`
}

func (q *Queries) InsertCompanyBusinessCost(ctx context.Context, arg InsertCompanyBusinessCostParams) (CompanyBusinessCost, error) {
	row := q.db.QueryRow(ctx, insertCompanyBusinessCost,
		arg.CompanyID,
		arg.InvoiceNumber,
		arg.InvoiceURL,
		arg.Description,
		arg.TotalCost,
		arg.ReferenceMonth,
		arg.Comments,
	)
	var i CompanyBusinessCost
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.InvoiceNumber,
		&i.InvoiceUrl,
		&i.Description,
		&i.TotalCost,
		&i.ReferenceMonth,
		&i.Comments,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listCompanyBusinessCosts = `-- name: ListCompanyBusinessCosts :many
SELECT
    cbc.id,
    cbc.company_id,
    cbc.invoice_number,
    cbc.invoice_url,
    cbc.description,
    cbc.total_cost,
    cbc.reference_month,
    cbc.comments,
    cbc.created_at,
    cbc.updated_at,
    cbc.deleted_at
FROM
    company_business_costs cbc
WHERE
    cbc.company_id = $1
    AND cbc.deleted_at IS NULL
ORDER BY
    cbc.reference_month DESC
LIMIT $3
OFFSET $2
`

type ListCompanyBusinessCostsParams struct {
	CompanyID pgtype.UUID `db:"CompanyID" json:"CompanyID"`
	Offset    int32       `db:"Offset" json:"Offset"`
	Limit     int32       `db:"Limit" json:"Limit"`
}

func (q *Queries) ListCompanyBusinessCosts(ctx context.Context, arg ListCompanyBusinessCostsParams) ([]CompanyBusinessCost, error) {
	rows, err := q.db.Query(ctx, listCompanyBusinessCosts, arg.CompanyID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompanyBusinessCost
	for rows.Next() {
		var i CompanyBusinessCost
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.InvoiceNumber,
			&i.InvoiceUrl,
			&i.Description,
			&i.TotalCost,
			&i.ReferenceMonth,
			&i.Comments,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompanyBusinessCostsByMonth = `-- name: ListCompanyBusinessCostsByMonth :many
SELECT
    cbc.id,
    cbc.company_id,
    cbc.invoice_number,
    cbc.invoice_url,
    cbc.description,
    cbc.total_cost,
    cbc.reference_month,
    cbc.comments,
    cbc.created_at,
    cbc.updated_at,
    cbc.deleted_at
FROM
    company_business_costs cbc
WHERE
    cbc.company_id = $1
    AND cbc.reference_month = $2
    AND cbc.deleted_at IS NULL
ORDER BY
    cbc.created_at DESC
LIMIT $4
OFFSET $3
`

type ListCompanyBusinessCostsByMonthParams struct {
	CompanyID      pgtype.UUID `db:"CompanyID" json:"CompanyID"`
	ReferenceMonth pgtype.Date `db:"ReferenceMonth" json:"ReferenceMonth"`
	Offset         int32       `db:"Offset" json:"Offset"`
	Limit          int32       `db:"Limit" json:"Limit"`
}

func (q *Queries) ListCompanyBusinessCostsByMonth(ctx context.Context, arg ListCompanyBusinessCostsByMonthParams) ([]CompanyBusinessCost, error) {
	rows, err := q.db.Query(ctx, listCompanyBusinessCostsByMonth,
		arg.CompanyID,
		arg.ReferenceMonth,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompanyBusinessCost
	for rows.Next() {
		var i CompanyBusinessCost
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.InvoiceNumber,
			&i.InvoiceUrl,
			&i.Description,
			&i.TotalCost,
			&i.ReferenceMonth,
			&i.Comments,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCompanyBusinessCost = `-- name: UpdateCompanyBusinessCost :execrows
UPDATE
    company_business_costs
SET
    invoice_number = coalesce($1, invoice_number),
    invoice_url = coalesce($2, invoice_url),
    description = coalesce($3, description),
    total_cost = coalesce($4, total_cost),
    reference_month = coalesce($5, reference_month),
    comments = coalesce($6, comments),
    updated_at = now()
WHERE
    id = $7
    AND company_id = $8
    AND deleted_at IS NULL
`

type UpdateCompanyBusinessCostParams struct {
	InvoiceNumber  pgtype.Text    `db:"InvoiceNumber" json:"InvoiceNumber"`
	InvoiceURL     pgtype.Text    `db:"InvoiceURL" json:"InvoiceURL"`
	Description    pgtype.Text    `db:"Description" json:"Description"`
	TotalCost      pgtype.Numeric `db:"TotalCost" json:"TotalCost"`
	ReferenceMonth pgtype.Date    `db:"ReferenceMonth" json:"ReferenceMonth"`
	Comments       pgtype.Text    `db:"Comments" json:"Comments"`
	ID             pgtype.UUID    `db:"ID" json:"ID"`
	CompanyID      pgtype.UUID    `db:"CompanyID" json:"CompanyID"`
}

func (q *Queries) UpdateCompanyBusinessCost(ctx context.Context, arg UpdateCompanyBusinessCostParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCompanyBusinessCost,
		arg.InvoiceNumber,
		arg.InvoiceURL,
		arg.Description,
		arg.TotalCost,
		arg.ReferenceMonth,
		arg.Comments,
		arg.ID,
		arg.CompanyID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
