// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: company_users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCompanyUser = `-- name: CreateCompanyUser :one
INSERT INTO company_users(company_id, user_id, is_owner, is_active)
    VALUES ($1, $2, $3, $4)
RETURNING
    id, company_id, user_id, is_owner, is_active, joined_at, left_at
`

type CreateCompanyUserParams struct {
	CompanyID pgtype.UUID `db:"company_id" json:"company_id"`
	UserID    pgtype.UUID `db:"user_id" json:"user_id"`
	IsOwner   bool        `db:"is_owner" json:"is_owner"`
	IsActive  bool        `db:"is_active" json:"is_active"`
}

func (q *Queries) CreateCompanyUser(ctx context.Context, arg CreateCompanyUserParams) (CompanyUser, error) {
	row := q.db.QueryRow(ctx, createCompanyUser,
		arg.CompanyID,
		arg.UserID,
		arg.IsOwner,
		arg.IsActive,
	)
	var i CompanyUser
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.IsOwner,
		&i.IsActive,
		&i.JoinedAt,
		&i.LeftAt,
	)
	return i, err
}

const deactivateCompanyUser = `-- name: DeactivateCompanyUser :exec
UPDATE
    company_users
SET
    is_active = FALSE,
    left_at = now()
WHERE
    company_id = $1
    AND user_id = $2
`

type DeactivateCompanyUserParams struct {
	CompanyID pgtype.UUID `db:"CompanyID" json:"CompanyID"`
	UserID    pgtype.UUID `db:"UserID" json:"UserID"`
}

func (q *Queries) DeactivateCompanyUser(ctx context.Context, arg DeactivateCompanyUserParams) error {
	_, err := q.db.Exec(ctx, deactivateCompanyUser, arg.CompanyID, arg.UserID)
	return err
}

const getCompanyUser = `-- name: GetCompanyUser :one
SELECT
    cu.id,
    cu.company_id,
    cu.user_id,
    cu.is_owner,
    cu.is_active,
    cu.joined_at,
    cu.left_at
FROM
    company_users cu
WHERE
    cu.company_id = $1
    AND cu.user_id = $2
LIMIT 1
`

type GetCompanyUserParams struct {
	CompanyID pgtype.UUID `db:"CompanyID" json:"CompanyID"`
	UserID    pgtype.UUID `db:"UserID" json:"UserID"`
}

func (q *Queries) GetCompanyUser(ctx context.Context, arg GetCompanyUserParams) (CompanyUser, error) {
	row := q.db.QueryRow(ctx, getCompanyUser, arg.CompanyID, arg.UserID)
	var i CompanyUser
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.IsOwner,
		&i.IsActive,
		&i.JoinedAt,
		&i.LeftAt,
	)
	return i, err
}

const getCompanyUserByID = `-- name: GetCompanyUserByID :one
SELECT
    cu.id,
    cu.company_id,
    cu.user_id,
    cu.is_owner,
    cu.is_active,
    cu.joined_at,
    cu.left_at
FROM
    company_users cu
WHERE
    cu.id = $1
LIMIT 1
`

func (q *Queries) GetCompanyUserByID(ctx context.Context, id pgtype.UUID) (CompanyUser, error) {
	row := q.db.QueryRow(ctx, getCompanyUserByID, id)
	var i CompanyUser
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.IsOwner,
		&i.IsActive,
		&i.JoinedAt,
		&i.LeftAt,
	)
	return i, err
}

const listCompanyUsersByCompanyID = `-- name: ListCompanyUsersByCompanyID :many
SELECT
    cu.id,
    cu.company_id,
    cu.user_id,
    cu.is_owner,
    cu.is_active,
    cu.joined_at,
    cu.left_at
FROM
    company_users cu
WHERE
    cu.company_id = $1
    AND cu.is_active = TRUE
ORDER BY
    cu.joined_at DESC
`

func (q *Queries) ListCompanyUsersByCompanyID(ctx context.Context, companyid pgtype.UUID) ([]CompanyUser, error) {
	rows, err := q.db.Query(ctx, listCompanyUsersByCompanyID, companyid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompanyUser
	for rows.Next() {
		var i CompanyUser
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.UserID,
			&i.IsOwner,
			&i.IsActive,
			&i.JoinedAt,
			&i.LeftAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
