// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: employments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEmployment = `-- name: GetEmployment :one
SELECT
    p.id AS person_id,
    p.kind AS person_kind,
    p.is_active AS person_is_active,
    p.has_system_user AS person_has_system_user,
    p.created_at AS person_created_at,
    p.updated_at AS person_updated_at,
    pi.full_name AS identifications_full_name,
    PI.short_name AS identifications_short_name,
    pi.gender_identity AS identifications_gender_identity,
    pi.marital_status AS identifications_marital_status,
    pi.image_url AS identifications_image_url,
    pi.birth_date AS identifications_birth_date,
    pi.cpf AS identifications_cpf,
    pi.created_at AS identifications_created_at,
    pi.updated_at AS identifications_updated_at,
    e.id AS employment_id,
    e.company_employee_id AS employee_id,
    e."role",
    e.admission_date,
    e.resignation_date,
    e.salary,
    e.created_at,
    e.updated_at
FROM
    employments e
    JOIN company_employees ce ON e.company_employee_id = ce.id
    JOIN people p ON ce.person_id = p.id
    LEFT JOIN people_identifications pi ON p.id = pi.person_id
WHERE
    e.id = $1
`

type GetEmploymentRow struct {
	PersonID                      pgtype.UUID        `db:"person_id" json:"person_id"`
	PersonKind                    PersonKind         `db:"person_kind" json:"person_kind"`
	PersonIsActive                bool               `db:"person_is_active" json:"person_is_active"`
	PersonHasSystemUser           bool               `db:"person_has_system_user" json:"person_has_system_user"`
	PersonCreatedAt               pgtype.Timestamptz `db:"person_created_at" json:"person_created_at"`
	PersonUpdatedAt               pgtype.Timestamptz `db:"person_updated_at" json:"person_updated_at"`
	IdentificationsFullName       pgtype.Text        `db:"identifications_full_name" json:"identifications_full_name"`
	IdentificationsShortName      pgtype.Text        `db:"identifications_short_name" json:"identifications_short_name"`
	IdentificationsGenderIdentity NullGenderIdentity `db:"identifications_gender_identity" json:"identifications_gender_identity"`
	IdentificationsMaritalStatus  NullMaritalStatus  `db:"identifications_marital_status" json:"identifications_marital_status"`
	IdentificationsImageUrl       pgtype.Text        `db:"identifications_image_url" json:"identifications_image_url"`
	IdentificationsBirthDate      pgtype.Date        `db:"identifications_birth_date" json:"identifications_birth_date"`
	IdentificationsCpf            pgtype.Text        `db:"identifications_cpf" json:"identifications_cpf"`
	IdentificationsCreatedAt      pgtype.Timestamptz `db:"identifications_created_at" json:"identifications_created_at"`
	IdentificationsUpdatedAt      pgtype.Timestamptz `db:"identifications_updated_at" json:"identifications_updated_at"`
	EmploymentID                  pgtype.UUID        `db:"employment_id" json:"employment_id"`
	EmployeeID                    pgtype.UUID        `db:"employee_id" json:"employee_id"`
	Role                          string             `db:"role" json:"role"`
	AdmissionDate                 pgtype.Date        `db:"admission_date" json:"admission_date"`
	ResignationDate               pgtype.Date        `db:"resignation_date" json:"resignation_date"`
	Salary                        pgtype.Numeric     `db:"salary" json:"salary"`
	CreatedAt                     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetEmployment(ctx context.Context, id pgtype.UUID) (GetEmploymentRow, error) {
	row := q.db.QueryRow(ctx, getEmployment, id)
	var i GetEmploymentRow
	err := row.Scan(
		&i.PersonID,
		&i.PersonKind,
		&i.PersonIsActive,
		&i.PersonHasSystemUser,
		&i.PersonCreatedAt,
		&i.PersonUpdatedAt,
		&i.IdentificationsFullName,
		&i.IdentificationsShortName,
		&i.IdentificationsGenderIdentity,
		&i.IdentificationsMaritalStatus,
		&i.IdentificationsImageUrl,
		&i.IdentificationsBirthDate,
		&i.IdentificationsCpf,
		&i.IdentificationsCreatedAt,
		&i.IdentificationsUpdatedAt,
		&i.EmploymentID,
		&i.EmployeeID,
		&i.Role,
		&i.AdmissionDate,
		&i.ResignationDate,
		&i.Salary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertEployment = `-- name: InsertEployment :execrows
INSERT INTO employments(company_employee_id, "role", admission_date, resignation_date, salary)
    VALUES ($1, $2, $3, $4, $5)
`

type InsertEploymentParams struct {
	CompanyEmployeeID pgtype.UUID    `db:"CompanyEmployeeID" json:"CompanyEmployeeID"`
	Role              string         `db:"Role" json:"Role"`
	AdmissionDate     pgtype.Date    `db:"AdmissionDate" json:"AdmissionDate"`
	ResignationDate   pgtype.Date    `db:"ResignationDate" json:"ResignationDate"`
	Salary            pgtype.Numeric `db:"Salary" json:"Salary"`
}

func (q *Queries) InsertEployment(ctx context.Context, arg InsertEploymentParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertEployment,
		arg.CompanyEmployeeID,
		arg.Role,
		arg.AdmissionDate,
		arg.ResignationDate,
		arg.Salary,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateEmployment = `-- name: UpdateEmployment :execrows
UPDATE
    employments
SET
    "role" = COALESCE($1, "role"),
    admission_date = COALESCE($2, admission_date),
    resignation_date = COALESCE($3, resignation_date),
    salary = COALESCE($4, salary),
    updated_at = now()
WHERE
    id = $5
`

type UpdateEmploymentParams struct {
	Role            pgtype.Text    `db:"Role" json:"Role"`
	AdmissionDate   pgtype.Date    `db:"AdmissionDate" json:"AdmissionDate"`
	ResignationDate pgtype.Date    `db:"ResignationDate" json:"ResignationDate"`
	Salary          pgtype.Numeric `db:"Salary" json:"Salary"`
	ID              pgtype.UUID    `db:"ID" json:"ID"`
}

func (q *Queries) UpdateEmployment(ctx context.Context, arg UpdateEmploymentParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateEmployment,
		arg.Role,
		arg.AdmissionDate,
		arg.ResignationDate,
		arg.Salary,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
