// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: finances.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteFinance = `-- name: DeleteFinance :execrows
DELETE FROM finances
WHERE id = $1
`

func (q *Queries) DeleteFinance(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFinance, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getFinance = `-- name: GetFinance :one
SELECT
    f.id,
    f.bank_name,
    f.bank_code,
    f.bank_branch,
    f.bank_account,
    f.bank_account_digit,
    f.bank_account_type,
    f.has_pix,
    f.pix_key,
    f.pix_key_type,
    f.created_at,
    f.updated_at
FROM
    finances f
WHERE
    f.id = $1
`

func (q *Queries) GetFinance(ctx context.Context, id pgtype.UUID) (Finance, error) {
	row := q.db.QueryRow(ctx, getFinance, id)
	var i Finance
	err := row.Scan(
		&i.ID,
		&i.BankName,
		&i.BankCode,
		&i.BankBranch,
		&i.BankAccount,
		&i.BankAccountDigit,
		&i.BankAccountType,
		&i.HasPix,
		&i.PixKey,
		&i.PixKeyType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertFinance = `-- name: InsertFinance :one
INSERT INTO finances(bank_name, bank_code, bank_branch, bank_account, bank_account_digit, bank_account_type, has_pix, pix_key, pix_key_type)
    VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, bank_name, bank_code, bank_branch, bank_account, bank_account_digit, bank_account_type, has_pix, pix_key, pix_key_type, created_at, updated_at
`

type InsertFinanceParams struct {
	BankName         string          `db:"BankName" json:"BankName"`
	BankCode         pgtype.Text     `db:"BankCode" json:"BankCode"`
	BankBranch       string          `db:"BankBranch" json:"BankBranch"`
	BankAccount      string          `db:"BankAccount" json:"BankAccount"`
	BankAccountDigit string          `db:"BankAccountDigit" json:"BankAccountDigit"`
	BankAccountType  BankAccountKind `db:"BankAccountType" json:"BankAccountType"`
	HasPix           pgtype.Bool     `db:"HasPix" json:"HasPix"`
	PixKey           pgtype.Text     `db:"PixKey" json:"PixKey"`
	PixKeyType       NullPixKeyKind  `db:"PixKeyType" json:"PixKeyType"`
}

func (q *Queries) InsertFinance(ctx context.Context, arg InsertFinanceParams) (Finance, error) {
	row := q.db.QueryRow(ctx, insertFinance,
		arg.BankName,
		arg.BankCode,
		arg.BankBranch,
		arg.BankAccount,
		arg.BankAccountDigit,
		arg.BankAccountType,
		arg.HasPix,
		arg.PixKey,
		arg.PixKeyType,
	)
	var i Finance
	err := row.Scan(
		&i.ID,
		&i.BankName,
		&i.BankCode,
		&i.BankBranch,
		&i.BankAccount,
		&i.BankAccountDigit,
		&i.BankAccountType,
		&i.HasPix,
		&i.PixKey,
		&i.PixKeyType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFinance = `-- name: UpdateFinance :execrows
UPDATE
    finances
SET
    bank_name = COALESCE($1, bank_name),
    bank_code = COALESCE($2, bank_code),
    bank_branch = COALESCE($3, bank_branch),
    bank_account = COALESCE($4, bank_account),
    bank_account_digit = COALESCE($5, bank_account_digit),
    bank_account_type = COALESCE($6, bank_account_type),
    has_pix = COALESCE($7, has_pix),
    pix_key = COALESCE($8, pix_key),
    pix_key_type = COALESCE($9, pix_key_type),
    updated_at = now()
WHERE
    id = $10
`

type UpdateFinanceParams struct {
	BankName         pgtype.Text         `db:"BankName" json:"BankName"`
	BankCode         pgtype.Text         `db:"BankCode" json:"BankCode"`
	BankBranch       pgtype.Text         `db:"BankBranch" json:"BankBranch"`
	BankAccount      pgtype.Text         `db:"BankAccount" json:"BankAccount"`
	BankAccountDigit pgtype.Text         `db:"BankAccountDigit" json:"BankAccountDigit"`
	BankAccountType  NullBankAccountKind `db:"BankAccountType" json:"BankAccountType"`
	HasPix           pgtype.Bool         `db:"HasPix" json:"HasPix"`
	PixKey           pgtype.Text         `db:"PixKey" json:"PixKey"`
	PixKeyType       NullPixKeyKind      `db:"PixKeyType" json:"PixKeyType"`
	ID               pgtype.UUID         `db:"ID" json:"ID"`
}

func (q *Queries) UpdateFinance(ctx context.Context, arg UpdateFinanceParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateFinance,
		arg.BankName,
		arg.BankCode,
		arg.BankBranch,
		arg.BankAccount,
		arg.BankAccountDigit,
		arg.BankAccountType,
		arg.HasPix,
		arg.PixKey,
		arg.PixKeyType,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
