// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: languages.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteLanguage = `-- name: DeleteLanguage :execrows
DELETE FROM languages
WHERE id = $1
`

func (q *Queries) DeleteLanguage(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLanguage, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLanguageByCode = `-- name: GetLanguageByCode :one
SELECT
    l.id,
    l.code,
    l."name",
    l.native_name,
    l.created_at,
    l.updated_at
FROM
    languages l
WHERE
    l.code = $1
`

type GetLanguageByCodeRow struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	Code       string             `db:"code" json:"code"`
	Name       string             `db:"name" json:"name"`
	NativeName string             `db:"native_name" json:"native_name"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetLanguageByCode(ctx context.Context, code string) (GetLanguageByCodeRow, error) {
	row := q.db.QueryRow(ctx, getLanguageByCode, code)
	var i GetLanguageByCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.NativeName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertLanguage = `-- name: InsertLanguage :execrows
INSERT INTO languages(code, "name", native_name)
    VALUES ($1, $2, $3)
`

type InsertLanguageParams struct {
	Code       string `db:"Code" json:"Code"`
	Name       string `db:"Name" json:"Name"`
	NativeName string `db:"NativeName" json:"NativeName"`
}

func (q *Queries) InsertLanguage(ctx context.Context, arg InsertLanguageParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertLanguage, arg.Code, arg.Name, arg.NativeName)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listLanguages = `-- name: ListLanguages :many
SELECT
    l.id,
    l.code,
    l."name",
    l.native_name,
    l.created_at,
    l.updated_at
FROM
    languages l
ORDER BY
    l.code ASC
LIMIT $2
    OFFSET $1
`

type ListLanguagesParams struct {
	Offset int32 `db:"Offset" json:"Offset"`
	Limit  int32 `db:"Limit" json:"Limit"`
}

type ListLanguagesRow struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	Code       string             `db:"code" json:"code"`
	Name       string             `db:"name" json:"name"`
	NativeName string             `db:"native_name" json:"native_name"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListLanguages(ctx context.Context, arg ListLanguagesParams) ([]ListLanguagesRow, error) {
	rows, err := q.db.Query(ctx, listLanguages, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLanguagesRow
	for rows.Next() {
		var i ListLanguagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.NativeName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLanguage = `-- name: UpdateLanguage :execrows
UPDATE
    languages
SET
    code = coalesce($1, code),
    "name" = coalesce($2, "name"),
    native_name = coalesce($3, native_name),
    updated_at = now()
WHERE
    id = $4
`

type UpdateLanguageParams struct {
	Code       pgtype.Text `db:"Code" json:"Code"`
	Name       pgtype.Text `db:"Name" json:"Name"`
	NativeName pgtype.Text `db:"NativeName" json:"NativeName"`
	ID         pgtype.UUID `db:"ID" json:"ID"`
}

func (q *Queries) UpdateLanguage(ctx context.Context, arg UpdateLanguageParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateLanguage,
		arg.Code,
		arg.Name,
		arg.NativeName,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
