// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: login_history.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLoginHistoryByID = `-- name: GetLoginHistoryByID :one
SELECT
    lh.id,
    lh.user_id,
    lh.ip_address,
    lh.user_agent,
    lh.result,
    lh.failure_detail,
    lh.attempted_at
FROM
    login_history lh
WHERE
    lh.id = $1
LIMIT 1
`

func (q *Queries) GetLoginHistoryByID(ctx context.Context, id pgtype.UUID) (LoginHistory, error) {
	row := q.db.QueryRow(ctx, getLoginHistoryByID, id)
	var i LoginHistory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IpAddress,
		&i.UserAgent,
		&i.Result,
		&i.FailureDetail,
		&i.AttemptedAt,
	)
	return i, err
}

const listLoginHistoryByResult = `-- name: ListLoginHistoryByResult :many
SELECT
    lh.id,
    lh.user_id,
    lh.ip_address,
    lh.user_agent,
    lh.result,
    lh.failure_detail,
    lh.attempted_at
FROM
    login_history lh
WHERE
    lh.result = $1
ORDER BY
    lh.attempted_at DESC
LIMIT $3
OFFSET $2
`

type ListLoginHistoryByResultParams struct {
	Result LoginResult `db:"Result" json:"Result"`
	Offset int32       `db:"Offset" json:"Offset"`
	Limit  int32       `db:"Limit" json:"Limit"`
}

func (q *Queries) ListLoginHistoryByResult(ctx context.Context, arg ListLoginHistoryByResultParams) ([]LoginHistory, error) {
	rows, err := q.db.Query(ctx, listLoginHistoryByResult, arg.Result, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoginHistory
	for rows.Next() {
		var i LoginHistory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.IpAddress,
			&i.UserAgent,
			&i.Result,
			&i.FailureDetail,
			&i.AttemptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLoginHistoryByUserID = `-- name: ListLoginHistoryByUserID :many
SELECT
    lh.id,
    lh.user_id,
    lh.ip_address,
    lh.user_agent,
    lh.result,
    lh.failure_detail,
    lh.attempted_at
FROM
    login_history lh
WHERE
    lh.user_id = $1
ORDER BY
    lh.attempted_at DESC
LIMIT $3
OFFSET $2
`

type ListLoginHistoryByUserIDParams struct {
	UserID pgtype.UUID `db:"UserID" json:"UserID"`
	Offset int32       `db:"Offset" json:"Offset"`
	Limit  int32       `db:"Limit" json:"Limit"`
}

func (q *Queries) ListLoginHistoryByUserID(ctx context.Context, arg ListLoginHistoryByUserIDParams) ([]LoginHistory, error) {
	rows, err := q.db.Query(ctx, listLoginHistoryByUserID, arg.UserID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoginHistory
	for rows.Next() {
		var i LoginHistory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.IpAddress,
			&i.UserAgent,
			&i.Result,
			&i.FailureDetail,
			&i.AttemptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
