// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type BankAccountKind string

const (
	BankAccountKindChecking BankAccountKind = "checking"
	BankAccountKindSavings  BankAccountKind = "savings"
	BankAccountKindSalary   BankAccountKind = "salary"
)

func (e *BankAccountKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BankAccountKind(s)
	case string:
		*e = BankAccountKind(s)
	default:
		return fmt.Errorf("unsupported scan type for BankAccountKind: %T", src)
	}
	return nil
}

type NullBankAccountKind struct {
	BankAccountKind BankAccountKind `json:"bank_account_kind"`
	Valid           bool            `json:"valid"` // Valid is true if BankAccountKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBankAccountKind) Scan(value interface{}) error {
	if value == nil {
		ns.BankAccountKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BankAccountKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBankAccountKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BankAccountKind), nil
}

type EmployeeKind string

const (
	EmployeeKindInternal   EmployeeKind = "internal"
	EmployeeKindOutsourced EmployeeKind = "outsourced"
)

func (e *EmployeeKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EmployeeKind(s)
	case string:
		*e = EmployeeKind(s)
	default:
		return fmt.Errorf("unsupported scan type for EmployeeKind: %T", src)
	}
	return nil
}

type NullEmployeeKind struct {
	EmployeeKind EmployeeKind `json:"employee_kind"`
	Valid        bool         `json:"valid"` // Valid is true if EmployeeKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEmployeeKind) Scan(value interface{}) error {
	if value == nil {
		ns.EmployeeKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EmployeeKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEmployeeKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EmployeeKind), nil
}

type GenderIdentity string

const (
	GenderIdentityManCisgender        GenderIdentity = "man_cisgender"
	GenderIdentityWomanCisgender      GenderIdentity = "woman_cisgender"
	GenderIdentityTransgender         GenderIdentity = "transgender"
	GenderIdentityNonBinary           GenderIdentity = "non_binary"
	GenderIdentityGenderFluid         GenderIdentity = "gender_fluid"
	GenderIdentityGenderQueer         GenderIdentity = "gender_queer"
	GenderIdentityAgender             GenderIdentity = "agender"
	GenderIdentityGenderNonConforming GenderIdentity = "gender_non_conforming"
	GenderIdentityNotToExpose         GenderIdentity = "not_to_expose"
)

func (e *GenderIdentity) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GenderIdentity(s)
	case string:
		*e = GenderIdentity(s)
	default:
		return fmt.Errorf("unsupported scan type for GenderIdentity: %T", src)
	}
	return nil
}

type NullGenderIdentity struct {
	GenderIdentity GenderIdentity `json:"gender_identity"`
	Valid          bool           `json:"valid"` // Valid is true if GenderIdentity is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGenderIdentity) Scan(value interface{}) error {
	if value == nil {
		ns.GenderIdentity, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GenderIdentity.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGenderIdentity) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GenderIdentity), nil
}

type GraduationLevel string

const (
	GraduationLevelElementaryIncomplete   GraduationLevel = "elementary_incomplete"
	GraduationLevelElementaryComplete     GraduationLevel = "elementary_complete"
	GraduationLevelMiddleIncomplete       GraduationLevel = "middle_incomplete"
	GraduationLevelMiddleComplete         GraduationLevel = "middle_complete"
	GraduationLevelHighIncomplete         GraduationLevel = "high_incomplete"
	GraduationLevelHighComplete           GraduationLevel = "high_complete"
	GraduationLevelCollegeIncomplete      GraduationLevel = "college_incomplete"
	GraduationLevelCollegeComplete        GraduationLevel = "college_complete"
	GraduationLevelPostgraduateIncomplete GraduationLevel = "postgraduate_incomplete"
	GraduationLevelPostgraduateComplete   GraduationLevel = "postgraduate_complete"
	GraduationLevelMasterIncomplete       GraduationLevel = "master_incomplete"
	GraduationLevelMasterComplete         GraduationLevel = "master_complete"
	GraduationLevelDoctorateIncomplete    GraduationLevel = "doctorate_incomplete"
	GraduationLevelDoctorateComplete      GraduationLevel = "doctorate_complete"
)

func (e *GraduationLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GraduationLevel(s)
	case string:
		*e = GraduationLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for GraduationLevel: %T", src)
	}
	return nil
}

type NullGraduationLevel struct {
	GraduationLevel GraduationLevel `json:"graduation_level"`
	Valid           bool            `json:"valid"` // Valid is true if GraduationLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGraduationLevel) Scan(value interface{}) error {
	if value == nil {
		ns.GraduationLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GraduationLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGraduationLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GraduationLevel), nil
}

type LogAction string

const (
	LogActionCreate     LogAction = "create"
	LogActionUpdate     LogAction = "update"
	LogActionDelete     LogAction = "delete"
	LogActionRestore    LogAction = "restore"
	LogActionLogin      LogAction = "login"
	LogActionLogout     LogAction = "logout"
	LogActionView       LogAction = "view"
	LogActionExport     LogAction = "export"
	LogActionDeactivate LogAction = "deactivate"
	LogActionReactivate LogAction = "reactivate"
)

func (e *LogAction) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LogAction(s)
	case string:
		*e = LogAction(s)
	default:
		return fmt.Errorf("unsupported scan type for LogAction: %T", src)
	}
	return nil
}

type NullLogAction struct {
	LogAction LogAction `json:"log_action"`
	Valid     bool      `json:"valid"` // Valid is true if LogAction is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLogAction) Scan(value interface{}) error {
	if value == nil {
		ns.LogAction, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LogAction.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLogAction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LogAction), nil
}

type LoginResult string

const (
	LoginResultSuccess            LoginResult = "success"
	LoginResultInvalidCredentials LoginResult = "invalid_credentials"
	LoginResultAccountLocked      LoginResult = "account_locked"
	LoginResultAccountInactive    LoginResult = "account_inactive"
	LoginResultEmailUnverified    LoginResult = "email_unverified"
	LoginResultTokenExpired       LoginResult = "token_expired"
	LoginResultMfaRequired        LoginResult = "mfa_required"
	LoginResultMfaFailed          LoginResult = "mfa_failed"
)

func (e *LoginResult) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LoginResult(s)
	case string:
		*e = LoginResult(s)
	default:
		return fmt.Errorf("unsupported scan type for LoginResult: %T", src)
	}
	return nil
}

type NullLoginResult struct {
	LoginResult LoginResult `json:"login_result"`
	Valid       bool        `json:"valid"` // Valid is true if LoginResult is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLoginResult) Scan(value interface{}) error {
	if value == nil {
		ns.LoginResult, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LoginResult.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLoginResult) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LoginResult), nil
}

type LogoutReason string

const (
	LogoutReasonUserInitiated      LogoutReason = "user_initiated"
	LogoutReasonSessionExpired     LogoutReason = "session_expired"
	LogoutReasonForcedByAdmin      LogoutReason = "forced_by_admin"
	LogoutReasonPasswordChanged    LogoutReason = "password_changed"
	LogoutReasonAccountDeactivated LogoutReason = "account_deactivated"
	LogoutReasonSuspiciousActivity LogoutReason = "suspicious_activity"
)

func (e *LogoutReason) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LogoutReason(s)
	case string:
		*e = LogoutReason(s)
	default:
		return fmt.Errorf("unsupported scan type for LogoutReason: %T", src)
	}
	return nil
}

type NullLogoutReason struct {
	LogoutReason LogoutReason `json:"logout_reason"`
	Valid        bool         `json:"valid"` // Valid is true if LogoutReason is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLogoutReason) Scan(value interface{}) error {
	if value == nil {
		ns.LogoutReason, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LogoutReason.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLogoutReason) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LogoutReason), nil
}

type MaritalStatus string

const (
	MaritalStatusSingle    MaritalStatus = "single"
	MaritalStatusMarried   MaritalStatus = "married"
	MaritalStatusDivorced  MaritalStatus = "divorced"
	MaritalStatusWidowed   MaritalStatus = "widowed"
	MaritalStatusSeparated MaritalStatus = "separated"
)

func (e *MaritalStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MaritalStatus(s)
	case string:
		*e = MaritalStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MaritalStatus: %T", src)
	}
	return nil
}

type NullMaritalStatus struct {
	MaritalStatus MaritalStatus `json:"marital_status"`
	Valid         bool          `json:"valid"` // Valid is true if MaritalStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMaritalStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MaritalStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MaritalStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMaritalStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MaritalStatus), nil
}

type ModulePackage string

const (
	ModulePackageInternal  ModulePackage = "internal"
	ModulePackageStarter   ModulePackage = "starter"
	ModulePackageBasic     ModulePackage = "basic"
	ModulePackageEssential ModulePackage = "essential"
	ModulePackagePremium   ModulePackage = "premium"
	ModulePackageTrial     ModulePackage = "trial"
)

func (e *ModulePackage) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ModulePackage(s)
	case string:
		*e = ModulePackage(s)
	default:
		return fmt.Errorf("unsupported scan type for ModulePackage: %T", src)
	}
	return nil
}

type NullModulePackage struct {
	ModulePackage ModulePackage `json:"module_package"`
	Valid         bool          `json:"valid"` // Valid is true if ModulePackage is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullModulePackage) Scan(value interface{}) error {
	if value == nil {
		ns.ModulePackage, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ModulePackage.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullModulePackage) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ModulePackage), nil
}

type NotificationLevel string

const (
	NotificationLevelInfo    NotificationLevel = "info"
	NotificationLevelSuccess NotificationLevel = "success"
	NotificationLevelWarning NotificationLevel = "warning"
	NotificationLevelError   NotificationLevel = "error"
	NotificationLevelAlert   NotificationLevel = "alert"
)

func (e *NotificationLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationLevel(s)
	case string:
		*e = NotificationLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationLevel: %T", src)
	}
	return nil
}

type NullNotificationLevel struct {
	NotificationLevel NotificationLevel `json:"notification_level"`
	Valid             bool              `json:"valid"` // Valid is true if NotificationLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationLevel) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationLevel), nil
}

type PaymentMethod string

const (
	PaymentMethodCreditCard PaymentMethod = "credit_card"
	PaymentMethodDebitCard  PaymentMethod = "debit_card"
	PaymentMethodPix        PaymentMethod = "pix"
	PaymentMethodCash       PaymentMethod = "cash"
	PaymentMethodCheck      PaymentMethod = "check"
	PaymentMethodBankSlip   PaymentMethod = "bank_slip"
	PaymentMethodTransfer   PaymentMethod = "transfer"
)

func (e *PaymentMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentMethod(s)
	case string:
		*e = PaymentMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentMethod: %T", src)
	}
	return nil
}

type NullPaymentMethod struct {
	PaymentMethod PaymentMethod `json:"payment_method"`
	Valid         bool          `json:"valid"` // Valid is true if PaymentMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentMethod) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentMethod), nil
}

type PersonKind string

const (
	PersonKindClient             PersonKind = "client"
	PersonKindEmployee           PersonKind = "employee"
	PersonKindOutsourcedEmployee PersonKind = "outsourced_employee"
	PersonKindSupplier           PersonKind = "supplier"
	PersonKindGuardian           PersonKind = "guardian"
	PersonKindResponsible        PersonKind = "responsible"
)

func (e *PersonKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PersonKind(s)
	case string:
		*e = PersonKind(s)
	default:
		return fmt.Errorf("unsupported scan type for PersonKind: %T", src)
	}
	return nil
}

type NullPersonKind struct {
	PersonKind PersonKind `json:"person_kind"`
	Valid      bool       `json:"valid"` // Valid is true if PersonKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPersonKind) Scan(value interface{}) error {
	if value == nil {
		ns.PersonKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PersonKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPersonKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PersonKind), nil
}

type PetKind string

const (
	PetKindDog     PetKind = "dog"
	PetKindCat     PetKind = "cat"
	PetKindBird    PetKind = "bird"
	PetKindFish    PetKind = "fish"
	PetKindReptile PetKind = "reptile"
	PetKindRodent  PetKind = "rodent"
	PetKindRabbit  PetKind = "rabbit"
	PetKindOther   PetKind = "other"
)

func (e *PetKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PetKind(s)
	case string:
		*e = PetKind(s)
	default:
		return fmt.Errorf("unsupported scan type for PetKind: %T", src)
	}
	return nil
}

type NullPetKind struct {
	PetKind PetKind `json:"pet_kind"`
	Valid   bool    `json:"valid"` // Valid is true if PetKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPetKind) Scan(value interface{}) error {
	if value == nil {
		ns.PetKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PetKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPetKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PetKind), nil
}

type PetSize string

const (
	PetSizeSmall  PetSize = "small"
	PetSizeMedium PetSize = "medium"
	PetSizeLarge  PetSize = "large"
	PetSizeGiant  PetSize = "giant"
)

func (e *PetSize) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PetSize(s)
	case string:
		*e = PetSize(s)
	default:
		return fmt.Errorf("unsupported scan type for PetSize: %T", src)
	}
	return nil
}

type NullPetSize struct {
	PetSize PetSize `json:"pet_size"`
	Valid   bool    `json:"valid"` // Valid is true if PetSize is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPetSize) Scan(value interface{}) error {
	if value == nil {
		ns.PetSize, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PetSize.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPetSize) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PetSize), nil
}

type PetTemperament string

const (
	PetTemperamentCalm       PetTemperament = "calm"
	PetTemperamentNervous    PetTemperament = "nervous"
	PetTemperamentAggressive PetTemperament = "aggressive"
	PetTemperamentPlayful    PetTemperament = "playful"
	PetTemperamentLoving     PetTemperament = "loving"
)

func (e *PetTemperament) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PetTemperament(s)
	case string:
		*e = PetTemperament(s)
	default:
		return fmt.Errorf("unsupported scan type for PetTemperament: %T", src)
	}
	return nil
}

type NullPetTemperament struct {
	PetTemperament PetTemperament `json:"pet_temperament"`
	Valid          bool           `json:"valid"` // Valid is true if PetTemperament is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPetTemperament) Scan(value interface{}) error {
	if value == nil {
		ns.PetTemperament, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PetTemperament.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPetTemperament) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PetTemperament), nil
}

type PixKeyKind string

const (
	PixKeyKindCpf    PixKeyKind = "cpf"
	PixKeyKindCnpj   PixKeyKind = "cnpj"
	PixKeyKindEmail  PixKeyKind = "email"
	PixKeyKindPhone  PixKeyKind = "phone"
	PixKeyKindRandom PixKeyKind = "random"
)

func (e *PixKeyKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PixKeyKind(s)
	case string:
		*e = PixKeyKind(s)
	default:
		return fmt.Errorf("unsupported scan type for PixKeyKind: %T", src)
	}
	return nil
}

type NullPixKeyKind struct {
	PixKeyKind PixKeyKind `json:"pix_key_kind"`
	Valid      bool       `json:"valid"` // Valid is true if PixKeyKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPixKeyKind) Scan(value interface{}) error {
	if value == nil {
		ns.PixKeyKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PixKeyKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPixKeyKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PixKeyKind), nil
}

type ProductKind string

const (
	ProductKindService       ProductKind = "service"
	ProductKindCustomer      ProductKind = "customer"
	ProductKindInternalUsage ProductKind = "internal_usage"
)

func (e *ProductKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProductKind(s)
	case string:
		*e = ProductKind(s)
	default:
		return fmt.Errorf("unsupported scan type for ProductKind: %T", src)
	}
	return nil
}

type NullProductKind struct {
	ProductKind ProductKind `json:"product_kind"`
	Valid       bool        `json:"valid"` // Valid is true if ProductKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProductKind) Scan(value interface{}) error {
	if value == nil {
		ns.ProductKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProductKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProductKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProductKind), nil
}

type ScheduleStatus string

const (
	ScheduleStatusWaiting    ScheduleStatus = "waiting"
	ScheduleStatusConfirmed  ScheduleStatus = "confirmed"
	ScheduleStatusCanceled   ScheduleStatus = "canceled"
	ScheduleStatusInProgress ScheduleStatus = "in_progress"
	ScheduleStatusFinished   ScheduleStatus = "finished"
	ScheduleStatusDelivered  ScheduleStatus = "delivered"
)

func (e *ScheduleStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ScheduleStatus(s)
	case string:
		*e = ScheduleStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ScheduleStatus: %T", src)
	}
	return nil
}

type NullScheduleStatus struct {
	ScheduleStatus ScheduleStatus `json:"schedule_status"`
	Valid          bool           `json:"valid"` // Valid is true if ScheduleStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullScheduleStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ScheduleStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ScheduleStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullScheduleStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ScheduleStatus), nil
}

type UserKind string

const (
	UserKindOwner              UserKind = "owner"
	UserKindEmployee           UserKind = "employee"
	UserKindClient             UserKind = "client"
	UserKindSupplier           UserKind = "supplier"
	UserKindOutsourcedEmployee UserKind = "outsourced_employee"
)

func (e *UserKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserKind(s)
	case string:
		*e = UserKind(s)
	default:
		return fmt.Errorf("unsupported scan type for UserKind: %T", src)
	}
	return nil
}

type NullUserKind struct {
	UserKind UserKind `json:"user_kind"`
	Valid    bool     `json:"valid"` // Valid is true if UserKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserKind) Scan(value interface{}) error {
	if value == nil {
		ns.UserKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserKind), nil
}

type UserRoleType string

const (
	UserRoleTypeRoot     UserRoleType = "root"
	UserRoleTypeInternal UserRoleType = "internal"
	UserRoleTypeAdmin    UserRoleType = "admin"
	UserRoleTypeSystem   UserRoleType = "system"
	UserRoleTypeCommon   UserRoleType = "common"
	UserRoleTypeFree     UserRoleType = "free"
)

func (e *UserRoleType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRoleType(s)
	case string:
		*e = UserRoleType(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRoleType: %T", src)
	}
	return nil
}

type NullUserRoleType struct {
	UserRoleType UserRoleType `json:"user_role_type"`
	Valid        bool         `json:"valid"` // Valid is true if UserRoleType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRoleType) Scan(value interface{}) error {
	if value == nil {
		ns.UserRoleType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRoleType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRoleType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRoleType), nil
}

type WeekDay string

const (
	WeekDaySunday    WeekDay = "sunday"
	WeekDayMonday    WeekDay = "monday"
	WeekDayTuesday   WeekDay = "tuesday"
	WeekDayWednesday WeekDay = "wednesday"
	WeekDayThursday  WeekDay = "thursday"
	WeekDayFriday    WeekDay = "friday"
	WeekDaySaturday  WeekDay = "saturday"
)

func (e *WeekDay) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WeekDay(s)
	case string:
		*e = WeekDay(s)
	default:
		return fmt.Errorf("unsupported scan type for WeekDay: %T", src)
	}
	return nil
}

type NullWeekDay struct {
	WeekDay WeekDay `json:"week_day"`
	Valid   bool    `json:"valid"` // Valid is true if WeekDay is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWeekDay) Scan(value interface{}) error {
	if value == nil {
		ns.WeekDay, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WeekDay.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWeekDay) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WeekDay), nil
}

type Address struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	ZipCode    string             `db:"zip_code" json:"zip_code"`
	Street     string             `db:"street" json:"street"`
	Number     string             `db:"number" json:"number"`
	Complement pgtype.Text        `db:"complement" json:"complement"`
	District   string             `db:"district" json:"district"`
	City       string             `db:"city" json:"city"`
	State      string             `db:"state" json:"state"`
	Country    string             `db:"country" json:"country"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type AdminSystemConversation struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	CompanyID    pgtype.UUID        `db:"company_id" json:"company_id"`
	AdminUserID  pgtype.UUID        `db:"admin_user_id" json:"admin_user_id"`
	SystemUserID pgtype.UUID        `db:"system_user_id" json:"system_user_id"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type AdminSystemMessage struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	ConversationID pgtype.UUID        `db:"conversation_id" json:"conversation_id"`
	CompanyID      pgtype.UUID        `db:"company_id" json:"company_id"`
	SenderUserID   pgtype.UUID        `db:"sender_user_id" json:"sender_user_id"`
	Body           string             `db:"body" json:"body"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type AuditLog struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Action      LogAction          `db:"action" json:"action"`
	EntityTable string             `db:"entity_table" json:"entity_table"`
	EntityID    pgtype.UUID        `db:"entity_id" json:"entity_id"`
	CompanyID   pgtype.UUID        `db:"company_id" json:"company_id"`
	OldData     []byte             `db:"old_data" json:"old_data"`
	NewData     []byte             `db:"new_data" json:"new_data"`
	ChangedAt   pgtype.Timestamptz `db:"changed_at" json:"changed_at"`
	ChangedBy   pgtype.UUID        `db:"changed_by" json:"changed_by"`
	IpAddress   *netip.Addr        `db:"ip_address" json:"ip_address"`
	UserAgent   pgtype.Text        `db:"user_agent" json:"user_agent"`
}

type AuthLog struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	UserID     pgtype.UUID        `db:"user_id" json:"user_id"`
	Action     LogAction          `db:"action" json:"action"`
	CompanyID  pgtype.UUID        `db:"company_id" json:"company_id"`
	SessionID  pgtype.UUID        `db:"session_id" json:"session_id"`
	IpAddress  netip.Addr         `db:"ip_address" json:"ip_address"`
	UserAgent  string             `db:"user_agent" json:"user_agent"`
	Result     NullLoginResult    `db:"result" json:"result"`
	Detail     pgtype.Text        `db:"detail" json:"detail"`
	OccurredAt pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
}

type Client struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	PersonID      pgtype.UUID        `db:"person_id" json:"person_id"`
	ClientSince   pgtype.Date        `db:"client_since" json:"client_since"`
	RecommendedBy pgtype.UUID        `db:"recommended_by" json:"recommended_by"`
	Notes         pgtype.Text        `db:"notes" json:"notes"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type ClientPlan struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	ClientID  pgtype.UUID        `db:"client_id" json:"client_id"`
	PlanID    pgtype.UUID        `db:"plan_id" json:"plan_id"`
	StartedAt pgtype.Timestamptz `db:"started_at" json:"started_at"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	PricePaid pgtype.Numeric     `db:"price_paid" json:"price_paid"`
	IsActive  bool               `db:"is_active" json:"is_active"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ClientServicePlan struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	ClientID      pgtype.UUID        `db:"client_id" json:"client_id"`
	ServicePlanID pgtype.UUID        `db:"service_plan_id" json:"service_plan_id"`
	StartedAt     pgtype.Timestamptz `db:"started_at" json:"started_at"`
	ExpiresAt     pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	PricePaid     pgtype.Numeric     `db:"price_paid" json:"price_paid"`
	IsActive      bool               `db:"is_active" json:"is_active"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Company struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	Slug           string             `db:"slug" json:"slug"`
	Name           string             `db:"name" json:"name"`
	FantasyName    string             `db:"fantasy_name" json:"fantasy_name"`
	Cnpj           string             `db:"cnpj" json:"cnpj"`
	FoundationDate pgtype.Date        `db:"foundation_date" json:"foundation_date"`
	LogoUrl        pgtype.Text        `db:"logo_url" json:"logo_url"`
	ResponsibleID  pgtype.UUID        `db:"responsible_id" json:"responsible_id"`
	ActivePackage  ModulePackage      `db:"active_package" json:"active_package"`
	IsActive       bool               `db:"is_active" json:"is_active"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type CompanyAddress struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	CompanyID pgtype.UUID        `db:"company_id" json:"company_id"`
	AddressID pgtype.UUID        `db:"address_id" json:"address_id"`
	IsMain    bool               `db:"is_main" json:"is_main"`
	Label     pgtype.Text        `db:"label" json:"label"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type CompanyBusinessCost struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	CompanyID      pgtype.UUID        `db:"company_id" json:"company_id"`
	InvoiceNumber  pgtype.Text        `db:"invoice_number" json:"invoice_number"`
	InvoiceUrl     pgtype.Text        `db:"invoice_url" json:"invoice_url"`
	Description    string             `db:"description" json:"description"`
	TotalCost      pgtype.Numeric     `db:"total_cost" json:"total_cost"`
	ReferenceMonth pgtype.Date        `db:"reference_month" json:"reference_month"`
	Comments       pgtype.Text        `db:"comments" json:"comments"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type CompanyClient struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	CompanyID pgtype.UUID        `db:"company_id" json:"company_id"`
	ClientID  pgtype.UUID        `db:"client_id" json:"client_id"`
	IsActive  bool               `db:"is_active" json:"is_active"`
	JoinedAt  pgtype.Timestamptz `db:"joined_at" json:"joined_at"`
	LeftAt    pgtype.Timestamptz `db:"left_at" json:"left_at"`
}

type CompanyEmployee struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	CompanyID pgtype.UUID        `db:"company_id" json:"company_id"`
	PersonID  pgtype.UUID        `db:"person_id" json:"person_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type CompanyEmployeeCost struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	CompanyEmployeeID pgtype.UUID        `db:"company_employee_id" json:"company_employee_id"`
	Costs             pgtype.Numeric     `db:"costs" json:"costs"`
	ReferenceMonth    pgtype.Date        `db:"reference_month" json:"reference_month"`
	Comments          pgtype.Text        `db:"comments" json:"comments"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type CompanyFinance struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	CompanyID pgtype.UUID        `db:"company_id" json:"company_id"`
	FinanceID pgtype.UUID        `db:"finance_id" json:"finance_id"`
	IsPrimary bool               `db:"is_primary" json:"is_primary"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type CompanyModule struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	CompanyID pgtype.UUID        `db:"company_id" json:"company_id"`
	ModuleID  pgtype.UUID        `db:"module_id" json:"module_id"`
	IsActive  bool               `db:"is_active" json:"is_active"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type CompanyPerson struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	CompanyID pgtype.UUID        `db:"company_id" json:"company_id"`
	PersonID  pgtype.UUID        `db:"person_id" json:"person_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type CompanyProduct struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	CompanyID    pgtype.UUID        `db:"company_id" json:"company_id"`
	ProductID    pgtype.UUID        `db:"product_id" json:"product_id"`
	Kind         ProductKind        `db:"kind" json:"kind"`
	HasStock     bool               `db:"has_stock" json:"has_stock"`
	ForSale      bool               `db:"for_sale" json:"for_sale"`
	CostPerUnit  pgtype.Numeric     `db:"cost_per_unit" json:"cost_per_unit"`
	ProfitMargin pgtype.Numeric     `db:"profit_margin" json:"profit_margin"`
	SalePrice    pgtype.Numeric     `db:"sale_price" json:"sale_price"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type CompanyService struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	CompanyID pgtype.UUID        `db:"company_id" json:"company_id"`
	ServiceID pgtype.UUID        `db:"service_id" json:"service_id"`
	IsActive  bool               `db:"is_active" json:"is_active"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type CompanyServicePlan struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	CompanyID     pgtype.UUID        `db:"company_id" json:"company_id"`
	ServicePlanID pgtype.UUID        `db:"service_plan_id" json:"service_plan_id"`
	IsActive      bool               `db:"is_active" json:"is_active"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type CompanySubscription struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	CompanyID  pgtype.UUID        `db:"company_id" json:"company_id"`
	PlanID     pgtype.UUID        `db:"plan_id" json:"plan_id"`
	StartedAt  pgtype.Timestamptz `db:"started_at" json:"started_at"`
	ExpiresAt  pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CanceledAt pgtype.Timestamptz `db:"canceled_at" json:"canceled_at"`
	IsActive   bool               `db:"is_active" json:"is_active"`
	PricePaid  pgtype.Numeric     `db:"price_paid" json:"price_paid"`
	Notes      pgtype.Text        `db:"notes" json:"notes"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type CompanySystemConfig struct {
	ID                    pgtype.UUID        `db:"id" json:"id"`
	CompanyID             pgtype.UUID        `db:"company_id" json:"company_id"`
	ScheduleInitTime      pgtype.Time        `db:"schedule_init_time" json:"schedule_init_time"`
	SchedulePauseInitTime pgtype.Time        `db:"schedule_pause_init_time" json:"schedule_pause_init_time"`
	SchedulePauseEndTime  pgtype.Time        `db:"schedule_pause_end_time" json:"schedule_pause_end_time"`
	ScheduleEndTime       pgtype.Time        `db:"schedule_end_time" json:"schedule_end_time"`
	MinSchedulesPerDay    int16              `db:"min_schedules_per_day" json:"min_schedules_per_day"`
	MaxSchedulesPerDay    int16              `db:"max_schedules_per_day" json:"max_schedules_per_day"`
	ScheduleDays          []WeekDay          `db:"schedule_days" json:"schedule_days"`
	DynamicCages          bool               `db:"dynamic_cages" json:"dynamic_cages"`
	TotalSmallCages       int16              `db:"total_small_cages" json:"total_small_cages"`
	TotalMediumCages      int16              `db:"total_medium_cages" json:"total_medium_cages"`
	TotalLargeCages       int16              `db:"total_large_cages" json:"total_large_cages"`
	TotalGiantCages       int16              `db:"total_giant_cages" json:"total_giant_cages"`
	WhatsappNotifications bool               `db:"whatsapp_notifications" json:"whatsapp_notifications"`
	WhatsappConversation  bool               `db:"whatsapp_conversation" json:"whatsapp_conversation"`
	WhatsappBusinessPhone pgtype.Text        `db:"whatsapp_business_phone" json:"whatsapp_business_phone"`
	CreatedAt             pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type CompanyUser struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	CompanyID pgtype.UUID        `db:"company_id" json:"company_id"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	Kind      UserKind           `db:"kind" json:"kind"`
	IsOwner   bool               `db:"is_owner" json:"is_owner"`
	IsActive  bool               `db:"is_active" json:"is_active"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type EmailVerificationToken struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	UserID            pgtype.UUID        `db:"user_id" json:"user_id"`
	TokenHash         string             `db:"token_hash" json:"token_hash"`
	Email             string             `db:"email" json:"email"`
	ExpiresAt         pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	UsedAt            pgtype.Timestamptz `db:"used_at" json:"used_at"`
	RevokedAt         pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	RequestIp         *netip.Addr        `db:"request_ip" json:"request_ip"`
	RequestUserAgent  pgtype.Text        `db:"request_user_agent" json:"request_user_agent"`
	ConsumedIp        *netip.Addr        `db:"consumed_ip" json:"consumed_ip"`
	ConsumedUserAgent pgtype.Text        `db:"consumed_user_agent" json:"consumed_user_agent"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type EmployeeBenefit struct {
	ID                    pgtype.UUID        `db:"id" json:"id"`
	CompanyEmployeeID     pgtype.UUID        `db:"company_employee_id" json:"company_employee_id"`
	MealTicket            bool               `db:"meal_ticket" json:"meal_ticket"`
	MealTicketValue       pgtype.Numeric     `db:"meal_ticket_value" json:"meal_ticket_value"`
	TransportVoucher      bool               `db:"transport_voucher" json:"transport_voucher"`
	TransportVoucherQty   int16              `db:"transport_voucher_qty" json:"transport_voucher_qty"`
	TransportVoucherValue pgtype.Numeric     `db:"transport_voucher_value" json:"transport_voucher_value"`
	ValidFrom             pgtype.Date        `db:"valid_from" json:"valid_from"`
	ValidUntil            pgtype.Date        `db:"valid_until" json:"valid_until"`
	CreatedAt             pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type EmployeeDocument struct {
	ID                    pgtype.UUID        `db:"id" json:"id"`
	PersonID              pgtype.UUID        `db:"person_id" json:"person_id"`
	Rg                    string             `db:"rg" json:"rg"`
	IssuingBody           string             `db:"issuing_body" json:"issuing_body"`
	IssuingDate           pgtype.Date        `db:"issuing_date" json:"issuing_date"`
	Ctps                  string             `db:"ctps" json:"ctps"`
	CtpsSeries            string             `db:"ctps_series" json:"ctps_series"`
	CtpsState             string             `db:"ctps_state" json:"ctps_state"`
	Pis                   string             `db:"pis" json:"pis"`
	VoterRegistration     pgtype.Text        `db:"voter_registration" json:"voter_registration"`
	VoteZone              pgtype.Text        `db:"vote_zone" json:"vote_zone"`
	VoteSection           pgtype.Text        `db:"vote_section" json:"vote_section"`
	MilitaryCertificate   pgtype.Text        `db:"military_certificate" json:"military_certificate"`
	MilitarySeries        pgtype.Text        `db:"military_series" json:"military_series"`
	MilitaryCategory      pgtype.Text        `db:"military_category" json:"military_category"`
	HasSpecialNeeds       pgtype.Bool        `db:"has_special_needs" json:"has_special_needs"`
	HasChildren           bool               `db:"has_children" json:"has_children"`
	ChildrenQty           pgtype.Int2        `db:"children_qty" json:"children_qty"`
	HasChildrenUnder18    pgtype.Bool        `db:"has_children_under_18" json:"has_children_under_18"`
	HasFamilySpecialNeeds pgtype.Bool        `db:"has_family_special_needs" json:"has_family_special_needs"`
	Graduation            GraduationLevel    `db:"graduation" json:"graduation"`
	HasCnh                pgtype.Bool        `db:"has_cnh" json:"has_cnh"`
	CnhType               pgtype.Text        `db:"cnh_type" json:"cnh_type"`
	CnhNumber             pgtype.Text        `db:"cnh_number" json:"cnh_number"`
	CnhExpirationDate     pgtype.Date        `db:"cnh_expiration_date" json:"cnh_expiration_date"`
	CreatedAt             pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Employment struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	CompanyEmployeeID pgtype.UUID        `db:"company_employee_id" json:"company_employee_id"`
	Role              string             `db:"role" json:"role"`
	AdmissionDate     pgtype.Date        `db:"admission_date" json:"admission_date"`
	ResignationDate   pgtype.Date        `db:"resignation_date" json:"resignation_date"`
	Salary            pgtype.Numeric     `db:"salary" json:"salary"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type Finance struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	BankName         string             `db:"bank_name" json:"bank_name"`
	BankCode         pgtype.Text        `db:"bank_code" json:"bank_code"`
	BankBranch       string             `db:"bank_branch" json:"bank_branch"`
	BankAccount      string             `db:"bank_account" json:"bank_account"`
	BankAccountDigit string             `db:"bank_account_digit" json:"bank_account_digit"`
	BankAccountType  BankAccountKind    `db:"bank_account_type" json:"bank_account_type"`
	HasPix           bool               `db:"has_pix" json:"has_pix"`
	PixKey           pgtype.Text        `db:"pix_key" json:"pix_key"`
	PixKeyType       NullPixKeyKind     `db:"pix_key_type" json:"pix_key_type"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Language struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	Code       string             `db:"code" json:"code"`
	Name       string             `db:"name" json:"name"`
	NativeName string             `db:"native_name" json:"native_name"`
	IsActive   bool               `db:"is_active" json:"is_active"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type LoginHistory struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	UserID        pgtype.UUID        `db:"user_id" json:"user_id"`
	IpAddress     netip.Addr         `db:"ip_address" json:"ip_address"`
	UserAgent     string             `db:"user_agent" json:"user_agent"`
	Result        LoginResult        `db:"result" json:"result"`
	FailureDetail pgtype.Text        `db:"failure_detail" json:"failure_detail"`
	AttemptedAt   pgtype.Timestamptz `db:"attempted_at" json:"attempted_at"`
}

type Module struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Code        string             `db:"code" json:"code"`
	Name        string             `db:"name" json:"name"`
	Description string             `db:"description" json:"description"`
	MinPackage  ModulePackage      `db:"min_package" json:"min_package"`
	IsActive    bool               `db:"is_active" json:"is_active"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type ModulePermission struct {
	ModuleID     pgtype.UUID `db:"module_id" json:"module_id"`
	PermissionID pgtype.UUID `db:"permission_id" json:"permission_id"`
}

type Notification struct {
	ID                      pgtype.UUID        `db:"id" json:"id"`
	CompanyID               pgtype.UUID        `db:"company_id" json:"company_id"`
	Title                   string             `db:"title" json:"title"`
	Summary                 string             `db:"summary" json:"summary"`
	Content                 string             `db:"content" json:"content"`
	ImageUrl                pgtype.Text        `db:"image_url" json:"image_url"`
	Level                   NotificationLevel  `db:"level" json:"level"`
	SendToWhatsapp          bool               `db:"send_to_whatsapp" json:"send_to_whatsapp"`
	SendToTelegram          bool               `db:"send_to_telegram" json:"send_to_telegram"`
	SendToEmail             bool               `db:"send_to_email" json:"send_to_email"`
	SendToSms               bool               `db:"send_to_sms" json:"send_to_sms"`
	SendToPush              bool               `db:"send_to_push" json:"send_to_push"`
	SendToInAppNotification bool               `db:"send_to_in_app_notification" json:"send_to_in_app_notification"`
	CreatedBy               pgtype.UUID        `db:"created_by" json:"created_by"`
	CreatedAt               pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt               pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type NotificationReceiver struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	NotificationID pgtype.UUID        `db:"notification_id" json:"notification_id"`
	UserID         pgtype.UUID        `db:"user_id" json:"user_id"`
	ReadAt         pgtype.Timestamptz `db:"read_at" json:"read_at"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type PasswordRecoveryToken struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	UserID            pgtype.UUID        `db:"user_id" json:"user_id"`
	TokenHash         string             `db:"token_hash" json:"token_hash"`
	RequestedEmail    string             `db:"requested_email" json:"requested_email"`
	ExpiresAt         pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	UsedAt            pgtype.Timestamptz `db:"used_at" json:"used_at"`
	RevokedAt         pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	RequestIp         *netip.Addr        `db:"request_ip" json:"request_ip"`
	RequestUserAgent  pgtype.Text        `db:"request_user_agent" json:"request_user_agent"`
	ConsumedIp        *netip.Addr        `db:"consumed_ip" json:"consumed_ip"`
	ConsumedUserAgent pgtype.Text        `db:"consumed_user_agent" json:"consumed_user_agent"`
	TriggeredByUserID pgtype.UUID        `db:"triggered_by_user_id" json:"triggered_by_user_id"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type PeopleAddress struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	PersonID  pgtype.UUID        `db:"person_id" json:"person_id"`
	AddressID pgtype.UUID        `db:"address_id" json:"address_id"`
	IsMain    bool               `db:"is_main" json:"is_main"`
	Label     pgtype.Text        `db:"label" json:"label"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type PeopleContact struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	PersonID         pgtype.UUID        `db:"person_id" json:"person_id"`
	Email            string             `db:"email" json:"email"`
	Phone            pgtype.Text        `db:"phone" json:"phone"`
	Cellphone        string             `db:"cellphone" json:"cellphone"`
	HasWhatsapp      bool               `db:"has_whatsapp" json:"has_whatsapp"`
	InstagramUser    pgtype.Text        `db:"instagram_user" json:"instagram_user"`
	EmergencyContact pgtype.Text        `db:"emergency_contact" json:"emergency_contact"`
	EmergencyPhone   pgtype.Text        `db:"emergency_phone" json:"emergency_phone"`
	IsPrimary        bool               `db:"is_primary" json:"is_primary"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type PeopleFinance struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	PersonID  pgtype.UUID        `db:"person_id" json:"person_id"`
	FinanceID pgtype.UUID        `db:"finance_id" json:"finance_id"`
	IsPrimary bool               `db:"is_primary" json:"is_primary"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type PeopleIdentification struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	PersonID       pgtype.UUID        `db:"person_id" json:"person_id"`
	FullName       string             `db:"full_name" json:"full_name"`
	ShortName      string             `db:"short_name" json:"short_name"`
	GenderIdentity GenderIdentity     `db:"gender_identity" json:"gender_identity"`
	MaritalStatus  MaritalStatus      `db:"marital_status" json:"marital_status"`
	ImageUrl       pgtype.Text        `db:"image_url" json:"image_url"`
	BirthDate      pgtype.Date        `db:"birth_date" json:"birth_date"`
	Cpf            string             `db:"cpf" json:"cpf"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Permission struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	Code         string             `db:"code" json:"code"`
	Description  pgtype.Text        `db:"description" json:"description"`
	DefaultRoles []UserRoleType     `db:"default_roles" json:"default_roles"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Person struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	Kind          PersonKind         `db:"kind" json:"kind"`
	IsActive      bool               `db:"is_active" json:"is_active"`
	HasSystemUser bool               `db:"has_system_user" json:"has_system_user"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Pet struct {
	ID                      pgtype.UUID        `db:"id" json:"id"`
	Name                    string             `db:"name" json:"name"`
	Race                    string             `db:"race" json:"race"`
	Color                   string             `db:"color" json:"color"`
	Sex                     string             `db:"sex" json:"sex"`
	Size                    PetSize            `db:"size" json:"size"`
	Kind                    PetKind            `db:"kind" json:"kind"`
	Temperament             PetTemperament     `db:"temperament" json:"temperament"`
	ImageUrl                pgtype.Text        `db:"image_url" json:"image_url"`
	BirthDate               pgtype.Date        `db:"birth_date" json:"birth_date"`
	OwnerID                 pgtype.UUID        `db:"owner_id" json:"owner_id"`
	IsActive                bool               `db:"is_active" json:"is_active"`
	IsDeceased              bool               `db:"is_deceased" json:"is_deceased"`
	IsVaccinated            bool               `db:"is_vaccinated" json:"is_vaccinated"`
	IsNeutered              bool               `db:"is_neutered" json:"is_neutered"`
	IsMicrochipped          bool               `db:"is_microchipped" json:"is_microchipped"`
	MicrochipNumber         pgtype.Text        `db:"microchip_number" json:"microchip_number"`
	MicrochipExpirationDate pgtype.Date        `db:"microchip_expiration_date" json:"microchip_expiration_date"`
	Notes                   pgtype.Text        `db:"notes" json:"notes"`
	CreatedAt               pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt               pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type PetGuardian struct {
	PetID      pgtype.UUID        `db:"pet_id" json:"pet_id"`
	GuardianID pgtype.UUID        `db:"guardian_id" json:"guardian_id"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Plan struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	PlanTypeID       pgtype.UUID        `db:"plan_type_id" json:"plan_type_id"`
	Name             string             `db:"name" json:"name"`
	Description      string             `db:"description" json:"description"`
	Package          ModulePackage      `db:"package" json:"package"`
	Price            pgtype.Numeric     `db:"price" json:"price"`
	BillingCycleDays int32              `db:"billing_cycle_days" json:"billing_cycle_days"`
	MaxUsers         pgtype.Int4        `db:"max_users" json:"max_users"`
	IsActive         bool               `db:"is_active" json:"is_active"`
	ImageUrl         pgtype.Text        `db:"image_url" json:"image_url"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type PlanModule struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	PlanID    pgtype.UUID        `db:"plan_id" json:"plan_id"`
	ModuleID  pgtype.UUID        `db:"module_id" json:"module_id"`
	IsActive  bool               `db:"is_active" json:"is_active"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type PlanPermission struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	PlanID       pgtype.UUID        `db:"plan_id" json:"plan_id"`
	PermissionID pgtype.UUID        `db:"permission_id" json:"permission_id"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type PlanType struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Name        string             `db:"name" json:"name"`
	Description pgtype.Text        `db:"description" json:"description"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type Product struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	Name           string             `db:"name" json:"name"`
	BatchNumber    pgtype.Text        `db:"batch_number" json:"batch_number"`
	Description    pgtype.Text        `db:"description" json:"description"`
	ImageUrl       pgtype.Text        `db:"image_url" json:"image_url"`
	ExpirationDate pgtype.Date        `db:"expiration_date" json:"expiration_date"`
	Quantity       int32              `db:"quantity" json:"quantity"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type Schedule struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	CompanyID    pgtype.UUID        `db:"company_id" json:"company_id"`
	ClientID     pgtype.UUID        `db:"client_id" json:"client_id"`
	PetID        pgtype.UUID        `db:"pet_id" json:"pet_id"`
	ScheduledAt  pgtype.Timestamptz `db:"scheduled_at" json:"scheduled_at"`
	EstimatedEnd pgtype.Timestamptz `db:"estimated_end" json:"estimated_end"`
	Notes        pgtype.Text        `db:"notes" json:"notes"`
	CreatedBy    pgtype.UUID        `db:"created_by" json:"created_by"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type ScheduleCheckin struct {
	ID                      pgtype.UUID        `db:"id" json:"id"`
	ScheduleID              pgtype.UUID        `db:"schedule_id" json:"schedule_id"`
	CheckedInAt             pgtype.Timestamptz `db:"checked_in_at" json:"checked_in_at"`
	CheckInPersonID         pgtype.UUID        `db:"check_in_person_id" json:"check_in_person_id"`
	CheckInNotes            pgtype.Text        `db:"check_in_notes" json:"check_in_notes"`
	CheckInPhotoUrl         pgtype.Text        `db:"check_in_photo_url" json:"check_in_photo_url"`
	CheckedOutAt            pgtype.Timestamptz `db:"checked_out_at" json:"checked_out_at"`
	CheckOutPersonID        pgtype.UUID        `db:"check_out_person_id" json:"check_out_person_id"`
	CheckOutNotes           pgtype.Text        `db:"check_out_notes" json:"check_out_notes"`
	CheckOutPhotoUrl        pgtype.Text        `db:"check_out_photo_url" json:"check_out_photo_url"`
	ServiceExecutorPersonID pgtype.UUID        `db:"service_executor_person_id" json:"service_executor_person_id"`
	CreatedAt               pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type SchedulePayment struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	ScheduleID         pgtype.UUID        `db:"schedule_id" json:"schedule_id"`
	PaymentMethodOne   PaymentMethod      `db:"payment_method_one" json:"payment_method_one"`
	PaymentMethodTwo   NullPaymentMethod  `db:"payment_method_two" json:"payment_method_two"`
	PaymentMethodThree NullPaymentMethod  `db:"payment_method_three" json:"payment_method_three"`
	PaymentDate        pgtype.Timestamptz `db:"payment_date" json:"payment_date"`
	GrossValue         pgtype.Numeric     `db:"gross_value" json:"gross_value"`
	DiscountValue      pgtype.Numeric     `db:"discount_value" json:"discount_value"`
	NetValue           pgtype.Numeric     `db:"net_value" json:"net_value"`
	AmountPaid         pgtype.Numeric     `db:"amount_paid" json:"amount_paid"`
	AmountRemaining    pgtype.Numeric     `db:"amount_remaining" json:"amount_remaining"`
	Notes              pgtype.Text        `db:"notes" json:"notes"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ScheduleService struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	ScheduleID pgtype.UUID        `db:"schedule_id" json:"schedule_id"`
	ServiceID  pgtype.UUID        `db:"service_id" json:"service_id"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type ScheduleStatusHistory struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	ScheduleID pgtype.UUID        `db:"schedule_id" json:"schedule_id"`
	Status     ScheduleStatus     `db:"status" json:"status"`
	ChangedAt  pgtype.Timestamptz `db:"changed_at" json:"changed_at"`
	ChangedBy  pgtype.UUID        `db:"changed_by" json:"changed_by"`
	Notes      pgtype.Text        `db:"notes" json:"notes"`
}

type ScheduleSubService struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	ScheduleID   pgtype.UUID        `db:"schedule_id" json:"schedule_id"`
	ServiceID    pgtype.UUID        `db:"service_id" json:"service_id"`
	SubServiceID pgtype.UUID        `db:"sub_service_id" json:"sub_service_id"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Service struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	TypeID       pgtype.UUID        `db:"type_id" json:"type_id"`
	Title        string             `db:"title" json:"title"`
	Description  string             `db:"description" json:"description"`
	Notes        pgtype.Text        `db:"notes" json:"notes"`
	Price        pgtype.Numeric     `db:"price" json:"price"`
	DiscountRate pgtype.Numeric     `db:"discount_rate" json:"discount_rate"`
	ImageUrl     pgtype.Text        `db:"image_url" json:"image_url"`
	IsActive     bool               `db:"is_active" json:"is_active"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type ServiceOrder struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	ScheduleID  pgtype.UUID        `db:"schedule_id" json:"schedule_id"`
	PrintedBy   pgtype.UUID        `db:"printed_by" json:"printed_by"`
	PrintedAt   pgtype.Timestamptz `db:"printed_at" json:"printed_at"`
	GrossTotal  pgtype.Numeric     `db:"gross_total" json:"gross_total"`
	AmountPaid  pgtype.Numeric     `db:"amount_paid" json:"amount_paid"`
	AmountToPay pgtype.Numeric     `db:"amount_to_pay" json:"amount_to_pay"`
	HasPerfume  bool               `db:"has_perfume" json:"has_perfume"`
	HasOrnament bool               `db:"has_ornament" json:"has_ornament"`
	Notes       pgtype.Text        `db:"notes" json:"notes"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ServicePlan struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	PlanTypeID   pgtype.UUID        `db:"plan_type_id" json:"plan_type_id"`
	Title        string             `db:"title" json:"title"`
	Description  string             `db:"description" json:"description"`
	Notes        pgtype.Text        `db:"notes" json:"notes"`
	Price        pgtype.Numeric     `db:"price" json:"price"`
	DiscountRate pgtype.Numeric     `db:"discount_rate" json:"discount_rate"`
	ImageUrl     pgtype.Text        `db:"image_url" json:"image_url"`
	IsActive     bool               `db:"is_active" json:"is_active"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type ServicePlanBonuse struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	ServicePlanID pgtype.UUID        `db:"service_plan_id" json:"service_plan_id"`
	ServiceID     pgtype.UUID        `db:"service_id" json:"service_id"`
	SubServiceID  pgtype.UUID        `db:"sub_service_id" json:"sub_service_id"`
	IsActive      bool               `db:"is_active" json:"is_active"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type ServicePlanService struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	ServicePlanID pgtype.UUID        `db:"service_plan_id" json:"service_plan_id"`
	ServiceID     pgtype.UUID        `db:"service_id" json:"service_id"`
	IsActive      bool               `db:"is_active" json:"is_active"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type ServicePlanSubService struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	ServicePlanID pgtype.UUID        `db:"service_plan_id" json:"service_plan_id"`
	SubServiceID  pgtype.UUID        `db:"sub_service_id" json:"sub_service_id"`
	IsActive      bool               `db:"is_active" json:"is_active"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type ServiceType struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Name        string             `db:"name" json:"name"`
	Description pgtype.Text        `db:"description" json:"description"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type ServicesAverageTime struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	ServiceID          pgtype.UUID        `db:"service_id" json:"service_id"`
	SubServiceID       pgtype.UUID        `db:"sub_service_id" json:"sub_service_id"`
	PetSize            PetSize            `db:"pet_size" json:"pet_size"`
	PetKind            PetKind            `db:"pet_kind" json:"pet_kind"`
	PetTemperament     PetTemperament     `db:"pet_temperament" json:"pet_temperament"`
	AverageTimeMinutes int16              `db:"average_time_minutes" json:"average_time_minutes"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type SubService struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	ServiceID    pgtype.UUID        `db:"service_id" json:"service_id"`
	TypeID       pgtype.UUID        `db:"type_id" json:"type_id"`
	Title        string             `db:"title" json:"title"`
	Description  string             `db:"description" json:"description"`
	Notes        pgtype.Text        `db:"notes" json:"notes"`
	Price        pgtype.Numeric     `db:"price" json:"price"`
	DiscountRate pgtype.Numeric     `db:"discount_rate" json:"discount_rate"`
	ImageUrl     pgtype.Text        `db:"image_url" json:"image_url"`
	IsActive     bool               `db:"is_active" json:"is_active"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type Translation struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	LanguageCode string             `db:"language_code" json:"language_code"`
	EntityTable  string             `db:"entity_table" json:"entity_table"`
	EntityID     pgtype.UUID        `db:"entity_id" json:"entity_id"`
	Field        string             `db:"field" json:"field"`
	Content      string             `db:"content" json:"content"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type User struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	Email           string             `db:"email" json:"email"`
	EmailVerified   bool               `db:"email_verified" json:"email_verified"`
	EmailVerifiedAt pgtype.Timestamptz `db:"email_verified_at" json:"email_verified_at"`
	Role            UserRoleType       `db:"role" json:"role"`
	IsActive        bool               `db:"is_active" json:"is_active"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type UserAuth struct {
	UserID             pgtype.UUID        `db:"user_id" json:"user_id"`
	PasswordHash       string             `db:"password_hash" json:"password_hash"`
	PasswordChangedAt  pgtype.Timestamptz `db:"password_changed_at" json:"password_changed_at"`
	MustChangePassword bool               `db:"must_change_password" json:"must_change_password"`
	LoginAttempts      int16              `db:"login_attempts" json:"login_attempts"`
	LockedUntil        pgtype.Timestamptz `db:"locked_until" json:"locked_until"`
	LastLoginAt        pgtype.Timestamptz `db:"last_login_at" json:"last_login_at"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type UserPermission struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	UserID       pgtype.UUID        `db:"user_id" json:"user_id"`
	PermissionID pgtype.UUID        `db:"permission_id" json:"permission_id"`
	GrantedBy    pgtype.UUID        `db:"granted_by" json:"granted_by"`
	IsActive     bool               `db:"is_active" json:"is_active"`
	GrantedAt    pgtype.Timestamptz `db:"granted_at" json:"granted_at"`
	RevokedBy    pgtype.UUID        `db:"revoked_by" json:"revoked_by"`
	RevokedAt    pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
}

type UserProfile struct {
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	PersonID  pgtype.UUID        `db:"person_id" json:"person_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type UserSession struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	UserID         pgtype.UUID        `db:"user_id" json:"user_id"`
	LoginHistoryID pgtype.UUID        `db:"login_history_id" json:"login_history_id"`
	SessionToken   string             `db:"session_token" json:"session_token"`
	IpAddress      netip.Addr         `db:"ip_address" json:"ip_address"`
	UserAgent      string             `db:"user_agent" json:"user_agent"`
	LastActivityAt pgtype.Timestamptz `db:"last_activity_at" json:"last_activity_at"`
	ExpiresAt      pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	LoggedOutAt    pgtype.Timestamptz `db:"logged_out_at" json:"logged_out_at"`
	LogoutReason   NullLogoutReason   `db:"logout_reason" json:"logout_reason"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type UserSetting struct {
	UserID               pgtype.UUID        `db:"user_id" json:"user_id"`
	NotificationsEnabled bool               `db:"notifications_enabled" json:"notifications_enabled"`
	Theme                string             `db:"theme" json:"theme"`
	Language             string             `db:"language" json:"language"`
	Timezone             string             `db:"timezone" json:"timezone"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
