// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUnreadNotificationsByUserID = `-- name: CountUnreadNotificationsByUserID :one
SELECT
    COUNT(*) AS unread_count
FROM
    notification_receivers nr
    JOIN notifications n ON nr.notification_id = n.id
WHERE
    nr.user_id = $1
    AND nr.read_at IS NULL
    AND n.deleted_at IS NULL
`

func (q *Queries) CountUnreadNotificationsByUserID(ctx context.Context, userid pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotificationsByUserID, userid)
	var unread_count int64
	err := row.Scan(&unread_count)
	return unread_count, err
}

const deleteNotification = `-- name: DeleteNotification :execrows
UPDATE
    notifications
SET
    deleted_at = now(),
    updated_at = now()
WHERE
    id = $1
    AND deleted_at IS NULL
`

func (q *Queries) DeleteNotification(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNotification, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteNotificationReceiver = `-- name: DeleteNotificationReceiver :execrows
DELETE FROM notification_receivers
WHERE notification_id = $1
    AND user_id = $2
`

type DeleteNotificationReceiverParams struct {
	NotificationID pgtype.UUID `db:"NotificationID" json:"NotificationID"`
	UserID         pgtype.UUID `db:"UserID" json:"UserID"`
}

func (q *Queries) DeleteNotificationReceiver(ctx context.Context, arg DeleteNotificationReceiverParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNotificationReceiver, arg.NotificationID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getNotificationByID = `-- name: GetNotificationByID :one
SELECT
    n.id,
    n.company_id,
    n.title,
    n.summary,
    n.content,
    n.send_to_whatsapp,
    n.created_by,
    n.created_at,
    n.updated_at,
    n.deleted_at
FROM
    notifications n
WHERE
    n.id = $1
    AND n.deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetNotificationByID(ctx context.Context, id pgtype.UUID) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotificationByID, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Title,
		&i.Summary,
		&i.Content,
		&i.SendToWhatsapp,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertNotification = `-- name: InsertNotification :one
INSERT INTO notifications(company_id, title, summary, content, send_to_whatsapp, created_by)
    VALUES ($1, $2, $3, $4, $5, $6)
RETURNING
    id, company_id, title, summary, content, send_to_whatsapp, created_by, created_at, updated_at, deleted_at
`

type InsertNotificationParams struct {
	CompanyID      pgtype.UUID `db:"CompanyID" json:"CompanyID"`
	Title          string      `db:"Title" json:"Title"`
	Summary        string      `db:"Summary" json:"Summary"`
	Content        string      `db:"Content" json:"Content"`
	SendToWhatsapp pgtype.Bool `db:"SendToWhatsapp" json:"SendToWhatsapp"`
	CreatedBy      pgtype.UUID `db:"CreatedBy" json:"CreatedBy"`
}

func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, insertNotification,
		arg.CompanyID,
		arg.Title,
		arg.Summary,
		arg.Content,
		arg.SendToWhatsapp,
		arg.CreatedBy,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Title,
		&i.Summary,
		&i.Content,
		&i.SendToWhatsapp,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertNotificationReceiver = `-- name: InsertNotificationReceiver :execrows
INSERT INTO notification_receivers(notification_id, user_id)
    VALUES ($1, $2)
`

type InsertNotificationReceiverParams struct {
	NotificationID pgtype.UUID `db:"NotificationID" json:"NotificationID"`
	UserID         pgtype.UUID `db:"UserID" json:"UserID"`
}

func (q *Queries) InsertNotificationReceiver(ctx context.Context, arg InsertNotificationReceiverParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertNotificationReceiver, arg.NotificationID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listNotificationReceiversByUserID = `-- name: ListNotificationReceiversByUserID :many
SELECT
    nr.id,
    nr.notification_id,
    nr.user_id,
    nr.read_at,
    nr.created_at,
    n.title AS notification_title,
    n.summary AS notification_summary,
    n.company_id AS notification_company_id
FROM
    notification_receivers nr
    JOIN notifications n ON nr.notification_id = n.id
WHERE
    nr.user_id = $1
    AND n.deleted_at IS NULL
ORDER BY
    nr.created_at DESC
LIMIT $3
OFFSET $2
`

type ListNotificationReceiversByUserIDParams struct {
	UserID pgtype.UUID `db:"UserID" json:"UserID"`
	Offset int32       `db:"Offset" json:"Offset"`
	Limit  int32       `db:"Limit" json:"Limit"`
}

type ListNotificationReceiversByUserIDRow struct {
	ID                    pgtype.UUID        `db:"id" json:"id"`
	NotificationID        pgtype.UUID        `db:"notification_id" json:"notification_id"`
	UserID                pgtype.UUID        `db:"user_id" json:"user_id"`
	ReadAt                pgtype.Timestamptz `db:"read_at" json:"read_at"`
	CreatedAt             pgtype.Timestamptz `db:"created_at" json:"created_at"`
	NotificationTitle     string             `db:"notification_title" json:"notification_title"`
	NotificationSummary   string             `db:"notification_summary" json:"notification_summary"`
	NotificationCompanyID pgtype.UUID        `db:"notification_company_id" json:"notification_company_id"`
}

func (q *Queries) ListNotificationReceiversByUserID(ctx context.Context, arg ListNotificationReceiversByUserIDParams) ([]ListNotificationReceiversByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listNotificationReceiversByUserID, arg.UserID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotificationReceiversByUserIDRow
	for rows.Next() {
		var i ListNotificationReceiversByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.NotificationID,
			&i.UserID,
			&i.ReadAt,
			&i.CreatedAt,
			&i.NotificationTitle,
			&i.NotificationSummary,
			&i.NotificationCompanyID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationsByCompanyID = `-- name: ListNotificationsByCompanyID :many
SELECT
    n.id,
    n.company_id,
    n.title,
    n.summary,
    n.content,
    n.send_to_whatsapp,
    n.created_by,
    n.created_at,
    n.updated_at,
    n.deleted_at
FROM
    notifications n
WHERE (n.company_id = $1
    OR n.company_id IS NULL)
AND n.deleted_at IS NULL
ORDER BY
    n.created_at DESC
LIMIT $3
OFFSET $2
`

type ListNotificationsByCompanyIDParams struct {
	CompanyID pgtype.UUID `db:"CompanyID" json:"CompanyID"`
	Offset    int32       `db:"Offset" json:"Offset"`
	Limit     int32       `db:"Limit" json:"Limit"`
}

func (q *Queries) ListNotificationsByCompanyID(ctx context.Context, arg ListNotificationsByCompanyIDParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsByCompanyID, arg.CompanyID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Title,
			&i.Summary,
			&i.Content,
			&i.SendToWhatsapp,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationAsRead = `-- name: MarkNotificationAsRead :execrows
UPDATE
    notification_receivers
SET
    read_at = now()
WHERE
    notification_id = $1
    AND user_id = $2
    AND read_at IS NULL
`

type MarkNotificationAsReadParams struct {
	NotificationID pgtype.UUID `db:"NotificationID" json:"NotificationID"`
	UserID         pgtype.UUID `db:"UserID" json:"UserID"`
}

func (q *Queries) MarkNotificationAsRead(ctx context.Context, arg MarkNotificationAsReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationAsRead, arg.NotificationID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateNotification = `-- name: UpdateNotification :execrows
UPDATE
    notifications
SET
    title = coalesce($1, title),
    summary = coalesce($2, summary),
    content = coalesce($3, content),
    send_to_whatsapp = coalesce($4, send_to_whatsapp),
    updated_at = now()
WHERE
    id = $5
    AND deleted_at IS NULL
`

type UpdateNotificationParams struct {
	Title          pgtype.Text `db:"Title" json:"Title"`
	Summary        pgtype.Text `db:"Summary" json:"Summary"`
	Content        pgtype.Text `db:"Content" json:"Content"`
	SendToWhatsapp pgtype.Bool `db:"SendToWhatsapp" json:"SendToWhatsapp"`
	ID             pgtype.UUID `db:"ID" json:"ID"`
}

func (q *Queries) UpdateNotification(ctx context.Context, arg UpdateNotificationParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateNotification,
		arg.Title,
		arg.Summary,
		arg.Content,
		arg.SendToWhatsapp,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
