// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: password_recovery_tokens.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPasswordRecoveryTokenByHash = `-- name: GetPasswordRecoveryTokenByHash :one
SELECT
    prt.id,
    prt.user_id,
    prt.token_hash,
    prt.requested_email,
    prt.expires_at,
    prt.used_at,
    prt.revoked_at,
    prt.request_ip,
    prt.request_user_agent,
    prt.triggered_by_user_id
FROM
    password_recovery_tokens prt
WHERE
    prt.token_hash = $1
`

type GetPasswordRecoveryTokenByHashRow struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	UserID            pgtype.UUID        `db:"user_id" json:"user_id"`
	TokenHash         string             `db:"token_hash" json:"token_hash"`
	RequestedEmail    string             `db:"requested_email" json:"requested_email"`
	ExpiresAt         pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	UsedAt            pgtype.Timestamptz `db:"used_at" json:"used_at"`
	RevokedAt         pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	RequestIp         *netip.Addr        `db:"request_ip" json:"request_ip"`
	RequestUserAgent  pgtype.Text        `db:"request_user_agent" json:"request_user_agent"`
	TriggeredByUserID pgtype.UUID        `db:"triggered_by_user_id" json:"triggered_by_user_id"`
}

func (q *Queries) GetPasswordRecoveryTokenByHash(ctx context.Context, tokenhash string) (GetPasswordRecoveryTokenByHashRow, error) {
	row := q.db.QueryRow(ctx, getPasswordRecoveryTokenByHash, tokenhash)
	var i GetPasswordRecoveryTokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.RequestedEmail,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
		&i.RequestIp,
		&i.RequestUserAgent,
		&i.TriggeredByUserID,
	)
	return i, err
}

const insertPasswordRecoveryToken = `-- name: InsertPasswordRecoveryToken :execrows
INSERT INTO password_recovery_tokens(user_id, token_hash, requested_email, expires_at, used_at, revoked_at, request_ip, request_user_agent, triggered_by_user_id)
    VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertPasswordRecoveryTokenParams struct {
	UserID            pgtype.UUID        `db:"UserID" json:"UserID"`
	TokenHash         string             `db:"TokenHash" json:"TokenHash"`
	RequestedEmail    string             `db:"RequestedEmail" json:"RequestedEmail"`
	ExpiresAt         pgtype.Timestamptz `db:"ExpiresAt" json:"ExpiresAt"`
	UsedAt            pgtype.Timestamptz `db:"UsedAt" json:"UsedAt"`
	RevokedAt         pgtype.Timestamptz `db:"RevokedAt" json:"RevokedAt"`
	RequestIP         *netip.Addr        `db:"RequestIP" json:"RequestIP"`
	RequestUserAgent  pgtype.Text        `db:"RequestUserAgent" json:"RequestUserAgent"`
	TriggeredByUserID pgtype.UUID        `db:"TriggeredByUserID" json:"TriggeredByUserID"`
}

func (q *Queries) InsertPasswordRecoveryToken(ctx context.Context, arg InsertPasswordRecoveryTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertPasswordRecoveryToken,
		arg.UserID,
		arg.TokenHash,
		arg.RequestedEmail,
		arg.ExpiresAt,
		arg.UsedAt,
		arg.RevokedAt,
		arg.RequestIP,
		arg.RequestUserAgent,
		arg.TriggeredByUserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listActivePasswordRecoveryTokensByUserID = `-- name: ListActivePasswordRecoveryTokensByUserID :many
SELECT
    prt.id,
    prt.user_id,
    prt.token_hash,
    prt.requested_email,
    prt.expires_at,
    prt.used_at,
    prt.revoked_at,
    prt.request_ip,
    prt.request_user_agent,
    prt.triggered_by_user_id
FROM
    password_recovery_tokens prt
WHERE
    prt.user_id = $1
    AND prt.used_at IS NULL
    AND prt.revoked_at IS NULL
    AND prt.expires_at > NOW()
ORDER BY
    prt.expires_at DESC
LIMIT $3
OFFSET $2
`

type ListActivePasswordRecoveryTokensByUserIDParams struct {
	UserID pgtype.UUID `db:"UserID" json:"UserID"`
	Offset int32       `db:"Offset" json:"Offset"`
	Limit  int32       `db:"Limit" json:"Limit"`
}

type ListActivePasswordRecoveryTokensByUserIDRow struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	UserID            pgtype.UUID        `db:"user_id" json:"user_id"`
	TokenHash         string             `db:"token_hash" json:"token_hash"`
	RequestedEmail    string             `db:"requested_email" json:"requested_email"`
	ExpiresAt         pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	UsedAt            pgtype.Timestamptz `db:"used_at" json:"used_at"`
	RevokedAt         pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	RequestIp         *netip.Addr        `db:"request_ip" json:"request_ip"`
	RequestUserAgent  pgtype.Text        `db:"request_user_agent" json:"request_user_agent"`
	TriggeredByUserID pgtype.UUID        `db:"triggered_by_user_id" json:"triggered_by_user_id"`
}

func (q *Queries) ListActivePasswordRecoveryTokensByUserID(ctx context.Context, arg ListActivePasswordRecoveryTokensByUserIDParams) ([]ListActivePasswordRecoveryTokensByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listActivePasswordRecoveryTokensByUserID, arg.UserID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActivePasswordRecoveryTokensByUserIDRow
	for rows.Next() {
		var i ListActivePasswordRecoveryTokensByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.RequestedEmail,
			&i.ExpiresAt,
			&i.UsedAt,
			&i.RevokedAt,
			&i.RequestIp,
			&i.RequestUserAgent,
			&i.TriggeredByUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPasswordRecoveryTokenAsUsed = `-- name: MarkPasswordRecoveryTokenAsUsed :execrows
UPDATE
    password_recovery_tokens
SET
    used_at = $1
WHERE
    token_hash = $2
    AND used_at IS NULL
    AND revoked_at IS NULL
`

type MarkPasswordRecoveryTokenAsUsedParams struct {
	UsedAt    pgtype.Timestamptz `db:"UsedAt" json:"UsedAt"`
	TokenHash string             `db:"TokenHash" json:"TokenHash"`
}

func (q *Queries) MarkPasswordRecoveryTokenAsUsed(ctx context.Context, arg MarkPasswordRecoveryTokenAsUsedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markPasswordRecoveryTokenAsUsed, arg.UsedAt, arg.TokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokePasswordRecoveryToken = `-- name: RevokePasswordRecoveryToken :execrows
UPDATE
    password_recovery_tokens
SET
    revoked_at = $1
WHERE
    token_hash = $2
    AND used_at IS NULL
    AND revoked_at IS NULL
`

type RevokePasswordRecoveryTokenParams struct {
	RevokedAt pgtype.Timestamptz `db:"RevokedAt" json:"RevokedAt"`
	TokenHash string             `db:"TokenHash" json:"TokenHash"`
}

func (q *Queries) RevokePasswordRecoveryToken(ctx context.Context, arg RevokePasswordRecoveryTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokePasswordRecoveryToken, arg.RevokedAt, arg.TokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
