// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: people_addresses.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deletePersonAddress = `-- name: DeletePersonAddress :execrows
DELETE FROM people_addresses
WHERE person_id = $1
    AND address_id = $2
`

type DeletePersonAddressParams struct {
	PersonID  pgtype.UUID `db:"PersonID" json:"PersonID"`
	AddressID pgtype.UUID `db:"AddressID" json:"AddressID"`
}

func (q *Queries) DeletePersonAddress(ctx context.Context, arg DeletePersonAddressParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePersonAddress, arg.PersonID, arg.AddressID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPersonAddress = `-- name: GetPersonAddress :one
SELECT
    pa.id,
    pa.person_id,
    pa.address_id,
    pa.is_main,
    pa.label,
    pa.created_at
FROM
    people_addresses pa
WHERE
    pa.person_id = $1
    AND pa.address_id = $2
`

type GetPersonAddressParams struct {
	PersonID  pgtype.UUID `db:"PersonID" json:"PersonID"`
	AddressID pgtype.UUID `db:"AddressID" json:"AddressID"`
}

func (q *Queries) GetPersonAddress(ctx context.Context, arg GetPersonAddressParams) (PeopleAddress, error) {
	row := q.db.QueryRow(ctx, getPersonAddress, arg.PersonID, arg.AddressID)
	var i PeopleAddress
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.AddressID,
		&i.IsMain,
		&i.Label,
		&i.CreatedAt,
	)
	return i, err
}

const insertPersonAddress = `-- name: InsertPersonAddress :execrows
INSERT INTO people_addresses(person_id, address_id, is_main, label)
    VALUES ($1, $2, $3, $4)
`

type InsertPersonAddressParams struct {
	PersonID  pgtype.UUID `db:"PersonID" json:"PersonID"`
	AddressID pgtype.UUID `db:"AddressID" json:"AddressID"`
	IsMain    bool        `db:"IsMain" json:"IsMain"`
	Label     pgtype.Text `db:"Label" json:"Label"`
}

func (q *Queries) InsertPersonAddress(ctx context.Context, arg InsertPersonAddressParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertPersonAddress,
		arg.PersonID,
		arg.AddressID,
		arg.IsMain,
		arg.Label,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listPersonAddresses = `-- name: ListPersonAddresses :many
SELECT
    pa.id,
    pa.person_id,
    pa.address_id,
    pa.is_main,
    pa.label,
    pa.created_at
FROM
    people_addresses pa
WHERE
    pa.person_id = $1
ORDER BY
    pa.created_at DESC
LIMIT $3
OFFSET $2
`

type ListPersonAddressesParams struct {
	PersonID pgtype.UUID `db:"PersonID" json:"PersonID"`
	Offset   int32       `db:"Offset" json:"Offset"`
	Limit    int32       `db:"Limit" json:"Limit"`
}

func (q *Queries) ListPersonAddresses(ctx context.Context, arg ListPersonAddressesParams) ([]PeopleAddress, error) {
	rows, err := q.db.Query(ctx, listPersonAddresses, arg.PersonID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PeopleAddress
	for rows.Next() {
		var i PeopleAddress
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.AddressID,
			&i.IsMain,
			&i.Label,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePersonAddress = `-- name: UpdatePersonAddress :execrows
UPDATE
    people_addresses
SET
    is_main = COALESCE($1, is_main),
    label = COALESCE($2, label),
    updated_at = now()
WHERE
    id = $3
`

type UpdatePersonAddressParams struct {
	IsMain pgtype.Bool `db:"IsMain" json:"IsMain"`
	Label  pgtype.Text `db:"Label" json:"Label"`
	ID     pgtype.UUID `db:"ID" json:"ID"`
}

func (q *Queries) UpdatePersonAddress(ctx context.Context, arg UpdatePersonAddressParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePersonAddress, arg.IsMain, arg.Label, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
