// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: people_finances.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPersonFinance = `-- name: GetPersonFinance :one
SELECT
    f.id AS finance_id,
    f.bank_name,
    f.bank_code,
    f.bank_branch,
    f.bank_account,
    f.bank_account_digit,
    f.bank_account_type,
    f.has_pix,
    f.pix_key,
    f.pix_key_type,
    f.created_at AS finance_created_at,
    f.updated_at AS finance_updated_at,
    pf.id AS person_finance_id,
    pf.person_id,
    pf.is_primary,
    pf.created_at AS person_finance_created_at,
    pf.updated_at AS person_finance_updated_at
FROM
    people_finances pf
    JOIN finances f ON pf.finance_id = f.id
WHERE
    pf.person_id = $1
    AND pf.finance_id = $2
`

type GetPersonFinanceParams struct {
	PersonID  pgtype.UUID `db:"PersonID" json:"PersonID"`
	FinanceID pgtype.UUID `db:"FinanceID" json:"FinanceID"`
}

type GetPersonFinanceRow struct {
	FinanceID              pgtype.UUID        `db:"finance_id" json:"finance_id"`
	BankName               string             `db:"bank_name" json:"bank_name"`
	BankCode               pgtype.Text        `db:"bank_code" json:"bank_code"`
	BankBranch             string             `db:"bank_branch" json:"bank_branch"`
	BankAccount            string             `db:"bank_account" json:"bank_account"`
	BankAccountDigit       string             `db:"bank_account_digit" json:"bank_account_digit"`
	BankAccountType        BankAccountKind    `db:"bank_account_type" json:"bank_account_type"`
	HasPix                 bool               `db:"has_pix" json:"has_pix"`
	PixKey                 pgtype.Text        `db:"pix_key" json:"pix_key"`
	PixKeyType             NullPixKeyKind     `db:"pix_key_type" json:"pix_key_type"`
	FinanceCreatedAt       pgtype.Timestamptz `db:"finance_created_at" json:"finance_created_at"`
	FinanceUpdatedAt       pgtype.Timestamptz `db:"finance_updated_at" json:"finance_updated_at"`
	PersonFinanceID        pgtype.UUID        `db:"person_finance_id" json:"person_finance_id"`
	PersonID               pgtype.UUID        `db:"person_id" json:"person_id"`
	IsPrimary              bool               `db:"is_primary" json:"is_primary"`
	PersonFinanceCreatedAt pgtype.Timestamptz `db:"person_finance_created_at" json:"person_finance_created_at"`
	PersonFinanceUpdatedAt pgtype.Timestamptz `db:"person_finance_updated_at" json:"person_finance_updated_at"`
}

func (q *Queries) GetPersonFinance(ctx context.Context, arg GetPersonFinanceParams) (GetPersonFinanceRow, error) {
	row := q.db.QueryRow(ctx, getPersonFinance, arg.PersonID, arg.FinanceID)
	var i GetPersonFinanceRow
	err := row.Scan(
		&i.FinanceID,
		&i.BankName,
		&i.BankCode,
		&i.BankBranch,
		&i.BankAccount,
		&i.BankAccountDigit,
		&i.BankAccountType,
		&i.HasPix,
		&i.PixKey,
		&i.PixKeyType,
		&i.FinanceCreatedAt,
		&i.FinanceUpdatedAt,
		&i.PersonFinanceID,
		&i.PersonID,
		&i.IsPrimary,
		&i.PersonFinanceCreatedAt,
		&i.PersonFinanceUpdatedAt,
	)
	return i, err
}

const insertPersonFinance = `-- name: InsertPersonFinance :execrows
INSERT INTO people_finances(person_id, finance_id, is_primary)
    VALUES ($1, $2, $3)
`

type InsertPersonFinanceParams struct {
	PersonID  pgtype.UUID `db:"PersonID" json:"PersonID"`
	FinanceID pgtype.UUID `db:"FinanceID" json:"FinanceID"`
	IsPrimary pgtype.Bool `db:"IsPrimary" json:"IsPrimary"`
}

func (q *Queries) InsertPersonFinance(ctx context.Context, arg InsertPersonFinanceParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertPersonFinance, arg.PersonID, arg.FinanceID, arg.IsPrimary)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listPersonFinances = `-- name: ListPersonFinances :many
SELECT
    f.id AS finance_id,
    f.bank_name,
    f.bank_code,
    f.bank_branch,
    f.bank_account,
    f.bank_account_digit,
    f.bank_account_type,
    f.has_pix,
    f.pix_key,
    f.pix_key_type,
    f.created_at AS finance_created_at,
    f.updated_at AS finance_updated_at,
    pf.id AS person_finance_id,
    pf.person_id,
    pf.is_primary,
    pf.created_at AS person_finance_created_at,
    pf.updated_at AS person_finance_updated_at
FROM
    people_finances pf
    JOIN finances f ON pf.finance_id = f.id
WHERE
    pf.person_id = $1
ORDER BY
    pf.created_at DESC
LIMIT $3
OFFSET $2
`

type ListPersonFinancesParams struct {
	PersonID pgtype.UUID `db:"PersonID" json:"PersonID"`
	Offset   int32       `db:"Offset" json:"Offset"`
	Limit    int32       `db:"Limit" json:"Limit"`
}

type ListPersonFinancesRow struct {
	FinanceID              pgtype.UUID        `db:"finance_id" json:"finance_id"`
	BankName               string             `db:"bank_name" json:"bank_name"`
	BankCode               pgtype.Text        `db:"bank_code" json:"bank_code"`
	BankBranch             string             `db:"bank_branch" json:"bank_branch"`
	BankAccount            string             `db:"bank_account" json:"bank_account"`
	BankAccountDigit       string             `db:"bank_account_digit" json:"bank_account_digit"`
	BankAccountType        BankAccountKind    `db:"bank_account_type" json:"bank_account_type"`
	HasPix                 bool               `db:"has_pix" json:"has_pix"`
	PixKey                 pgtype.Text        `db:"pix_key" json:"pix_key"`
	PixKeyType             NullPixKeyKind     `db:"pix_key_type" json:"pix_key_type"`
	FinanceCreatedAt       pgtype.Timestamptz `db:"finance_created_at" json:"finance_created_at"`
	FinanceUpdatedAt       pgtype.Timestamptz `db:"finance_updated_at" json:"finance_updated_at"`
	PersonFinanceID        pgtype.UUID        `db:"person_finance_id" json:"person_finance_id"`
	PersonID               pgtype.UUID        `db:"person_id" json:"person_id"`
	IsPrimary              bool               `db:"is_primary" json:"is_primary"`
	PersonFinanceCreatedAt pgtype.Timestamptz `db:"person_finance_created_at" json:"person_finance_created_at"`
	PersonFinanceUpdatedAt pgtype.Timestamptz `db:"person_finance_updated_at" json:"person_finance_updated_at"`
}

func (q *Queries) ListPersonFinances(ctx context.Context, arg ListPersonFinancesParams) ([]ListPersonFinancesRow, error) {
	rows, err := q.db.Query(ctx, listPersonFinances, arg.PersonID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPersonFinancesRow
	for rows.Next() {
		var i ListPersonFinancesRow
		if err := rows.Scan(
			&i.FinanceID,
			&i.BankName,
			&i.BankCode,
			&i.BankBranch,
			&i.BankAccount,
			&i.BankAccountDigit,
			&i.BankAccountType,
			&i.HasPix,
			&i.PixKey,
			&i.PixKeyType,
			&i.FinanceCreatedAt,
			&i.FinanceUpdatedAt,
			&i.PersonFinanceID,
			&i.PersonID,
			&i.IsPrimary,
			&i.PersonFinanceCreatedAt,
			&i.PersonFinanceUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePersonFinance = `-- name: UpdatePersonFinance :execrows
UPDATE
    people_finances
SET
    is_primary = COALESCE($1, is_primary),
    updated_at = now()
WHERE
    person_id = $2
    AND finance_id = $3
`

type UpdatePersonFinanceParams struct {
	IsPrimary pgtype.Bool `db:"IsPrimary" json:"IsPrimary"`
	ID        pgtype.UUID `db:"ID" json:"ID"`
	FinanceID pgtype.UUID `db:"FinanceID" json:"FinanceID"`
}

func (q *Queries) UpdatePersonFinance(ctx context.Context, arg UpdatePersonFinanceParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePersonFinance, arg.IsPrimary, arg.ID, arg.FinanceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
