// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: people.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deletePerson = `-- name: DeletePerson :execrows
DELETE FROM people
WHERE id = $1
`

func (q *Queries) DeletePerson(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePerson, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPerson = `-- name: GetPerson :one
SELECT
    p.id,
    p.kind,
    p.is_active,
    p.has_system_user,
    p.created_at,
    p.updated_at,
    pi.full_name,
    PI.short_name,
    pi.gender_identity,
    pi.marital_status,
    pi.image_url,
    pi.birth_date,
    pi.cpf,
    pi.created_at AS identifications_created_at,
    pi.updated_at AS identifications_updated_at
FROM
    people p
    LEFT JOIN people_identifications pi ON p.id = pi.person_id
WHERE
    p.id = $1
`

type GetPersonRow struct {
	ID                       pgtype.UUID        `db:"id" json:"id"`
	Kind                     PersonKind         `db:"kind" json:"kind"`
	IsActive                 bool               `db:"is_active" json:"is_active"`
	HasSystemUser            bool               `db:"has_system_user" json:"has_system_user"`
	CreatedAt                pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	FullName                 pgtype.Text        `db:"full_name" json:"full_name"`
	ShortName                pgtype.Text        `db:"short_name" json:"short_name"`
	GenderIdentity           NullGenderIdentity `db:"gender_identity" json:"gender_identity"`
	MaritalStatus            NullMaritalStatus  `db:"marital_status" json:"marital_status"`
	ImageUrl                 pgtype.Text        `db:"image_url" json:"image_url"`
	BirthDate                pgtype.Date        `db:"birth_date" json:"birth_date"`
	Cpf                      pgtype.Text        `db:"cpf" json:"cpf"`
	IdentificationsCreatedAt pgtype.Timestamptz `db:"identifications_created_at" json:"identifications_created_at"`
	IdentificationsUpdatedAt pgtype.Timestamptz `db:"identifications_updated_at" json:"identifications_updated_at"`
}

func (q *Queries) GetPerson(ctx context.Context, id pgtype.UUID) (GetPersonRow, error) {
	row := q.db.QueryRow(ctx, getPerson, id)
	var i GetPersonRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.IsActive,
		&i.HasSystemUser,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FullName,
		&i.ShortName,
		&i.GenderIdentity,
		&i.MaritalStatus,
		&i.ImageUrl,
		&i.BirthDate,
		&i.Cpf,
		&i.IdentificationsCreatedAt,
		&i.IdentificationsUpdatedAt,
	)
	return i, err
}

const insertPerson = `-- name: InsertPerson :one
INSERT INTO people(kind, is_active, has_system_user)
    VALUES ($1, $2, $3)
RETURNING id, kind, is_active, has_system_user, created_at, updated_at
`

type InsertPersonParams struct {
	Kind          PersonKind  `db:"Kind" json:"Kind"`
	IsActive      pgtype.Bool `db:"IsActive" json:"IsActive"`
	HasSystemUser pgtype.Bool `db:"HasSystemUser" json:"HasSystemUser"`
}

func (q *Queries) InsertPerson(ctx context.Context, arg InsertPersonParams) (Person, error) {
	row := q.db.QueryRow(ctx, insertPerson, arg.Kind, arg.IsActive, arg.HasSystemUser)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.IsActive,
		&i.HasSystemUser,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPeople = `-- name: ListPeople :many
SELECT
    p.id,
    p.kind,
    p.is_active,
    p.has_system_user,
    p.created_at,
    p.updated_at,
    pi.full_name,
    PI.short_name,
    pi.gender_identity,
    pi.marital_status,
    pi.image_url,
    pi.birth_date,
    pi.cpf,
    pi.created_at AS identifications_created_at,
    pi.updated_at AS identifications_updated_at
FROM
    people p
    LEFT JOIN people_identifications pi ON p.id = pi.person_id
WHERE ($1::person_kind IS NULL
    OR p.kind = $1::person_kind)
AND ($2::BOOLEAN IS NULL
    OR p.is_active = $2::BOOLEAN)
AND ($3::BOOLEAN IS NULL
    OR p.has_system_user = $3::BOOLEAN)
ORDER BY
    p.created_at DESC
LIMIT $5
OFFSET $4
`

type ListPeopleParams struct {
	Kind          NullPersonKind `db:"Kind" json:"Kind"`
	IsActive      pgtype.Bool    `db:"IsActive" json:"IsActive"`
	HasSystemUser pgtype.Bool    `db:"HasSystemUser" json:"HasSystemUser"`
	Offset        int32          `db:"Offset" json:"Offset"`
	Limit         int32          `db:"Limit" json:"Limit"`
}

type ListPeopleRow struct {
	ID                       pgtype.UUID        `db:"id" json:"id"`
	Kind                     PersonKind         `db:"kind" json:"kind"`
	IsActive                 bool               `db:"is_active" json:"is_active"`
	HasSystemUser            bool               `db:"has_system_user" json:"has_system_user"`
	CreatedAt                pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	FullName                 pgtype.Text        `db:"full_name" json:"full_name"`
	ShortName                pgtype.Text        `db:"short_name" json:"short_name"`
	GenderIdentity           NullGenderIdentity `db:"gender_identity" json:"gender_identity"`
	MaritalStatus            NullMaritalStatus  `db:"marital_status" json:"marital_status"`
	ImageUrl                 pgtype.Text        `db:"image_url" json:"image_url"`
	BirthDate                pgtype.Date        `db:"birth_date" json:"birth_date"`
	Cpf                      pgtype.Text        `db:"cpf" json:"cpf"`
	IdentificationsCreatedAt pgtype.Timestamptz `db:"identifications_created_at" json:"identifications_created_at"`
	IdentificationsUpdatedAt pgtype.Timestamptz `db:"identifications_updated_at" json:"identifications_updated_at"`
}

func (q *Queries) ListPeople(ctx context.Context, arg ListPeopleParams) ([]ListPeopleRow, error) {
	rows, err := q.db.Query(ctx, listPeople,
		arg.Kind,
		arg.IsActive,
		arg.HasSystemUser,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPeopleRow
	for rows.Next() {
		var i ListPeopleRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.IsActive,
			&i.HasSystemUser,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FullName,
			&i.ShortName,
			&i.GenderIdentity,
			&i.MaritalStatus,
			&i.ImageUrl,
			&i.BirthDate,
			&i.Cpf,
			&i.IdentificationsCreatedAt,
			&i.IdentificationsUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePerson = `-- name: UpdatePerson :execrows
UPDATE
    people
SET
    kind = COALESCE($1, kind),
    is_active = COALESCE($2, is_active),
    has_system_user = COALESCE($3, has_system_user),
    updated_at = now()
WHERE
    id = $4
`

type UpdatePersonParams struct {
	Kind          NullPersonKind `db:"Kind" json:"Kind"`
	IsActive      pgtype.Bool    `db:"IsActive" json:"IsActive"`
	HasSystemUser pgtype.Bool    `db:"HasSystemUser" json:"HasSystemUser"`
	ID            pgtype.UUID    `db:"ID" json:"ID"`
}

func (q *Queries) UpdatePerson(ctx context.Context, arg UpdatePersonParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePerson,
		arg.Kind,
		arg.IsActive,
		arg.HasSystemUser,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
