// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pet_guardians.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deletePetGuardiansByGuardianID = `-- name: DeletePetGuardiansByGuardianID :execrows
DELETE FROM pet_guardians
WHERE guardian_id = $1
`

func (q *Queries) DeletePetGuardiansByGuardianID(ctx context.Context, guardianid pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePetGuardiansByGuardianID, guardianid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listGuardianPetsByCompanyID = `-- name: ListGuardianPetsByCompanyID :many
SELECT
    pg.pet_id,
    p.name,
    p.kind,
    p.size,
    pi.full_name AS owner_name
FROM
    pet_guardians pg
    INNER JOIN pets p ON p.id = pg.pet_id
    INNER JOIN clients c ON c.id = p.owner_id
    INNER JOIN company_clients cc ON cc.client_id = c.id
    INNER JOIN people_identifications pi ON pi.person_id = c.person_id
WHERE
    pg.guardian_id = $1
    AND cc.company_id = $2
    AND cc.is_active = TRUE
    AND c.deleted_at IS NULL
    AND p.deleted_at IS NULL
    AND p.is_active = TRUE
ORDER BY
    p.name ASC
`

type ListGuardianPetsByCompanyIDParams struct {
	GuardianID pgtype.UUID `db:"GuardianID" json:"GuardianID"`
	CompanyID  pgtype.UUID `db:"CompanyID" json:"CompanyID"`
}

type ListGuardianPetsByCompanyIDRow struct {
	PetID     pgtype.UUID `db:"pet_id" json:"pet_id"`
	Name      string      `db:"name" json:"name"`
	Kind      PetKind     `db:"kind" json:"kind"`
	Size      PetSize     `db:"size" json:"size"`
	OwnerName string      `db:"owner_name" json:"owner_name"`
}

func (q *Queries) ListGuardianPetsByCompanyID(ctx context.Context, arg ListGuardianPetsByCompanyIDParams) ([]ListGuardianPetsByCompanyIDRow, error) {
	rows, err := q.db.Query(ctx, listGuardianPetsByCompanyID, arg.GuardianID, arg.CompanyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGuardianPetsByCompanyIDRow
	for rows.Next() {
		var i ListGuardianPetsByCompanyIDRow
		if err := rows.Scan(
			&i.PetID,
			&i.Name,
			&i.Kind,
			&i.Size,
			&i.OwnerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPetGuardian = `-- name: UpsertPetGuardian :execrows
INSERT INTO pet_guardians(pet_id, guardian_id)
    VALUES ($1, $2)
ON CONFLICT (pet_id) DO UPDATE SET
    guardian_id = EXCLUDED.guardian_id
`

type UpsertPetGuardianParams struct {
	PetID      pgtype.UUID `db:"PetID" json:"PetID"`
	GuardianID pgtype.UUID `db:"GuardianID" json:"GuardianID"`
}

func (q *Queries) UpsertPetGuardian(ctx context.Context, arg UpsertPetGuardianParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertPetGuardian, arg.PetID, arg.GuardianID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
