// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pet_guardians.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deletePetGuardiansByGuardianID = `-- name: DeletePetGuardiansByGuardianID :execrows
DELETE FROM pet_guardians
WHERE guardian_id = $1
`

func (q *Queries) DeletePetGuardiansByGuardianID(ctx context.Context, guardianid pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePetGuardiansByGuardianID, guardianid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listGuardianPetsByCompanyID = `-- name: ListGuardianPetsByCompanyID :many
SELECT
    pg.pet_id,
    p.name,
    p.race,
    p.color,
    p.sex,
    p.size,
    p.kind,
    p.temperament,
    p.image_url,
    p.birth_date,
    p.is_active,
    p.is_deceased,
    p.is_vaccinated,
    p.is_neutered,
    p.is_microchipped,
    p.microchip_number,
    p.microchip_expiration_date,
    p.notes,
    p.created_at,
    p.updated_at,
    p.deleted_at,
    pi.full_name AS owner_name
FROM
    pet_guardians pg
    INNER JOIN pets p ON p.id = pg.pet_id
    INNER JOIN clients c ON c.id = p.owner_id
    INNER JOIN company_clients cc ON cc.client_id = c.id
    INNER JOIN people_identifications pi ON pi.person_id = c.person_id
WHERE
    pg.guardian_id = $1
    AND cc.company_id = $2
    AND cc.is_active = TRUE
    AND c.deleted_at IS NULL
    AND p.deleted_at IS NULL
    AND p.is_active = TRUE
ORDER BY
    p.name ASC
`

type ListGuardianPetsByCompanyIDParams struct {
	GuardianID pgtype.UUID `db:"GuardianID" json:"GuardianID"`
	CompanyID  pgtype.UUID `db:"CompanyID" json:"CompanyID"`
}

type ListGuardianPetsByCompanyIDRow struct {
	PetID                   pgtype.UUID        `db:"pet_id" json:"pet_id"`
	Name                    string             `db:"name" json:"name"`
	Race                    string             `db:"race" json:"race"`
	Color                   string             `db:"color" json:"color"`
	Sex                     string             `db:"sex" json:"sex"`
	Size                    PetSize            `db:"size" json:"size"`
	Kind                    PetKind            `db:"kind" json:"kind"`
	Temperament             PetTemperament     `db:"temperament" json:"temperament"`
	ImageUrl                pgtype.Text        `db:"image_url" json:"image_url"`
	BirthDate               pgtype.Date        `db:"birth_date" json:"birth_date"`
	IsActive                bool               `db:"is_active" json:"is_active"`
	IsDeceased              bool               `db:"is_deceased" json:"is_deceased"`
	IsVaccinated            bool               `db:"is_vaccinated" json:"is_vaccinated"`
	IsNeutered              bool               `db:"is_neutered" json:"is_neutered"`
	IsMicrochipped          bool               `db:"is_microchipped" json:"is_microchipped"`
	MicrochipNumber         pgtype.Text        `db:"microchip_number" json:"microchip_number"`
	MicrochipExpirationDate pgtype.Date        `db:"microchip_expiration_date" json:"microchip_expiration_date"`
	Notes                   pgtype.Text        `db:"notes" json:"notes"`
	CreatedAt               pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt               pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	OwnerName               string             `db:"owner_name" json:"owner_name"`
}

func (q *Queries) ListGuardianPetsByCompanyID(ctx context.Context, arg ListGuardianPetsByCompanyIDParams) ([]ListGuardianPetsByCompanyIDRow, error) {
	rows, err := q.db.Query(ctx, listGuardianPetsByCompanyID, arg.GuardianID, arg.CompanyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGuardianPetsByCompanyIDRow
	for rows.Next() {
		var i ListGuardianPetsByCompanyIDRow
		if err := rows.Scan(
			&i.PetID,
			&i.Name,
			&i.Race,
			&i.Color,
			&i.Sex,
			&i.Size,
			&i.Kind,
			&i.Temperament,
			&i.ImageUrl,
			&i.BirthDate,
			&i.IsActive,
			&i.IsDeceased,
			&i.IsVaccinated,
			&i.IsNeutered,
			&i.IsMicrochipped,
			&i.MicrochipNumber,
			&i.MicrochipExpirationDate,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.OwnerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPetGuardian = `-- name: UpsertPetGuardian :execrows
INSERT INTO pet_guardians(pet_id, guardian_id)
    VALUES ($1, $2)
ON CONFLICT (pet_id)
    DO UPDATE SET
        guardian_id = EXCLUDED.guardian_id
`

type UpsertPetGuardianParams struct {
	PetID      pgtype.UUID `db:"PetID" json:"PetID"`
	GuardianID pgtype.UUID `db:"GuardianID" json:"GuardianID"`
}

func (q *Queries) UpsertPetGuardian(ctx context.Context, arg UpsertPetGuardianParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertPetGuardian, arg.PetID, arg.GuardianID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
