// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pets.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPet = `-- name: CreatePet :one
INSERT INTO pets (
    name,
    size,
    kind,
    temperament,
    image_url,
    birth_date,
    owner_id,
    is_active,
    notes
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    TRUE,
    $8
)
RETURNING id, name, size, kind, temperament, image_url, birth_date, owner_id, guardian_id, is_active, notes, created_at, updated_at, deleted_at
`

type CreatePetParams struct {
	Name        string         `db:"Name" json:"Name"`
	Size        PetSize        `db:"Size" json:"Size"`
	Kind        PetKind        `db:"Kind" json:"Kind"`
	Temperament PetTemperament `db:"Temperament" json:"Temperament"`
	ImageUrl    pgtype.Text    `db:"ImageUrl" json:"ImageUrl"`
	BirthDate   pgtype.Date    `db:"BirthDate" json:"BirthDate"`
	OwnerID     pgtype.UUID    `db:"OwnerID" json:"OwnerID"`
	Notes       pgtype.Text    `db:"Notes" json:"Notes"`
}

func (q *Queries) CreatePet(ctx context.Context, arg CreatePetParams) (Pet, error) {
	row := q.db.QueryRow(ctx, createPet,
		arg.Name,
		arg.Size,
		arg.Kind,
		arg.Temperament,
		arg.ImageUrl,
		arg.BirthDate,
		arg.OwnerID,
		arg.Notes,
	)
	var i Pet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Size,
		&i.Kind,
		&i.Temperament,
		&i.ImageUrl,
		&i.BirthDate,
		&i.OwnerID,
		&i.GuardianID,
		&i.IsActive,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deletePet = `-- name: DeletePet :execrows
UPDATE
    pets
SET
    is_active = FALSE,
    deleted_at = now(),
    updated_at = now()
WHERE
    id = $1
    AND deleted_at IS NULL
    AND is_active = TRUE
`

func (q *Queries) DeletePet(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePet, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPetByIDAndCompanyID = `-- name: GetPetByIDAndCompanyID :one
SELECT
    p.id,
    p.owner_id,
    cc.company_id,
    pi.full_name AS owner_name,
    p.name,
    p.size,
    p.kind,
    p.temperament,
    p.image_url,
    p.birth_date,
    p.is_active,
    p.notes,
    p.created_at,
    p.updated_at,
    p.deleted_at
FROM
    pets p
    INNER JOIN clients c ON c.id = p.owner_id
    INNER JOIN company_clients cc ON cc.client_id = c.id
    INNER JOIN people_identifications pi ON pi.person_id = c.person_id
WHERE
    cc.company_id = $1
    AND p.id = $2
    AND cc.is_active = TRUE
    AND c.deleted_at IS NULL
    AND p.deleted_at IS NULL
    AND p.is_active = TRUE
LIMIT 1
`

type GetPetByIDAndCompanyIDParams struct {
	CompanyID pgtype.UUID `db:"CompanyID" json:"CompanyID"`
	ID        pgtype.UUID `db:"ID" json:"ID"`
}

type GetPetByIDAndCompanyIDRow struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	OwnerID     pgtype.UUID        `db:"owner_id" json:"owner_id"`
	CompanyID   pgtype.UUID        `db:"company_id" json:"company_id"`
	OwnerName   string             `db:"owner_name" json:"owner_name"`
	Name        string             `db:"name" json:"name"`
	Size        PetSize            `db:"size" json:"size"`
	Kind        PetKind            `db:"kind" json:"kind"`
	Temperament PetTemperament     `db:"temperament" json:"temperament"`
	ImageUrl    pgtype.Text        `db:"image_url" json:"image_url"`
	BirthDate   pgtype.Date        `db:"birth_date" json:"birth_date"`
	IsActive    bool               `db:"is_active" json:"is_active"`
	Notes       pgtype.Text        `db:"notes" json:"notes"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

func (q *Queries) GetPetByIDAndCompanyID(ctx context.Context, arg GetPetByIDAndCompanyIDParams) (GetPetByIDAndCompanyIDRow, error) {
	row := q.db.QueryRow(ctx, getPetByIDAndCompanyID, arg.CompanyID, arg.ID)
	var i GetPetByIDAndCompanyIDRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.CompanyID,
		&i.OwnerName,
		&i.Name,
		&i.Size,
		&i.Kind,
		&i.Temperament,
		&i.ImageUrl,
		&i.BirthDate,
		&i.IsActive,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listPetsByCompanyID = `-- name: ListPetsByCompanyID :many
SELECT
    p.id,
    p.owner_id,
    cc.company_id,
    pi.full_name AS owner_name,
    p.name,
    p.size,
    p.kind,
    p.temperament,
    p.image_url,
    p.birth_date,
    p.is_active,
    p.notes,
    p.created_at,
    p.updated_at,
    p.deleted_at
FROM
    pets p
    INNER JOIN clients c ON c.id = p.owner_id
    INNER JOIN company_clients cc ON cc.client_id = c.id
    INNER JOIN people_identifications pi ON pi.person_id = c.person_id
WHERE
    cc.company_id = $1
    AND cc.is_active = TRUE
    AND c.deleted_at IS NULL
    AND p.deleted_at IS NULL
    AND p.is_active = TRUE
ORDER BY
    p.name ASC
`

type ListPetsByCompanyIDRow struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	OwnerID     pgtype.UUID        `db:"owner_id" json:"owner_id"`
	CompanyID   pgtype.UUID        `db:"company_id" json:"company_id"`
	OwnerName   string             `db:"owner_name" json:"owner_name"`
	Name        string             `db:"name" json:"name"`
	Size        PetSize            `db:"size" json:"size"`
	Kind        PetKind            `db:"kind" json:"kind"`
	Temperament PetTemperament     `db:"temperament" json:"temperament"`
	ImageUrl    pgtype.Text        `db:"image_url" json:"image_url"`
	BirthDate   pgtype.Date        `db:"birth_date" json:"birth_date"`
	IsActive    bool               `db:"is_active" json:"is_active"`
	Notes       pgtype.Text        `db:"notes" json:"notes"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

func (q *Queries) ListPetsByCompanyID(ctx context.Context, companyid pgtype.UUID) ([]ListPetsByCompanyIDRow, error) {
	rows, err := q.db.Query(ctx, listPetsByCompanyID, companyid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPetsByCompanyIDRow
	for rows.Next() {
		var i ListPetsByCompanyIDRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.CompanyID,
			&i.OwnerName,
			&i.Name,
			&i.Size,
			&i.Kind,
			&i.Temperament,
			&i.ImageUrl,
			&i.BirthDate,
			&i.IsActive,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePet = `-- name: UpdatePet :execrows
UPDATE
    pets
SET
    owner_id = COALESCE($1, owner_id),
    name = COALESCE($2, name),
    size = COALESCE($3, size),
    kind = COALESCE($4, kind),
    temperament = COALESCE($5, temperament),
    image_url = COALESCE($6, image_url),
    birth_date = COALESCE($7, birth_date),
    notes = COALESCE($8, notes),
    updated_at = now()
WHERE
    id = $9
    AND deleted_at IS NULL
    AND is_active = TRUE
`

type UpdatePetParams struct {
	OwnerID     pgtype.UUID        `db:"OwnerID" json:"OwnerID"`
	Name        pgtype.Text        `db:"Name" json:"Name"`
	Size        NullPetSize        `db:"Size" json:"Size"`
	Kind        NullPetKind        `db:"Kind" json:"Kind"`
	Temperament NullPetTemperament `db:"Temperament" json:"Temperament"`
	ImageUrl    pgtype.Text        `db:"ImageUrl" json:"ImageUrl"`
	BirthDate   pgtype.Date        `db:"BirthDate" json:"BirthDate"`
	Notes       pgtype.Text        `db:"Notes" json:"Notes"`
	ID          pgtype.UUID        `db:"ID" json:"ID"`
}

func (q *Queries) UpdatePet(ctx context.Context, arg UpdatePetParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePet,
		arg.OwnerID,
		arg.Name,
		arg.Size,
		arg.Kind,
		arg.Temperament,
		arg.ImageUrl,
		arg.BirthDate,
		arg.Notes,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const validatePetOwnerByCompany = `-- name: ValidatePetOwnerByCompany :one
SELECT
    EXISTS (
        SELECT
            1
        FROM
            company_clients cc
            INNER JOIN clients c ON c.id = cc.client_id
        WHERE
            cc.company_id = $1
            AND cc.client_id = $2
            AND cc.is_active = TRUE
            AND c.deleted_at IS NULL
    ) AS is_valid
`

type ValidatePetOwnerByCompanyParams struct {
	CompanyID pgtype.UUID `db:"CompanyID" json:"CompanyID"`
	OwnerID   pgtype.UUID `db:"OwnerID" json:"OwnerID"`
}

func (q *Queries) ValidatePetOwnerByCompany(ctx context.Context, arg ValidatePetOwnerByCompanyParams) (bool, error) {
	row := q.db.QueryRow(ctx, validatePetOwnerByCompany, arg.CompanyID, arg.OwnerID)
	var is_valid bool
	err := row.Scan(&is_valid)
	return is_valid, err
}
