// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plan_modules.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bulkInsertPlanModules = `-- name: BulkInsertPlanModules :execrows
INSERT INTO plan_modules(plan_id, module_id)
SELECT
    $1,
    unnest($2::uuid[])
`

type BulkInsertPlanModulesParams struct {
	PlanID    pgtype.UUID   `db:"PlanID" json:"PlanID"`
	ModuleIDs []pgtype.UUID `db:"ModuleIDs" json:"ModuleIDs"`
}

func (q *Queries) BulkInsertPlanModules(ctx context.Context, arg BulkInsertPlanModulesParams) (int64, error) {
	result, err := q.db.Exec(ctx, bulkInsertPlanModules, arg.PlanID, arg.ModuleIDs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePlanModule = `-- name: DeletePlanModule :execrows
DELETE FROM plan_modules
WHERE plan_id = $1
    AND module_id = $2
`

type DeletePlanModuleParams struct {
	PlanID   pgtype.UUID `db:"PlanID" json:"PlanID"`
	ModuleID pgtype.UUID `db:"ModuleID" json:"ModuleID"`
}

func (q *Queries) DeletePlanModule(ctx context.Context, arg DeletePlanModuleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePlanModule, arg.PlanID, arg.ModuleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertPlanModule = `-- name: InsertPlanModule :execrows
INSERT INTO plan_modules(plan_id, module_id)
    VALUES ($1, $2)
`

type InsertPlanModuleParams struct {
	PlanID   pgtype.UUID `db:"PlanID" json:"PlanID"`
	ModuleID pgtype.UUID `db:"ModuleID" json:"ModuleID"`
}

func (q *Queries) InsertPlanModule(ctx context.Context, arg InsertPlanModuleParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertPlanModule, arg.PlanID, arg.ModuleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listModulesByPlanID = `-- name: ListModulesByPlanID :many
SELECT
    m.id,
    m.code,
    m."name",
    m.description,
    m.created_at,
    m.updated_at,
    m.deleted_at
FROM
    plan_modules pm
    JOIN modules m ON pm.module_id = m.id
WHERE
    pm.plan_id = $1
    AND m.deleted_at IS NULL
ORDER BY
    m.code ASC
LIMIT $3
OFFSET $2
`

type ListModulesByPlanIDParams struct {
	PlanID pgtype.UUID `db:"PlanID" json:"PlanID"`
	Offset int32       `db:"Offset" json:"Offset"`
	Limit  int32       `db:"Limit" json:"Limit"`
}

type ListModulesByPlanIDRow struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Code        string             `db:"code" json:"code"`
	Name        string             `db:"name" json:"name"`
	Description string             `db:"description" json:"description"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

func (q *Queries) ListModulesByPlanID(ctx context.Context, arg ListModulesByPlanIDParams) ([]ListModulesByPlanIDRow, error) {
	rows, err := q.db.Query(ctx, listModulesByPlanID, arg.PlanID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListModulesByPlanIDRow
	for rows.Next() {
		var i ListModulesByPlanIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlansByModuleID = `-- name: ListPlansByModuleID :many
SELECT
    p.id,
    p.plan_type_id,
    p.name,
    p.description,
    p.package,
    p.price,
    p.billing_cycle_days,
    p.max_users,
    p.is_active,
    p.image_url,
    p.created_at,
    p.updated_at,
    p.deleted_at
FROM
    plan_modules pm
    JOIN plans p ON pm.plan_id = p.id
WHERE
    pm.module_id = $1
    AND p.deleted_at IS NULL
ORDER BY
    p.created_at DESC
LIMIT $3
OFFSET $2
`

type ListPlansByModuleIDParams struct {
	ModuleID pgtype.UUID `db:"ModuleID" json:"ModuleID"`
	Offset   int32       `db:"Offset" json:"Offset"`
	Limit    int32       `db:"Limit" json:"Limit"`
}

func (q *Queries) ListPlansByModuleID(ctx context.Context, arg ListPlansByModuleIDParams) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listPlansByModuleID, arg.ModuleID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plan
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.PlanTypeID,
			&i.Name,
			&i.Description,
			&i.Package,
			&i.Price,
			&i.BillingCycleDays,
			&i.MaxUsers,
			&i.IsActive,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
