// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plans.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCurrentPlanByCompanyID = `-- name: GetCurrentPlanByCompanyID :one
SELECT
    p.id,
    p.plan_type_id,
    p.name,
    p.description,
    p.package,
    p.price,
    p.billing_cycle_days,
    p.max_users,
    p.is_active,
    p.image_url,
    p.created_at,
    p.updated_at,
    p.deleted_at
FROM
    company_subscriptions cs
    INNER JOIN plans p ON p.id = cs.plan_id
WHERE
    cs.company_id = $1
    AND cs.is_active = TRUE
    AND cs.canceled_at IS NULL
    AND cs.started_at <= now()
    AND cs.expires_at > now()
    AND p.is_active = TRUE
    AND p.deleted_at IS NULL
ORDER BY
    cs.started_at DESC
LIMIT 1
`

func (q *Queries) GetCurrentPlanByCompanyID(ctx context.Context, companyid pgtype.UUID) (Plan, error) {
	row := q.db.QueryRow(ctx, getCurrentPlanByCompanyID, companyid)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.PlanTypeID,
		&i.Name,
		&i.Description,
		&i.Package,
		&i.Price,
		&i.BillingCycleDays,
		&i.MaxUsers,
		&i.IsActive,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPlanByID = `-- name: GetPlanByID :one
SELECT
    p.id,
    p.plan_type_id,
    p.name,
    p.description,
    p.package,
    p.price,
    p.billing_cycle_days,
    p.max_users,
    p.is_active,
    p.image_url,
    p.created_at,
    p.updated_at,
    p.deleted_at
FROM
    plans p
WHERE
    p.id = $1
    AND p.deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetPlanByID(ctx context.Context, id pgtype.UUID) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlanByID, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.PlanTypeID,
		&i.Name,
		&i.Description,
		&i.Package,
		&i.Price,
		&i.BillingCycleDays,
		&i.MaxUsers,
		&i.IsActive,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertPlan = `-- name: InsertPlan :one
INSERT INTO plans(plan_type_id, name, description, package, price, billing_cycle_days, max_users, is_active, image_url)
    VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING
    id, plan_type_id, name, description, package, price, billing_cycle_days, max_users, is_active, image_url, created_at, updated_at, deleted_at
`

type InsertPlanParams struct {
	PlanTypeID       pgtype.UUID    `db:"plan_type_id" json:"plan_type_id"`
	Name             string         `db:"name" json:"name"`
	Description      string         `db:"description" json:"description"`
	Package          ModulePackage  `db:"package" json:"package"`
	Price            pgtype.Numeric `db:"price" json:"price"`
	BillingCycleDays int32          `db:"billing_cycle_days" json:"billing_cycle_days"`
	MaxUsers         pgtype.Int4    `db:"max_users" json:"max_users"`
	IsActive         bool           `db:"is_active" json:"is_active"`
	ImageUrl         pgtype.Text    `db:"image_url" json:"image_url"`
}

func (q *Queries) InsertPlan(ctx context.Context, arg InsertPlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, insertPlan,
		arg.PlanTypeID,
		arg.Name,
		arg.Description,
		arg.Package,
		arg.Price,
		arg.BillingCycleDays,
		arg.MaxUsers,
		arg.IsActive,
		arg.ImageUrl,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.PlanTypeID,
		&i.Name,
		&i.Description,
		&i.Package,
		&i.Price,
		&i.BillingCycleDays,
		&i.MaxUsers,
		&i.IsActive,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertPlanType = `-- name: InsertPlanType :one
INSERT INTO plan_types(name, description)
    VALUES ($1, $2)
RETURNING
    id, name, description, created_at, updated_at, deleted_at
`

type InsertPlanTypeParams struct {
	Name        string      `db:"name" json:"name"`
	Description pgtype.Text `db:"description" json:"description"`
}

func (q *Queries) InsertPlanType(ctx context.Context, arg InsertPlanTypeParams) (PlanType, error) {
	row := q.db.QueryRow(ctx, insertPlanType, arg.Name, arg.Description)
	var i PlanType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listPlanTypes = `-- name: ListPlanTypes :many
SELECT
    pt.id,
    pt.name,
    pt.description,
    pt.created_at,
    pt.updated_at,
    pt.deleted_at
FROM
    plan_types pt
WHERE
    pt.deleted_at IS NULL
ORDER BY
    pt.created_at ASC
`

func (q *Queries) ListPlanTypes(ctx context.Context) ([]PlanType, error) {
	rows, err := q.db.Query(ctx, listPlanTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlanType
	for rows.Next() {
		var i PlanType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlans = `-- name: ListPlans :many
SELECT
    p.id,
    p.plan_type_id,
    p.name,
    p.description,
    p.package,
    p.price,
    p.billing_cycle_days,
    p.max_users,
    p.is_active,
    p.image_url,
    p.created_at,
    p.updated_at,
    p.deleted_at
FROM
    plans p
WHERE
    p.deleted_at IS NULL
ORDER BY
    p.created_at DESC
`

func (q *Queries) ListPlans(ctx context.Context) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plan
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.PlanTypeID,
			&i.Name,
			&i.Description,
			&i.Package,
			&i.Price,
			&i.BillingCycleDays,
			&i.MaxUsers,
			&i.IsActive,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlansByPackage = `-- name: ListPlansByPackage :many
SELECT
    p.id,
    p.plan_type_id,
    p.name,
    p.description,
    p.package,
    p.price,
    p.billing_cycle_days,
    p.max_users,
    p.is_active,
    p.image_url,
    p.created_at,
    p.updated_at,
    p.deleted_at
FROM
    plans p
WHERE
    p.deleted_at IS NULL
    AND p.package = $1
ORDER BY
    p.created_at DESC
`

func (q *Queries) ListPlansByPackage(ctx context.Context, package_ ModulePackage) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listPlansByPackage, package_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plan
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.PlanTypeID,
			&i.Name,
			&i.Description,
			&i.Package,
			&i.Price,
			&i.BillingCycleDays,
			&i.MaxUsers,
			&i.IsActive,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlan = `-- name: UpdatePlan :execrows
UPDATE
    plans
SET
    plan_type_id = coalesce($1, plan_type_id),
    name = coalesce($2, name),
    description = coalesce($3, description),
    package = coalesce($4, package),
    price = coalesce($5, price),
    billing_cycle_days = coalesce($6, billing_cycle_days),
    max_users = coalesce($7, max_users),
    is_active = coalesce($8, is_active),
    image_url = coalesce($9, image_url),
    updated_at = now()
WHERE
    id = $10
    AND deleted_at IS NULL
`

type UpdatePlanParams struct {
	PlanTypeID       pgtype.UUID       `db:"PlanTypeID" json:"PlanTypeID"`
	Name             pgtype.Text       `db:"Name" json:"Name"`
	Description      pgtype.Text       `db:"Description" json:"Description"`
	Package          NullModulePackage `db:"Package" json:"Package"`
	Price            pgtype.Numeric    `db:"Price" json:"Price"`
	BillingCycleDays pgtype.Int4       `db:"BillingCycleDays" json:"BillingCycleDays"`
	MaxUsers         pgtype.Int4       `db:"MaxUsers" json:"MaxUsers"`
	IsActive         pgtype.Bool       `db:"IsActive" json:"IsActive"`
	ImageUrl         pgtype.Text       `db:"ImageUrl" json:"ImageUrl"`
	ID               pgtype.UUID       `db:"ID" json:"ID"`
}

func (q *Queries) UpdatePlan(ctx context.Context, arg UpdatePlanParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePlan,
		arg.PlanTypeID,
		arg.Name,
		arg.Description,
		arg.Package,
		arg.Price,
		arg.BillingCycleDays,
		arg.MaxUsers,
		arg.IsActive,
		arg.ImageUrl,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
