// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteProduct = `-- name: DeleteProduct :one
UPDATE
    products
SET
    deleted_at = now(),
    updated_at = now()
WHERE
    id = $1
    AND deleted_at IS NULL
RETURNING
    id, name, batch_number, description, image_url, expiration_date, quantity, created_at, updated_at, deleted_at
`

func (q *Queries) DeleteProduct(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, deleteProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BatchNumber,
		&i.Description,
		&i.ImageUrl,
		&i.ExpirationDate,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT
    p.id,
    p.name,
    p.batch_number,
    p.description,
    p.image_url,
    p.expiration_date,
    p.quantity,
    p.created_at,
    p.updated_at,
    p.deleted_at
FROM
    products p
WHERE
    p.id = $1
    AND p.deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetProductByID(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BatchNumber,
		&i.Description,
		&i.ImageUrl,
		&i.ExpirationDate,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertProduct = `-- name: InsertProduct :one
INSERT INTO products(name, batch_number, description, image_url, expiration_date, quantity)
    VALUES ($1, $2, $3, $4, $5, $6)
RETURNING
    id, name, batch_number, description, image_url, expiration_date, quantity, created_at, updated_at, deleted_at
`

type InsertProductParams struct {
	Name           string      `db:"Name" json:"Name"`
	BatchNumber    pgtype.Text `db:"BatchNumber" json:"BatchNumber"`
	Description    pgtype.Text `db:"Description" json:"Description"`
	ImageURL       pgtype.Text `db:"ImageURL" json:"ImageURL"`
	ExpirationDate pgtype.Date `db:"ExpirationDate" json:"ExpirationDate"`
	Quantity       pgtype.Int4 `db:"Quantity" json:"Quantity"`
}

func (q *Queries) InsertProduct(ctx context.Context, arg InsertProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, insertProduct,
		arg.Name,
		arg.BatchNumber,
		arg.Description,
		arg.ImageURL,
		arg.ExpirationDate,
		arg.Quantity,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BatchNumber,
		&i.Description,
		&i.ImageUrl,
		&i.ExpirationDate,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT
    p.id,
    p.name,
    p.batch_number,
    p.description,
    p.image_url,
    p.expiration_date,
    p.quantity,
    p.created_at,
    p.updated_at,
    p.deleted_at
FROM
    products p
WHERE
    p.deleted_at IS NULL
ORDER BY
    p.created_at DESC
LIMIT $2
OFFSET $1
`

type ListProductsParams struct {
	Offset int32 `db:"Offset" json:"Offset"`
	Limit  int32 `db:"Limit" json:"Limit"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BatchNumber,
			&i.Description,
			&i.ImageUrl,
			&i.ExpirationDate,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE
    products
SET
    name = coalesce($1, name),
    batch_number = coalesce($2, batch_number),
    description = coalesce($3, description),
    image_url = coalesce($4, image_url),
    expiration_date = coalesce($5, expiration_date),
    quantity = coalesce($6, quantity),
    updated_at = now()
WHERE
    id = $7
    AND deleted_at IS NULL
RETURNING
    id, name, batch_number, description, image_url, expiration_date, quantity, created_at, updated_at, deleted_at
`

type UpdateProductParams struct {
	Name           pgtype.Text `db:"Name" json:"Name"`
	BatchNumber    pgtype.Text `db:"BatchNumber" json:"BatchNumber"`
	Description    pgtype.Text `db:"Description" json:"Description"`
	ImageURL       pgtype.Text `db:"ImageURL" json:"ImageURL"`
	ExpirationDate pgtype.Date `db:"ExpirationDate" json:"ExpirationDate"`
	Quantity       pgtype.Int4 `db:"Quantity" json:"Quantity"`
	ID             pgtype.UUID `db:"ID" json:"ID"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.Name,
		arg.BatchNumber,
		arg.Description,
		arg.ImageURL,
		arg.ExpirationDate,
		arg.Quantity,
		arg.ID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BatchNumber,
		&i.Description,
		&i.ImageUrl,
		&i.ExpirationDate,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateProductQuantity = `-- name: UpdateProductQuantity :one
UPDATE
    products
SET
    quantity = $1,
    updated_at = now()
WHERE
    id = $2
    AND deleted_at IS NULL
RETURNING
    id, name, batch_number, description, image_url, expiration_date, quantity, created_at, updated_at, deleted_at
`

type UpdateProductQuantityParams struct {
	Quantity int32       `db:"Quantity" json:"Quantity"`
	ID       pgtype.UUID `db:"ID" json:"ID"`
}

func (q *Queries) UpdateProductQuantity(ctx context.Context, arg UpdateProductQuantityParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProductQuantity, arg.Quantity, arg.ID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BatchNumber,
		&i.Description,
		&i.ImageUrl,
		&i.ExpirationDate,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
