// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: schedules.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSchedule = `-- name: CreateSchedule :one
INSERT INTO schedules (
    company_id,
    client_id,
    pet_id,
    scheduled_at,
    estimated_end,
    notes,
    created_by
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, company_id, client_id, pet_id, scheduled_at, estimated_end, notes, created_by, created_at, updated_at, deleted_at
`

type CreateScheduleParams struct {
	CompanyID    pgtype.UUID        `db:"CompanyID" json:"CompanyID"`
	ClientID     pgtype.UUID        `db:"ClientID" json:"ClientID"`
	PetID        pgtype.UUID        `db:"PetID" json:"PetID"`
	ScheduledAt  pgtype.Timestamptz `db:"ScheduledAt" json:"ScheduledAt"`
	EstimatedEnd pgtype.Timestamptz `db:"EstimatedEnd" json:"EstimatedEnd"`
	Notes        pgtype.Text        `db:"Notes" json:"Notes"`
	CreatedBy    pgtype.UUID        `db:"CreatedBy" json:"CreatedBy"`
}

func (q *Queries) CreateSchedule(ctx context.Context, arg CreateScheduleParams) (Schedule, error) {
	row := q.db.QueryRow(ctx, createSchedule,
		arg.CompanyID,
		arg.ClientID,
		arg.PetID,
		arg.ScheduledAt,
		arg.EstimatedEnd,
		arg.Notes,
		arg.CreatedBy,
	)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ClientID,
		&i.PetID,
		&i.ScheduledAt,
		&i.EstimatedEnd,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteSchedule = `-- name: DeleteSchedule :execrows
UPDATE
    schedules
SET
    deleted_at = now(),
    updated_at = now()
WHERE
    id = $1
    AND company_id = $2
    AND deleted_at IS NULL
`

type DeleteScheduleParams struct {
	ID        pgtype.UUID `db:"ID" json:"ID"`
	CompanyID pgtype.UUID `db:"CompanyID" json:"CompanyID"`
}

func (q *Queries) DeleteSchedule(ctx context.Context, arg DeleteScheduleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSchedule, arg.ID, arg.CompanyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteScheduleServicesByScheduleID = `-- name: DeleteScheduleServicesByScheduleID :execrows
DELETE FROM schedule_services
WHERE
    schedule_id = $1
`

func (q *Queries) DeleteScheduleServicesByScheduleID(ctx context.Context, scheduleid pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteScheduleServicesByScheduleID, scheduleid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getScheduleByIDAndCompanyID = `-- name: GetScheduleByIDAndCompanyID :one
SELECT
    s.id,
    s.company_id,
    s.client_id,
    s.pet_id,
    pi.full_name AS client_name,
    p.name AS pet_name,
    COALESCE(service_context.service_ids, '{}'::text[]) AS service_ids,
    COALESCE(service_context.service_titles, '{}'::text[]) AS service_titles,
    s.scheduled_at,
    s.estimated_end,
    s.notes,
    s.created_by,
    s.created_at,
    s.updated_at,
    s.deleted_at,
    COALESCE(ssh_current.status, 'waiting'::schedule_status) AS current_status
FROM
    schedules s
    INNER JOIN clients c ON c.id = s.client_id
    INNER JOIN people_identifications pi ON pi.person_id = c.person_id
    INNER JOIN pets p ON p.id = s.pet_id
    LEFT JOIN LATERAL (
        SELECT
            ssh.status
        FROM
            schedule_status_history ssh
        WHERE
            ssh.schedule_id = s.id
        ORDER BY
            ssh.changed_at DESC
        LIMIT 1
    ) ssh_current ON TRUE
    LEFT JOIN LATERAL (
        SELECT
            array_agg(ss.service_id::text ORDER BY svc.title) AS service_ids,
            array_agg(svc.title ORDER BY svc.title) AS service_titles
        FROM
            schedule_services ss
            INNER JOIN services svc ON svc.id = ss.service_id
        WHERE
            ss.schedule_id = s.id
            AND svc.deleted_at IS NULL
    ) service_context ON TRUE
WHERE
    s.id = $1
    AND s.company_id = $2
    AND s.deleted_at IS NULL
LIMIT 1
`

type GetScheduleByIDAndCompanyIDParams struct {
	ID        pgtype.UUID `db:"ID" json:"ID"`
	CompanyID pgtype.UUID `db:"CompanyID" json:"CompanyID"`
}

type GetScheduleByIDAndCompanyIDRow struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	CompanyID     pgtype.UUID        `db:"company_id" json:"company_id"`
	ClientID      pgtype.UUID        `db:"client_id" json:"client_id"`
	PetID         pgtype.UUID        `db:"pet_id" json:"pet_id"`
	ClientName    string             `db:"client_name" json:"client_name"`
	PetName       string             `db:"pet_name" json:"pet_name"`
	ServiceIds    interface{}        `db:"service_ids" json:"service_ids"`
	ServiceTitles interface{}        `db:"service_titles" json:"service_titles"`
	ScheduledAt   pgtype.Timestamptz `db:"scheduled_at" json:"scheduled_at"`
	EstimatedEnd  pgtype.Timestamptz `db:"estimated_end" json:"estimated_end"`
	Notes         pgtype.Text        `db:"notes" json:"notes"`
	CreatedBy     pgtype.UUID        `db:"created_by" json:"created_by"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	CurrentStatus ScheduleStatus     `db:"current_status" json:"current_status"`
}

func (q *Queries) GetScheduleByIDAndCompanyID(ctx context.Context, arg GetScheduleByIDAndCompanyIDParams) (GetScheduleByIDAndCompanyIDRow, error) {
	row := q.db.QueryRow(ctx, getScheduleByIDAndCompanyID, arg.ID, arg.CompanyID)
	var i GetScheduleByIDAndCompanyIDRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ClientID,
		&i.PetID,
		&i.ClientName,
		&i.PetName,
		&i.ServiceIds,
		&i.ServiceTitles,
		&i.ScheduledAt,
		&i.EstimatedEnd,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CurrentStatus,
	)
	return i, err
}

const insertScheduleService = `-- name: InsertScheduleService :one
INSERT INTO schedule_services (
    schedule_id,
    service_id
)
VALUES (
    $1,
    $2
)
RETURNING id, schedule_id, service_id, created_at
`

type InsertScheduleServiceParams struct {
	ScheduleID pgtype.UUID `db:"ScheduleID" json:"ScheduleID"`
	ServiceID  pgtype.UUID `db:"ServiceID" json:"ServiceID"`
}

func (q *Queries) InsertScheduleService(ctx context.Context, arg InsertScheduleServiceParams) (ScheduleService, error) {
	row := q.db.QueryRow(ctx, insertScheduleService, arg.ScheduleID, arg.ServiceID)
	var i ScheduleService
	err := row.Scan(
		&i.ID,
		&i.ScheduleID,
		&i.ServiceID,
		&i.CreatedAt,
	)
	return i, err
}

const insertScheduleStatusHistory = `-- name: InsertScheduleStatusHistory :one
INSERT INTO schedule_status_history (
    schedule_id,
    status,
    changed_by,
    notes
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, schedule_id, status, changed_at, changed_by, notes
`

type InsertScheduleStatusHistoryParams struct {
	ScheduleID pgtype.UUID    `db:"ScheduleID" json:"ScheduleID"`
	Status     ScheduleStatus `db:"Status" json:"Status"`
	ChangedBy  pgtype.UUID    `db:"ChangedBy" json:"ChangedBy"`
	Notes      pgtype.Text    `db:"Notes" json:"Notes"`
}

func (q *Queries) InsertScheduleStatusHistory(ctx context.Context, arg InsertScheduleStatusHistoryParams) (ScheduleStatusHistory, error) {
	row := q.db.QueryRow(ctx, insertScheduleStatusHistory,
		arg.ScheduleID,
		arg.Status,
		arg.ChangedBy,
		arg.Notes,
	)
	var i ScheduleStatusHistory
	err := row.Scan(
		&i.ID,
		&i.ScheduleID,
		&i.Status,
		&i.ChangedAt,
		&i.ChangedBy,
		&i.Notes,
	)
	return i, err
}

const listScheduleStatusHistoryByScheduleID = `-- name: ListScheduleStatusHistoryByScheduleID :many
SELECT
    ssh.id,
    ssh.schedule_id,
    ssh.status,
    ssh.changed_at,
    ssh.changed_by,
    ssh.notes
FROM
    schedule_status_history ssh
    INNER JOIN schedules s ON s.id = ssh.schedule_id
WHERE
    ssh.schedule_id = $1
    AND s.company_id = $2
ORDER BY
    ssh.changed_at DESC
`

type ListScheduleStatusHistoryByScheduleIDParams struct {
	ScheduleID pgtype.UUID `db:"ScheduleID" json:"ScheduleID"`
	CompanyID  pgtype.UUID `db:"CompanyID" json:"CompanyID"`
}

func (q *Queries) ListScheduleStatusHistoryByScheduleID(ctx context.Context, arg ListScheduleStatusHistoryByScheduleIDParams) ([]ScheduleStatusHistory, error) {
	rows, err := q.db.Query(ctx, listScheduleStatusHistoryByScheduleID, arg.ScheduleID, arg.CompanyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduleStatusHistory
	for rows.Next() {
		var i ScheduleStatusHistory
		if err := rows.Scan(
			&i.ID,
			&i.ScheduleID,
			&i.Status,
			&i.ChangedAt,
			&i.ChangedBy,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedulesByCompanyID = `-- name: ListSchedulesByCompanyID :many
SELECT
    s.id,
    s.company_id,
    s.client_id,
    s.pet_id,
    pi.full_name AS client_name,
    p.name AS pet_name,
    COALESCE(service_context.service_ids, '{}'::text[]) AS service_ids,
    COALESCE(service_context.service_titles, '{}'::text[]) AS service_titles,
    s.scheduled_at,
    s.estimated_end,
    s.notes,
    s.created_by,
    s.created_at,
    s.updated_at,
    s.deleted_at,
    COALESCE(ssh_current.status, 'waiting'::schedule_status) AS current_status
FROM
    schedules s
    INNER JOIN clients c ON c.id = s.client_id
    INNER JOIN people_identifications pi ON pi.person_id = c.person_id
    INNER JOIN pets p ON p.id = s.pet_id
    LEFT JOIN LATERAL (
        SELECT
            ssh.status
        FROM
            schedule_status_history ssh
        WHERE
            ssh.schedule_id = s.id
        ORDER BY
            ssh.changed_at DESC
        LIMIT 1
    ) ssh_current ON TRUE
    LEFT JOIN LATERAL (
        SELECT
            array_agg(ss.service_id::text ORDER BY svc.title) AS service_ids,
            array_agg(svc.title ORDER BY svc.title) AS service_titles
        FROM
            schedule_services ss
            INNER JOIN services svc ON svc.id = ss.service_id
        WHERE
            ss.schedule_id = s.id
            AND svc.deleted_at IS NULL
    ) service_context ON TRUE
WHERE
    s.company_id = $1
    AND s.deleted_at IS NULL
ORDER BY
    s.scheduled_at ASC
`

type ListSchedulesByCompanyIDRow struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	CompanyID     pgtype.UUID        `db:"company_id" json:"company_id"`
	ClientID      pgtype.UUID        `db:"client_id" json:"client_id"`
	PetID         pgtype.UUID        `db:"pet_id" json:"pet_id"`
	ClientName    string             `db:"client_name" json:"client_name"`
	PetName       string             `db:"pet_name" json:"pet_name"`
	ServiceIds    interface{}        `db:"service_ids" json:"service_ids"`
	ServiceTitles interface{}        `db:"service_titles" json:"service_titles"`
	ScheduledAt   pgtype.Timestamptz `db:"scheduled_at" json:"scheduled_at"`
	EstimatedEnd  pgtype.Timestamptz `db:"estimated_end" json:"estimated_end"`
	Notes         pgtype.Text        `db:"notes" json:"notes"`
	CreatedBy     pgtype.UUID        `db:"created_by" json:"created_by"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	CurrentStatus ScheduleStatus     `db:"current_status" json:"current_status"`
}

func (q *Queries) ListSchedulesByCompanyID(ctx context.Context, companyid pgtype.UUID) ([]ListSchedulesByCompanyIDRow, error) {
	rows, err := q.db.Query(ctx, listSchedulesByCompanyID, companyid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSchedulesByCompanyIDRow
	for rows.Next() {
		var i ListSchedulesByCompanyIDRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.ClientID,
			&i.PetID,
			&i.ClientName,
			&i.PetName,
			&i.ServiceIds,
			&i.ServiceTitles,
			&i.ScheduledAt,
			&i.EstimatedEnd,
			&i.Notes,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CurrentStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSchedule = `-- name: UpdateSchedule :execrows
UPDATE
    schedules
SET
    client_id = COALESCE($1, client_id),
    pet_id = COALESCE($2, pet_id),
    scheduled_at = COALESCE($3, scheduled_at),
    estimated_end = COALESCE($4, estimated_end),
    notes = COALESCE($5, notes),
    updated_at = now()
WHERE
    id = $6
    AND company_id = $7
    AND deleted_at IS NULL
`

type UpdateScheduleParams struct {
	ClientID     pgtype.UUID        `db:"ClientID" json:"ClientID"`
	PetID        pgtype.UUID        `db:"PetID" json:"PetID"`
	ScheduledAt  pgtype.Timestamptz `db:"ScheduledAt" json:"ScheduledAt"`
	EstimatedEnd pgtype.Timestamptz `db:"EstimatedEnd" json:"EstimatedEnd"`
	Notes        pgtype.Text        `db:"Notes" json:"Notes"`
	ID           pgtype.UUID        `db:"ID" json:"ID"`
	CompanyID    pgtype.UUID        `db:"CompanyID" json:"CompanyID"`
}

func (q *Queries) UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSchedule,
		arg.ClientID,
		arg.PetID,
		arg.ScheduledAt,
		arg.EstimatedEnd,
		arg.Notes,
		arg.ID,
		arg.CompanyID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const validateScheduleOwnership = `-- name: ValidateScheduleOwnership :one
SELECT
    EXISTS (
        SELECT
            1
        FROM
            company_clients cc
            INNER JOIN clients c ON c.id = cc.client_id
            INNER JOIN pets p ON p.id = $1
        WHERE
            cc.company_id = $2
            AND cc.client_id = $3
            AND cc.client_id = p.owner_id
            AND cc.is_active = TRUE
            AND c.deleted_at IS NULL
            AND p.deleted_at IS NULL
    ) AS is_valid
`

type ValidateScheduleOwnershipParams struct {
	PetID     pgtype.UUID `db:"PetID" json:"PetID"`
	CompanyID pgtype.UUID `db:"CompanyID" json:"CompanyID"`
	ClientID  pgtype.UUID `db:"ClientID" json:"ClientID"`
}

func (q *Queries) ValidateScheduleOwnership(ctx context.Context, arg ValidateScheduleOwnershipParams) (bool, error) {
	row := q.db.QueryRow(ctx, validateScheduleOwnership, arg.PetID, arg.CompanyID, arg.ClientID)
	var is_valid bool
	err := row.Scan(&is_valid)
	return is_valid, err
}
