// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: schedule_payments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSchedulePayment = `-- name: DeleteSchedulePayment :execrows
DELETE FROM schedule_payments
WHERE schedule_id = $1
`

func (q *Queries) DeleteSchedulePayment(ctx context.Context, scheduleid pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSchedulePayment, scheduleid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSchedulePaymentByScheduleID = `-- name: GetSchedulePaymentByScheduleID :one
SELECT
    sp.id,
    sp.schedule_id,
    sp.payment_method_one,
    sp.payment_method_two,
    sp.payment_method_three,
    sp.payment_date,
    sp.gross_value,
    sp.discount_value,
    sp.net_value,
    sp.amount_paid,
    sp.amount_remaining,
    sp.notes,
    sp.created_at,
    sp.updated_at
FROM
    schedule_payments sp
WHERE
    sp.schedule_id = $1
LIMIT 1
`

func (q *Queries) GetSchedulePaymentByScheduleID(ctx context.Context, scheduleid pgtype.UUID) (SchedulePayment, error) {
	row := q.db.QueryRow(ctx, getSchedulePaymentByScheduleID, scheduleid)
	var i SchedulePayment
	err := row.Scan(
		&i.ID,
		&i.ScheduleID,
		&i.PaymentMethodOne,
		&i.PaymentMethodTwo,
		&i.PaymentMethodThree,
		&i.PaymentDate,
		&i.GrossValue,
		&i.DiscountValue,
		&i.NetValue,
		&i.AmountPaid,
		&i.AmountRemaining,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSchedulePayment = `-- name: InsertSchedulePayment :one
INSERT INTO schedule_payments(schedule_id, payment_method_one, payment_method_two, payment_method_three, payment_date, gross_value, discount_value, net_value, amount_paid, notes)
    VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING
    id, schedule_id, payment_method_one, payment_method_two, payment_method_three, payment_date, gross_value, discount_value, net_value, amount_paid, amount_remaining, notes, created_at, updated_at
`

type InsertSchedulePaymentParams struct {
	ScheduleID         pgtype.UUID        `db:"ScheduleID" json:"ScheduleID"`
	PaymentMethodOne   PaymentMethod      `db:"PaymentMethodOne" json:"PaymentMethodOne"`
	PaymentMethodTwo   NullPaymentMethod  `db:"PaymentMethodTwo" json:"PaymentMethodTwo"`
	PaymentMethodThree NullPaymentMethod  `db:"PaymentMethodThree" json:"PaymentMethodThree"`
	PaymentDate        pgtype.Timestamptz `db:"PaymentDate" json:"PaymentDate"`
	GrossValue         pgtype.Numeric     `db:"GrossValue" json:"GrossValue"`
	DiscountValue      pgtype.Numeric     `db:"DiscountValue" json:"DiscountValue"`
	NetValue           pgtype.Numeric     `db:"NetValue" json:"NetValue"`
	AmountPaid         pgtype.Numeric     `db:"AmountPaid" json:"AmountPaid"`
	Notes              pgtype.Text        `db:"Notes" json:"Notes"`
}

func (q *Queries) InsertSchedulePayment(ctx context.Context, arg InsertSchedulePaymentParams) (SchedulePayment, error) {
	row := q.db.QueryRow(ctx, insertSchedulePayment,
		arg.ScheduleID,
		arg.PaymentMethodOne,
		arg.PaymentMethodTwo,
		arg.PaymentMethodThree,
		arg.PaymentDate,
		arg.GrossValue,
		arg.DiscountValue,
		arg.NetValue,
		arg.AmountPaid,
		arg.Notes,
	)
	var i SchedulePayment
	err := row.Scan(
		&i.ID,
		&i.ScheduleID,
		&i.PaymentMethodOne,
		&i.PaymentMethodTwo,
		&i.PaymentMethodThree,
		&i.PaymentDate,
		&i.GrossValue,
		&i.DiscountValue,
		&i.NetValue,
		&i.AmountPaid,
		&i.AmountRemaining,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSchedulePaymentsByCompanyID = `-- name: ListSchedulePaymentsByCompanyID :many
SELECT
    sp.id,
    sp.schedule_id,
    sp.payment_method_one,
    sp.payment_method_two,
    sp.payment_method_three,
    sp.payment_date,
    sp.gross_value,
    sp.discount_value,
    sp.net_value,
    sp.amount_paid,
    sp.amount_remaining,
    sp.notes,
    sp.created_at,
    sp.updated_at,
    s.scheduled_at,
    s.client_id,
    s.pet_id
FROM
    schedule_payments sp
    JOIN schedules s ON sp.schedule_id = s.id
WHERE
    s.company_id = $1
    AND s.deleted_at IS NULL
ORDER BY
    sp.payment_date DESC
LIMIT $3
OFFSET $2
`

type ListSchedulePaymentsByCompanyIDParams struct {
	CompanyID pgtype.UUID `db:"CompanyID" json:"CompanyID"`
	Offset    int32       `db:"Offset" json:"Offset"`
	Limit     int32       `db:"Limit" json:"Limit"`
}

type ListSchedulePaymentsByCompanyIDRow struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	ScheduleID         pgtype.UUID        `db:"schedule_id" json:"schedule_id"`
	PaymentMethodOne   PaymentMethod      `db:"payment_method_one" json:"payment_method_one"`
	PaymentMethodTwo   NullPaymentMethod  `db:"payment_method_two" json:"payment_method_two"`
	PaymentMethodThree NullPaymentMethod  `db:"payment_method_three" json:"payment_method_three"`
	PaymentDate        pgtype.Timestamptz `db:"payment_date" json:"payment_date"`
	GrossValue         pgtype.Numeric     `db:"gross_value" json:"gross_value"`
	DiscountValue      pgtype.Numeric     `db:"discount_value" json:"discount_value"`
	NetValue           pgtype.Numeric     `db:"net_value" json:"net_value"`
	AmountPaid         pgtype.Numeric     `db:"amount_paid" json:"amount_paid"`
	AmountRemaining    pgtype.Numeric     `db:"amount_remaining" json:"amount_remaining"`
	Notes              pgtype.Text        `db:"notes" json:"notes"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ScheduledAt        pgtype.Timestamptz `db:"scheduled_at" json:"scheduled_at"`
	ClientID           pgtype.UUID        `db:"client_id" json:"client_id"`
	PetID              pgtype.UUID        `db:"pet_id" json:"pet_id"`
}

func (q *Queries) ListSchedulePaymentsByCompanyID(ctx context.Context, arg ListSchedulePaymentsByCompanyIDParams) ([]ListSchedulePaymentsByCompanyIDRow, error) {
	rows, err := q.db.Query(ctx, listSchedulePaymentsByCompanyID, arg.CompanyID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSchedulePaymentsByCompanyIDRow
	for rows.Next() {
		var i ListSchedulePaymentsByCompanyIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ScheduleID,
			&i.PaymentMethodOne,
			&i.PaymentMethodTwo,
			&i.PaymentMethodThree,
			&i.PaymentDate,
			&i.GrossValue,
			&i.DiscountValue,
			&i.NetValue,
			&i.AmountPaid,
			&i.AmountRemaining,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ScheduledAt,
			&i.ClientID,
			&i.PetID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSchedulePayment = `-- name: UpdateSchedulePayment :execrows
UPDATE
    schedule_payments
SET
    payment_method_one = coalesce($1, payment_method_one),
    payment_method_two = coalesce($2, payment_method_two),
    payment_method_three = coalesce($3, payment_method_three),
    payment_date = coalesce($4, payment_date),
    gross_value = coalesce($5, gross_value),
    discount_value = coalesce($6, discount_value),
    net_value = coalesce($7, net_value),
    amount_paid = coalesce($8, amount_paid),
    notes = coalesce($9, notes),
    updated_at = now()
WHERE
    schedule_id = $10
`

type UpdateSchedulePaymentParams struct {
	PaymentMethodOne   NullPaymentMethod  `db:"PaymentMethodOne" json:"PaymentMethodOne"`
	PaymentMethodTwo   NullPaymentMethod  `db:"PaymentMethodTwo" json:"PaymentMethodTwo"`
	PaymentMethodThree NullPaymentMethod  `db:"PaymentMethodThree" json:"PaymentMethodThree"`
	PaymentDate        pgtype.Timestamptz `db:"PaymentDate" json:"PaymentDate"`
	GrossValue         pgtype.Numeric     `db:"GrossValue" json:"GrossValue"`
	DiscountValue      pgtype.Numeric     `db:"DiscountValue" json:"DiscountValue"`
	NetValue           pgtype.Numeric     `db:"NetValue" json:"NetValue"`
	AmountPaid         pgtype.Numeric     `db:"AmountPaid" json:"AmountPaid"`
	Notes              pgtype.Text        `db:"Notes" json:"Notes"`
	ScheduleID         pgtype.UUID        `db:"ScheduleID" json:"ScheduleID"`
}

func (q *Queries) UpdateSchedulePayment(ctx context.Context, arg UpdateSchedulePaymentParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSchedulePayment,
		arg.PaymentMethodOne,
		arg.PaymentMethodTwo,
		arg.PaymentMethodThree,
		arg.PaymentDate,
		arg.GrossValue,
		arg.DiscountValue,
		arg.NetValue,
		arg.AmountPaid,
		arg.Notes,
		arg.ScheduleID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
