// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: schedule_status_history.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestScheduleStatus = `-- name: GetLatestScheduleStatus :one
SELECT
    ssh.id,
    ssh.schedule_id,
    ssh.status,
    ssh.changed_at,
    ssh.changed_by,
    ssh.notes
FROM
    schedule_status_history ssh
WHERE
    ssh.schedule_id = $1
ORDER BY
    ssh.changed_at DESC
LIMIT 1
`

func (q *Queries) GetLatestScheduleStatus(ctx context.Context, scheduleid pgtype.UUID) (ScheduleStatusHistory, error) {
	row := q.db.QueryRow(ctx, getLatestScheduleStatus, scheduleid)
	var i ScheduleStatusHistory
	err := row.Scan(
		&i.ID,
		&i.ScheduleID,
		&i.Status,
		&i.ChangedAt,
		&i.ChangedBy,
		&i.Notes,
	)
	return i, err
}

const insertScheduleStatusHistory = `-- name: InsertScheduleStatusHistory :one
INSERT INTO schedule_status_history(schedule_id, status, changed_by, notes)
    VALUES ($1, $2, $3, $4)
RETURNING
    id, schedule_id, status, changed_at, changed_by, notes
`

type InsertScheduleStatusHistoryParams struct {
	ScheduleID pgtype.UUID    `db:"ScheduleID" json:"ScheduleID"`
	Status     ScheduleStatus `db:"Status" json:"Status"`
	ChangedBy  pgtype.UUID    `db:"ChangedBy" json:"ChangedBy"`
	Notes      pgtype.Text    `db:"Notes" json:"Notes"`
}

func (q *Queries) InsertScheduleStatusHistory(ctx context.Context, arg InsertScheduleStatusHistoryParams) (ScheduleStatusHistory, error) {
	row := q.db.QueryRow(ctx, insertScheduleStatusHistory,
		arg.ScheduleID,
		arg.Status,
		arg.ChangedBy,
		arg.Notes,
	)
	var i ScheduleStatusHistory
	err := row.Scan(
		&i.ID,
		&i.ScheduleID,
		&i.Status,
		&i.ChangedAt,
		&i.ChangedBy,
		&i.Notes,
	)
	return i, err
}

const listScheduleStatusHistoryByScheduleID = `-- name: ListScheduleStatusHistoryByScheduleID :many
SELECT
    ssh.id,
    ssh.schedule_id,
    ssh.status,
    ssh.changed_at,
    ssh.changed_by,
    ssh.notes
FROM
    schedule_status_history ssh
    INNER JOIN schedules s ON s.id = ssh.schedule_id
WHERE
    ssh.schedule_id = $1
    AND s.company_id = $2
ORDER BY
    ssh.changed_at DESC
`

type ListScheduleStatusHistoryByScheduleIDParams struct {
	ScheduleID pgtype.UUID `db:"ScheduleID" json:"ScheduleID"`
	CompanyID  pgtype.UUID `db:"CompanyID" json:"CompanyID"`
}

func (q *Queries) ListScheduleStatusHistoryByScheduleID(ctx context.Context, arg ListScheduleStatusHistoryByScheduleIDParams) ([]ScheduleStatusHistory, error) {
	rows, err := q.db.Query(ctx, listScheduleStatusHistoryByScheduleID, arg.ScheduleID, arg.CompanyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduleStatusHistory
	for rows.Next() {
		var i ScheduleStatusHistory
		if err := rows.Scan(
			&i.ID,
			&i.ScheduleID,
			&i.Status,
			&i.ChangedAt,
			&i.ChangedBy,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
