// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: schedule_services.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteScheduleService = `-- name: DeleteScheduleService :execrows
DELETE FROM schedule_services
WHERE schedule_id = $1
    AND service_id = $2
`

type DeleteScheduleServiceParams struct {
	ScheduleID pgtype.UUID `db:"ScheduleID" json:"ScheduleID"`
	ServiceID  pgtype.UUID `db:"ServiceID" json:"ServiceID"`
}

func (q *Queries) DeleteScheduleService(ctx context.Context, arg DeleteScheduleServiceParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteScheduleService, arg.ScheduleID, arg.ServiceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteScheduleServicesByScheduleID = `-- name: DeleteScheduleServicesByScheduleID :execrows
DELETE FROM schedule_services
WHERE schedule_id = $1
`

func (q *Queries) DeleteScheduleServicesByScheduleID(ctx context.Context, scheduleid pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteScheduleServicesByScheduleID, scheduleid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getScheduleService = `-- name: GetScheduleService :one
SELECT
    ss.id,
    ss.schedule_id,
    ss.service_id,
    ss.created_at
FROM
    schedule_services ss
WHERE
    ss.schedule_id = $1
    AND ss.service_id = $2
LIMIT 1
`

type GetScheduleServiceParams struct {
	ScheduleID pgtype.UUID `db:"ScheduleID" json:"ScheduleID"`
	ServiceID  pgtype.UUID `db:"ServiceID" json:"ServiceID"`
}

func (q *Queries) GetScheduleService(ctx context.Context, arg GetScheduleServiceParams) (ScheduleService, error) {
	row := q.db.QueryRow(ctx, getScheduleService, arg.ScheduleID, arg.ServiceID)
	var i ScheduleService
	err := row.Scan(
		&i.ID,
		&i.ScheduleID,
		&i.ServiceID,
		&i.CreatedAt,
	)
	return i, err
}

const insertScheduleService = `-- name: InsertScheduleService :one
INSERT INTO schedule_services (schedule_id, service_id)
    VALUES ($1, $2)
RETURNING id, schedule_id, service_id, created_at
`

type InsertScheduleServiceParams struct {
	ScheduleID pgtype.UUID `db:"ScheduleID" json:"ScheduleID"`
	ServiceID  pgtype.UUID `db:"ServiceID" json:"ServiceID"`
}

func (q *Queries) InsertScheduleService(ctx context.Context, arg InsertScheduleServiceParams) (ScheduleService, error) {
	row := q.db.QueryRow(ctx, insertScheduleService, arg.ScheduleID, arg.ServiceID)
	var i ScheduleService
	err := row.Scan(
		&i.ID,
		&i.ScheduleID,
		&i.ServiceID,
		&i.CreatedAt,
	)
	return i, err
}

const listScheduleServices = `-- name: ListScheduleServices :many
SELECT
    ss.id,
    ss.schedule_id,
    ss.service_id,
    ss.created_at,
    s.title AS service_title,
    s.description AS service_description,
    s.price AS service_price,
    s.discount_rate AS service_discount_rate,
    s.image_url AS service_image_url
FROM
    schedule_services ss
    JOIN services s ON ss.service_id = s.id
WHERE
    ss.schedule_id = $1
    AND s.deleted_at IS NULL
ORDER BY
    s.title ASC
`

type ListScheduleServicesRow struct {
	ID                  pgtype.UUID        `db:"id" json:"id"`
	ScheduleID          pgtype.UUID        `db:"schedule_id" json:"schedule_id"`
	ServiceID           pgtype.UUID        `db:"service_id" json:"service_id"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ServiceTitle        string             `db:"service_title" json:"service_title"`
	ServiceDescription  string             `db:"service_description" json:"service_description"`
	ServicePrice        pgtype.Numeric     `db:"service_price" json:"service_price"`
	ServiceDiscountRate pgtype.Numeric     `db:"service_discount_rate" json:"service_discount_rate"`
	ServiceImageUrl     pgtype.Text        `db:"service_image_url" json:"service_image_url"`
}

func (q *Queries) ListScheduleServices(ctx context.Context, scheduleid pgtype.UUID) ([]ListScheduleServicesRow, error) {
	rows, err := q.db.Query(ctx, listScheduleServices, scheduleid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScheduleServicesRow
	for rows.Next() {
		var i ListScheduleServicesRow
		if err := rows.Scan(
			&i.ID,
			&i.ScheduleID,
			&i.ServiceID,
			&i.CreatedAt,
			&i.ServiceTitle,
			&i.ServiceDescription,
			&i.ServicePrice,
			&i.ServiceDiscountRate,
			&i.ServiceImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
