// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: service_types.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteServiceType = `-- name: DeleteServiceType :one
UPDATE
    service_types
SET
    deleted_at = now(),
    updated_at = now()
WHERE
    id = $1
    AND deleted_at IS NULL
RETURNING
    id, name, description, created_at, updated_at, deleted_at
`

func (q *Queries) DeleteServiceType(ctx context.Context, id pgtype.UUID) (ServiceType, error) {
	row := q.db.QueryRow(ctx, deleteServiceType, id)
	var i ServiceType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getServiceTypeByID = `-- name: GetServiceTypeByID :one
SELECT
    st.id,
    st.name,
    st.description,
    st.created_at,
    st.updated_at,
    st.deleted_at
FROM
    service_types st
WHERE
    st.id = $1
    AND st.deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetServiceTypeByID(ctx context.Context, id pgtype.UUID) (ServiceType, error) {
	row := q.db.QueryRow(ctx, getServiceTypeByID, id)
	var i ServiceType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertServiceType = `-- name: InsertServiceType :one
INSERT INTO service_types(name, description)
    VALUES ($1, $2)
RETURNING
    id, name, description, created_at, updated_at, deleted_at
`

type InsertServiceTypeParams struct {
	Name        string      `db:"Name" json:"Name"`
	Description pgtype.Text `db:"Description" json:"Description"`
}

func (q *Queries) InsertServiceType(ctx context.Context, arg InsertServiceTypeParams) (ServiceType, error) {
	row := q.db.QueryRow(ctx, insertServiceType, arg.Name, arg.Description)
	var i ServiceType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listServiceTypes = `-- name: ListServiceTypes :many
SELECT
    st.id,
    st.name,
    st.description,
    st.created_at,
    st.updated_at,
    st.deleted_at
FROM
    service_types st
WHERE
    st.deleted_at IS NULL
ORDER BY
    st.created_at DESC
LIMIT $2
OFFSET $1
`

type ListServiceTypesParams struct {
	Offset int32 `db:"Offset" json:"Offset"`
	Limit  int32 `db:"Limit" json:"Limit"`
}

func (q *Queries) ListServiceTypes(ctx context.Context, arg ListServiceTypesParams) ([]ServiceType, error) {
	rows, err := q.db.Query(ctx, listServiceTypes, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceType
	for rows.Next() {
		var i ServiceType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateServiceType = `-- name: UpdateServiceType :one
UPDATE
    service_types
SET
    name = coalesce($1, name),
    description = coalesce($2, description),
    updated_at = now()
WHERE
    id = $3
    AND deleted_at IS NULL
RETURNING
    id, name, description, created_at, updated_at, deleted_at
`

type UpdateServiceTypeParams struct {
	Name        pgtype.Text `db:"Name" json:"Name"`
	Description pgtype.Text `db:"Description" json:"Description"`
	ID          pgtype.UUID `db:"ID" json:"ID"`
}

func (q *Queries) UpdateServiceType(ctx context.Context, arg UpdateServiceTypeParams) (ServiceType, error) {
	row := q.db.QueryRow(ctx, updateServiceType, arg.Name, arg.Description, arg.ID)
	var i ServiceType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
