// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: service_plan_bonuses.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteServicePlanBonus = `-- name: DeleteServicePlanBonus :execrows
DELETE FROM service_plan_bonuses
WHERE id = $1
`

func (q *Queries) DeleteServicePlanBonus(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteServicePlanBonus, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getServicePlanBonusByID = `-- name: GetServicePlanBonusByID :one
SELECT
    spb.id,
    spb.service_plan_id,
    spb.service_id,
    spb.sub_service_id,
    spb.is_active,
    spb.created_at
FROM
    service_plan_bonuses spb
WHERE
    spb.id = $1
LIMIT 1
`

func (q *Queries) GetServicePlanBonusByID(ctx context.Context, id pgtype.UUID) (ServicePlanBonuse, error) {
	row := q.db.QueryRow(ctx, getServicePlanBonusByID, id)
	var i ServicePlanBonuse
	err := row.Scan(
		&i.ID,
		&i.ServicePlanID,
		&i.ServiceID,
		&i.SubServiceID,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const insertServicePlanBonus = `-- name: InsertServicePlanBonus :execrows
INSERT INTO service_plan_bonuses(service_plan_id, service_id, sub_service_id, is_active)
    VALUES ($1, $2, $3, $4)
`

type InsertServicePlanBonusParams struct {
	ServicePlanID pgtype.UUID `db:"ServicePlanID" json:"ServicePlanID"`
	ServiceID     pgtype.UUID `db:"ServiceID" json:"ServiceID"`
	SubServiceID  pgtype.UUID `db:"SubServiceID" json:"SubServiceID"`
	IsActive      pgtype.Bool `db:"IsActive" json:"IsActive"`
}

func (q *Queries) InsertServicePlanBonus(ctx context.Context, arg InsertServicePlanBonusParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertServicePlanBonus,
		arg.ServicePlanID,
		arg.ServiceID,
		arg.SubServiceID,
		arg.IsActive,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listServicePlanBonuses = `-- name: ListServicePlanBonuses :many
SELECT
    spb.id,
    spb.service_plan_id,
    spb.service_id,
    spb.sub_service_id,
    spb.is_active,
    spb.created_at,
    s.title AS service_title,
    s.price AS service_price,
    ss.title AS sub_service_title,
    ss.price AS sub_service_price
FROM
    service_plan_bonuses spb
    LEFT JOIN services s ON spb.service_id = s.id
    LEFT JOIN sub_services ss ON spb.sub_service_id = ss.id
WHERE
    spb.service_plan_id = $1
ORDER BY
    spb.created_at DESC
LIMIT $3
OFFSET $2
`

type ListServicePlanBonusesParams struct {
	ServicePlanID pgtype.UUID `db:"ServicePlanID" json:"ServicePlanID"`
	Offset        int32       `db:"Offset" json:"Offset"`
	Limit         int32       `db:"Limit" json:"Limit"`
}

type ListServicePlanBonusesRow struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	ServicePlanID   pgtype.UUID        `db:"service_plan_id" json:"service_plan_id"`
	ServiceID       pgtype.UUID        `db:"service_id" json:"service_id"`
	SubServiceID    pgtype.UUID        `db:"sub_service_id" json:"sub_service_id"`
	IsActive        bool               `db:"is_active" json:"is_active"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ServiceTitle    pgtype.Text        `db:"service_title" json:"service_title"`
	ServicePrice    pgtype.Numeric     `db:"service_price" json:"service_price"`
	SubServiceTitle pgtype.Text        `db:"sub_service_title" json:"sub_service_title"`
	SubServicePrice pgtype.Numeric     `db:"sub_service_price" json:"sub_service_price"`
}

func (q *Queries) ListServicePlanBonuses(ctx context.Context, arg ListServicePlanBonusesParams) ([]ListServicePlanBonusesRow, error) {
	rows, err := q.db.Query(ctx, listServicePlanBonuses, arg.ServicePlanID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListServicePlanBonusesRow
	for rows.Next() {
		var i ListServicePlanBonusesRow
		if err := rows.Scan(
			&i.ID,
			&i.ServicePlanID,
			&i.ServiceID,
			&i.SubServiceID,
			&i.IsActive,
			&i.CreatedAt,
			&i.ServiceTitle,
			&i.ServicePrice,
			&i.SubServiceTitle,
			&i.SubServicePrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateServicePlanBonus = `-- name: UpdateServicePlanBonus :execrows
UPDATE
    service_plan_bonuses
SET
    is_active = coalesce($1, is_active)
WHERE
    id = $2
`

type UpdateServicePlanBonusParams struct {
	IsActive pgtype.Bool `db:"IsActive" json:"IsActive"`
	ID       pgtype.UUID `db:"ID" json:"ID"`
}

func (q *Queries) UpdateServicePlanBonus(ctx context.Context, arg UpdateServicePlanBonusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateServicePlanBonus, arg.IsActive, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
