// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: service_plans.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteServicePlan = `-- name: DeleteServicePlan :one
UPDATE
    service_plans
SET
    deleted_at = now(),
    updated_at = now()
WHERE
    id = $1
    AND deleted_at IS NULL
RETURNING
    id, plan_type_id, title, description, notes, price, discount_rate, image_url, is_active, created_at, updated_at, deleted_at
`

func (q *Queries) DeleteServicePlan(ctx context.Context, id pgtype.UUID) (ServicePlan, error) {
	row := q.db.QueryRow(ctx, deleteServicePlan, id)
	var i ServicePlan
	err := row.Scan(
		&i.ID,
		&i.PlanTypeID,
		&i.Title,
		&i.Description,
		&i.Notes,
		&i.Price,
		&i.DiscountRate,
		&i.ImageUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getServicePlanByID = `-- name: GetServicePlanByID :one
SELECT
    sp.id,
    sp.plan_type_id,
    sp.title,
    sp.description,
    sp.notes,
    sp.price,
    sp.discount_rate,
    sp.image_url,
    sp.is_active,
    sp.created_at,
    sp.updated_at,
    sp.deleted_at
FROM
    service_plans sp
WHERE
    sp.id = $1
    AND sp.deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetServicePlanByID(ctx context.Context, id pgtype.UUID) (ServicePlan, error) {
	row := q.db.QueryRow(ctx, getServicePlanByID, id)
	var i ServicePlan
	err := row.Scan(
		&i.ID,
		&i.PlanTypeID,
		&i.Title,
		&i.Description,
		&i.Notes,
		&i.Price,
		&i.DiscountRate,
		&i.ImageUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertServicePlan = `-- name: InsertServicePlan :one
INSERT INTO service_plans(plan_type_id, title, description, notes, price, discount_rate, image_url, is_active)
    VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING
    id, plan_type_id, title, description, notes, price, discount_rate, image_url, is_active, created_at, updated_at, deleted_at
`

type InsertServicePlanParams struct {
	PlanTypeID   pgtype.UUID    `db:"PlanTypeID" json:"PlanTypeID"`
	Title        string         `db:"Title" json:"Title"`
	Description  string         `db:"Description" json:"Description"`
	Notes        pgtype.Text    `db:"Notes" json:"Notes"`
	Price        pgtype.Numeric `db:"Price" json:"Price"`
	DiscountRate pgtype.Numeric `db:"DiscountRate" json:"DiscountRate"`
	ImageURL     pgtype.Text    `db:"ImageURL" json:"ImageURL"`
	IsActive     pgtype.Bool    `db:"IsActive" json:"IsActive"`
}

func (q *Queries) InsertServicePlan(ctx context.Context, arg InsertServicePlanParams) (ServicePlan, error) {
	row := q.db.QueryRow(ctx, insertServicePlan,
		arg.PlanTypeID,
		arg.Title,
		arg.Description,
		arg.Notes,
		arg.Price,
		arg.DiscountRate,
		arg.ImageURL,
		arg.IsActive,
	)
	var i ServicePlan
	err := row.Scan(
		&i.ID,
		&i.PlanTypeID,
		&i.Title,
		&i.Description,
		&i.Notes,
		&i.Price,
		&i.DiscountRate,
		&i.ImageUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listActiveServicePlans = `-- name: ListActiveServicePlans :many
SELECT
    sp.id,
    sp.plan_type_id,
    sp.title,
    sp.description,
    sp.notes,
    sp.price,
    sp.discount_rate,
    sp.image_url,
    sp.is_active,
    sp.created_at,
    sp.updated_at,
    sp.deleted_at
FROM
    service_plans sp
WHERE
    sp.is_active = TRUE
    AND sp.deleted_at IS NULL
ORDER BY
    sp.title ASC
LIMIT $2
OFFSET $1
`

type ListActiveServicePlansParams struct {
	Offset int32 `db:"Offset" json:"Offset"`
	Limit  int32 `db:"Limit" json:"Limit"`
}

func (q *Queries) ListActiveServicePlans(ctx context.Context, arg ListActiveServicePlansParams) ([]ServicePlan, error) {
	rows, err := q.db.Query(ctx, listActiveServicePlans, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServicePlan
	for rows.Next() {
		var i ServicePlan
		if err := rows.Scan(
			&i.ID,
			&i.PlanTypeID,
			&i.Title,
			&i.Description,
			&i.Notes,
			&i.Price,
			&i.DiscountRate,
			&i.ImageUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicePlans = `-- name: ListServicePlans :many
SELECT
    sp.id,
    sp.plan_type_id,
    sp.title,
    sp.description,
    sp.notes,
    sp.price,
    sp.discount_rate,
    sp.image_url,
    sp.is_active,
    sp.created_at,
    sp.updated_at,
    sp.deleted_at
FROM
    service_plans sp
WHERE
    sp.deleted_at IS NULL
ORDER BY
    sp.created_at DESC
LIMIT $2
OFFSET $1
`

type ListServicePlansParams struct {
	Offset int32 `db:"Offset" json:"Offset"`
	Limit  int32 `db:"Limit" json:"Limit"`
}

func (q *Queries) ListServicePlans(ctx context.Context, arg ListServicePlansParams) ([]ServicePlan, error) {
	rows, err := q.db.Query(ctx, listServicePlans, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServicePlan
	for rows.Next() {
		var i ServicePlan
		if err := rows.Scan(
			&i.ID,
			&i.PlanTypeID,
			&i.Title,
			&i.Description,
			&i.Notes,
			&i.Price,
			&i.DiscountRate,
			&i.ImageUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateServicePlan = `-- name: UpdateServicePlan :one
UPDATE
    service_plans
SET
    plan_type_id = coalesce($1, plan_type_id),
    title = coalesce($2, title),
    description = coalesce($3, description),
    notes = coalesce($4, notes),
    price = coalesce($5, price),
    discount_rate = coalesce($6, discount_rate),
    image_url = coalesce($7, image_url),
    is_active = coalesce($8, is_active),
    updated_at = now()
WHERE
    id = $9
    AND deleted_at IS NULL
RETURNING
    id, plan_type_id, title, description, notes, price, discount_rate, image_url, is_active, created_at, updated_at, deleted_at
`

type UpdateServicePlanParams struct {
	PlanTypeID   pgtype.UUID    `db:"PlanTypeID" json:"PlanTypeID"`
	Title        pgtype.Text    `db:"Title" json:"Title"`
	Description  pgtype.Text    `db:"Description" json:"Description"`
	Notes        pgtype.Text    `db:"Notes" json:"Notes"`
	Price        pgtype.Numeric `db:"Price" json:"Price"`
	DiscountRate pgtype.Numeric `db:"DiscountRate" json:"DiscountRate"`
	ImageURL     pgtype.Text    `db:"ImageURL" json:"ImageURL"`
	IsActive     pgtype.Bool    `db:"IsActive" json:"IsActive"`
	ID           pgtype.UUID    `db:"ID" json:"ID"`
}

func (q *Queries) UpdateServicePlan(ctx context.Context, arg UpdateServicePlanParams) (ServicePlan, error) {
	row := q.db.QueryRow(ctx, updateServicePlan,
		arg.PlanTypeID,
		arg.Title,
		arg.Description,
		arg.Notes,
		arg.Price,
		arg.DiscountRate,
		arg.ImageURL,
		arg.IsActive,
		arg.ID,
	)
	var i ServicePlan
	err := row.Scan(
		&i.ID,
		&i.PlanTypeID,
		&i.Title,
		&i.Description,
		&i.Notes,
		&i.Price,
		&i.DiscountRate,
		&i.ImageUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
