// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: services.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCompanyService = `-- name: CreateCompanyService :one
INSERT INTO company_services (
    company_id,
    service_id,
    is_active
)
VALUES (
    $1,
    $2,
    TRUE
)
RETURNING id, company_id, service_id, is_active, created_at, updated_at
`

type CreateCompanyServiceParams struct {
	CompanyID pgtype.UUID `db:"CompanyID" json:"CompanyID"`
	ServiceID pgtype.UUID `db:"ServiceID" json:"ServiceID"`
}

func (q *Queries) CreateCompanyService(ctx context.Context, arg CreateCompanyServiceParams) (CompanyService, error) {
	row := q.db.QueryRow(ctx, createCompanyService, arg.CompanyID, arg.ServiceID)
	var i CompanyService
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ServiceID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createService = `-- name: CreateService :one
INSERT INTO services (
    type_id,
    title,
    description,
    notes,
    price,
    discount_rate,
    image_url,
    is_active
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, type_id, title, description, notes, price, discount_rate, image_url, is_active, created_at, updated_at, deleted_at
`

type CreateServiceParams struct {
	TypeID       pgtype.UUID    `db:"TypeID" json:"TypeID"`
	Title        string         `db:"Title" json:"Title"`
	Description  string         `db:"Description" json:"Description"`
	Notes        pgtype.Text    `db:"Notes" json:"Notes"`
	Price        pgtype.Numeric `db:"Price" json:"Price"`
	DiscountRate pgtype.Numeric `db:"DiscountRate" json:"DiscountRate"`
	ImageURL     pgtype.Text    `db:"ImageURL" json:"ImageURL"`
	IsActive     bool           `db:"IsActive" json:"IsActive"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, createService,
		arg.TypeID,
		arg.Title,
		arg.Description,
		arg.Notes,
		arg.Price,
		arg.DiscountRate,
		arg.ImageURL,
		arg.IsActive,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.TypeID,
		&i.Title,
		&i.Description,
		&i.Notes,
		&i.Price,
		&i.DiscountRate,
		&i.ImageUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createServiceType = `-- name: CreateServiceType :one
INSERT INTO service_types (
    name,
    description
)
VALUES (
    $1,
    $2
)
RETURNING id, name, description, created_at, updated_at, deleted_at
`

type CreateServiceTypeParams struct {
	Name        string      `db:"Name" json:"Name"`
	Description pgtype.Text `db:"Description" json:"Description"`
}

func (q *Queries) CreateServiceType(ctx context.Context, arg CreateServiceTypeParams) (ServiceType, error) {
	row := q.db.QueryRow(ctx, createServiceType, arg.Name, arg.Description)
	var i ServiceType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deactivateCompanyService = `-- name: DeactivateCompanyService :execrows
UPDATE
    company_services
SET
    is_active = FALSE,
    updated_at = now()
WHERE
    company_id = $1
    AND service_id = $2
    AND is_active = TRUE
`

type DeactivateCompanyServiceParams struct {
	CompanyID pgtype.UUID `db:"CompanyID" json:"CompanyID"`
	ServiceID pgtype.UUID `db:"ServiceID" json:"ServiceID"`
}

func (q *Queries) DeactivateCompanyService(ctx context.Context, arg DeactivateCompanyServiceParams) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateCompanyService, arg.CompanyID, arg.ServiceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findServiceTypeByName = `-- name: FindServiceTypeByName :one
SELECT
    id,
    name,
    description,
    created_at,
    updated_at,
    deleted_at
FROM
    service_types
WHERE
    lower(name) = lower($1)
    AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) FindServiceTypeByName(ctx context.Context, name string) (ServiceType, error) {
	row := q.db.QueryRow(ctx, findServiceTypeByName, name)
	var i ServiceType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getServiceByIDAndCompanyID = `-- name: GetServiceByIDAndCompanyID :one
SELECT
    s.id,
    s.type_id,
    st.name AS type_name,
    s.title,
    s.description,
    s.notes,
    s.price,
    s.discount_rate,
    s.image_url,
    cs.is_active
FROM
    company_services cs
    INNER JOIN services s ON s.id = cs.service_id
    INNER JOIN service_types st ON st.id = s.type_id
WHERE
    cs.company_id = $1
    AND s.id = $2
    AND cs.is_active = TRUE
    AND s.deleted_at IS NULL
    AND st.deleted_at IS NULL
LIMIT 1
`

type GetServiceByIDAndCompanyIDParams struct {
	CompanyID pgtype.UUID `db:"CompanyID" json:"CompanyID"`
	ID        pgtype.UUID `db:"ID" json:"ID"`
}

type GetServiceByIDAndCompanyIDRow struct {
	ID           pgtype.UUID    `db:"id" json:"id"`
	TypeID       pgtype.UUID    `db:"type_id" json:"type_id"`
	TypeName     string         `db:"type_name" json:"type_name"`
	Title        string         `db:"title" json:"title"`
	Description  string         `db:"description" json:"description"`
	Notes        pgtype.Text    `db:"notes" json:"notes"`
	Price        pgtype.Numeric `db:"price" json:"price"`
	DiscountRate pgtype.Numeric `db:"discount_rate" json:"discount_rate"`
	ImageUrl     pgtype.Text    `db:"image_url" json:"image_url"`
	IsActive     bool           `db:"is_active" json:"is_active"`
}

func (q *Queries) GetServiceByIDAndCompanyID(ctx context.Context, arg GetServiceByIDAndCompanyIDParams) (GetServiceByIDAndCompanyIDRow, error) {
	row := q.db.QueryRow(ctx, getServiceByIDAndCompanyID, arg.CompanyID, arg.ID)
	var i GetServiceByIDAndCompanyIDRow
	err := row.Scan(
		&i.ID,
		&i.TypeID,
		&i.TypeName,
		&i.Title,
		&i.Description,
		&i.Notes,
		&i.Price,
		&i.DiscountRate,
		&i.ImageUrl,
		&i.IsActive,
	)
	return i, err
}

const listServicesByCompanyID = `-- name: ListServicesByCompanyID :many
SELECT
    s.id,
    s.type_id,
    st.name AS type_name,
    s.title,
    s.description,
    s.notes,
    s.price,
    s.discount_rate,
    s.image_url,
    cs.is_active
FROM
    company_services cs
    INNER JOIN services s ON s.id = cs.service_id
    INNER JOIN service_types st ON st.id = s.type_id
WHERE
    cs.company_id = $1
    AND cs.is_active = TRUE
    AND s.deleted_at IS NULL
    AND st.deleted_at IS NULL
ORDER BY
    s.title ASC
`

type ListServicesByCompanyIDRow struct {
	ID           pgtype.UUID    `db:"id" json:"id"`
	TypeID       pgtype.UUID    `db:"type_id" json:"type_id"`
	TypeName     string         `db:"type_name" json:"type_name"`
	Title        string         `db:"title" json:"title"`
	Description  string         `db:"description" json:"description"`
	Notes        pgtype.Text    `db:"notes" json:"notes"`
	Price        pgtype.Numeric `db:"price" json:"price"`
	DiscountRate pgtype.Numeric `db:"discount_rate" json:"discount_rate"`
	ImageUrl     pgtype.Text    `db:"image_url" json:"image_url"`
	IsActive     bool           `db:"is_active" json:"is_active"`
}

func (q *Queries) ListServicesByCompanyID(ctx context.Context, companyid pgtype.UUID) ([]ListServicesByCompanyIDRow, error) {
	rows, err := q.db.Query(ctx, listServicesByCompanyID, companyid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListServicesByCompanyIDRow
	for rows.Next() {
		var i ListServicesByCompanyIDRow
		if err := rows.Scan(
			&i.ID,
			&i.TypeID,
			&i.TypeName,
			&i.Title,
			&i.Description,
			&i.Notes,
			&i.Price,
			&i.DiscountRate,
			&i.ImageUrl,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateServiceByIDAndCompanyID = `-- name: UpdateServiceByIDAndCompanyID :execrows
UPDATE
    services s
SET
    type_id = COALESCE($1, s.type_id),
    title = COALESCE($2, s.title),
    description = COALESCE($3, s.description),
    notes = COALESCE($4, s.notes),
    price = COALESCE($5, s.price),
    discount_rate = COALESCE($6, s.discount_rate),
    image_url = COALESCE($7, s.image_url),
    is_active = COALESCE($8, s.is_active),
    updated_at = now()
FROM
    company_services cs
WHERE
    s.id = cs.service_id
    AND s.id = $9
    AND cs.company_id = $10
    AND cs.is_active = TRUE
    AND s.deleted_at IS NULL
`

type UpdateServiceByIDAndCompanyIDParams struct {
	TypeID       pgtype.UUID    `db:"TypeID" json:"TypeID"`
	Title        pgtype.Text    `db:"Title" json:"Title"`
	Description  pgtype.Text    `db:"Description" json:"Description"`
	Notes        pgtype.Text    `db:"Notes" json:"Notes"`
	Price        pgtype.Numeric `db:"Price" json:"Price"`
	DiscountRate pgtype.Numeric `db:"DiscountRate" json:"DiscountRate"`
	ImageURL     pgtype.Text    `db:"ImageURL" json:"ImageURL"`
	IsActive     pgtype.Bool    `db:"IsActive" json:"IsActive"`
	ID           pgtype.UUID    `db:"ID" json:"ID"`
	CompanyID    pgtype.UUID    `db:"CompanyID" json:"CompanyID"`
}

func (q *Queries) UpdateServiceByIDAndCompanyID(ctx context.Context, arg UpdateServiceByIDAndCompanyIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateServiceByIDAndCompanyID,
		arg.TypeID,
		arg.Title,
		arg.Description,
		arg.Notes,
		arg.Price,
		arg.DiscountRate,
		arg.ImageURL,
		arg.IsActive,
		arg.ID,
		arg.CompanyID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const validateServiceByIDAndCompanyID = `-- name: ValidateServiceByIDAndCompanyID :one
SELECT
    EXISTS (
        SELECT
            1
        FROM
            company_services cs
            INNER JOIN services s ON s.id = cs.service_id
        WHERE
            cs.company_id = $1
            AND cs.service_id = $2
            AND cs.is_active = TRUE
            AND s.deleted_at IS NULL
    ) AS is_valid
`

type ValidateServiceByIDAndCompanyIDParams struct {
	CompanyID pgtype.UUID `db:"CompanyID" json:"CompanyID"`
	ServiceID pgtype.UUID `db:"ServiceID" json:"ServiceID"`
}

func (q *Queries) ValidateServiceByIDAndCompanyID(ctx context.Context, arg ValidateServiceByIDAndCompanyIDParams) (bool, error) {
	row := q.db.QueryRow(ctx, validateServiceByIDAndCompanyID, arg.CompanyID, arg.ServiceID)
	var is_valid bool
	err := row.Scan(&is_valid)
	return is_valid, err
}
