// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: service_plan_services.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteServicePlanService = `-- name: DeleteServicePlanService :execrows
DELETE FROM service_plan_services
WHERE service_plan_id = $1
    AND service_id = $2
`

type DeleteServicePlanServiceParams struct {
	ServicePlanID pgtype.UUID `db:"ServicePlanID" json:"ServicePlanID"`
	ServiceID     pgtype.UUID `db:"ServiceID" json:"ServiceID"`
}

func (q *Queries) DeleteServicePlanService(ctx context.Context, arg DeleteServicePlanServiceParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteServicePlanService, arg.ServicePlanID, arg.ServiceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getServicePlanService = `-- name: GetServicePlanService :one
SELECT
    sps.id,
    sps.service_plan_id,
    sps.service_id,
    sps.is_active,
    sps.created_at
FROM
    service_plan_services sps
WHERE
    sps.service_plan_id = $1
    AND sps.service_id = $2
LIMIT 1
`

type GetServicePlanServiceParams struct {
	ServicePlanID pgtype.UUID `db:"ServicePlanID" json:"ServicePlanID"`
	ServiceID     pgtype.UUID `db:"ServiceID" json:"ServiceID"`
}

func (q *Queries) GetServicePlanService(ctx context.Context, arg GetServicePlanServiceParams) (ServicePlanService, error) {
	row := q.db.QueryRow(ctx, getServicePlanService, arg.ServicePlanID, arg.ServiceID)
	var i ServicePlanService
	err := row.Scan(
		&i.ID,
		&i.ServicePlanID,
		&i.ServiceID,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const insertServicePlanService = `-- name: InsertServicePlanService :execrows
INSERT INTO service_plan_services(service_plan_id, service_id, is_active)
    VALUES ($1, $2, $3)
`

type InsertServicePlanServiceParams struct {
	ServicePlanID pgtype.UUID `db:"ServicePlanID" json:"ServicePlanID"`
	ServiceID     pgtype.UUID `db:"ServiceID" json:"ServiceID"`
	IsActive      pgtype.Bool `db:"IsActive" json:"IsActive"`
}

func (q *Queries) InsertServicePlanService(ctx context.Context, arg InsertServicePlanServiceParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertServicePlanService, arg.ServicePlanID, arg.ServiceID, arg.IsActive)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listServicePlanServices = `-- name: ListServicePlanServices :many
SELECT
    sps.id,
    sps.service_plan_id,
    sps.service_id,
    sps.is_active,
    sps.created_at,
    s.title AS service_title,
    s.description AS service_description,
    s.price AS service_price,
    s.discount_rate AS service_discount_rate,
    s.image_url AS service_image_url
FROM
    service_plan_services sps
    JOIN services s ON sps.service_id = s.id
WHERE
    sps.service_plan_id = $1
    AND s.deleted_at IS NULL
ORDER BY
    s.title ASC
LIMIT $3
OFFSET $2
`

type ListServicePlanServicesParams struct {
	ServicePlanID pgtype.UUID `db:"ServicePlanID" json:"ServicePlanID"`
	Offset        int32       `db:"Offset" json:"Offset"`
	Limit         int32       `db:"Limit" json:"Limit"`
}

type ListServicePlanServicesRow struct {
	ID                  pgtype.UUID        `db:"id" json:"id"`
	ServicePlanID       pgtype.UUID        `db:"service_plan_id" json:"service_plan_id"`
	ServiceID           pgtype.UUID        `db:"service_id" json:"service_id"`
	IsActive            bool               `db:"is_active" json:"is_active"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ServiceTitle        string             `db:"service_title" json:"service_title"`
	ServiceDescription  string             `db:"service_description" json:"service_description"`
	ServicePrice        pgtype.Numeric     `db:"service_price" json:"service_price"`
	ServiceDiscountRate pgtype.Numeric     `db:"service_discount_rate" json:"service_discount_rate"`
	ServiceImageUrl     pgtype.Text        `db:"service_image_url" json:"service_image_url"`
}

func (q *Queries) ListServicePlanServices(ctx context.Context, arg ListServicePlanServicesParams) ([]ListServicePlanServicesRow, error) {
	rows, err := q.db.Query(ctx, listServicePlanServices, arg.ServicePlanID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListServicePlanServicesRow
	for rows.Next() {
		var i ListServicePlanServicesRow
		if err := rows.Scan(
			&i.ID,
			&i.ServicePlanID,
			&i.ServiceID,
			&i.IsActive,
			&i.CreatedAt,
			&i.ServiceTitle,
			&i.ServiceDescription,
			&i.ServicePrice,
			&i.ServiceDiscountRate,
			&i.ServiceImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateServicePlanService = `-- name: UpdateServicePlanService :execrows
UPDATE
    service_plan_services
SET
    is_active = coalesce($1, is_active)
WHERE
    service_plan_id = $2
    AND service_id = $3
`

type UpdateServicePlanServiceParams struct {
	IsActive      pgtype.Bool `db:"IsActive" json:"IsActive"`
	ServicePlanID pgtype.UUID `db:"ServicePlanID" json:"ServicePlanID"`
	ServiceID     pgtype.UUID `db:"ServiceID" json:"ServiceID"`
}

func (q *Queries) UpdateServicePlanService(ctx context.Context, arg UpdateServicePlanServiceParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateServicePlanService, arg.IsActive, arg.ServicePlanID, arg.ServiceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
