// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: services_average_times.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteServiceAverageTimesByServiceID = `-- name: DeleteServiceAverageTimesByServiceID :execrows
DELETE FROM services_average_times
WHERE service_id = $1
`

func (q *Queries) DeleteServiceAverageTimesByServiceID(ctx context.Context, serviceid pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteServiceAverageTimesByServiceID, serviceid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertServiceAverageTime = `-- name: InsertServiceAverageTime :one
INSERT INTO services_average_times(service_id, sub_service_id, pet_size, pet_kind, pet_temperament, average_time_minutes)
    VALUES ($1, $2, $3, $4, $5, $6)
RETURNING
    id, service_id, sub_service_id, pet_size, pet_kind, pet_temperament, average_time_minutes, created_at, updated_at
`

type InsertServiceAverageTimeParams struct {
	ServiceID          pgtype.UUID    `db:"ServiceID" json:"ServiceID"`
	SubServiceID       pgtype.UUID    `db:"SubServiceID" json:"SubServiceID"`
	PetSize            PetSize        `db:"PetSize" json:"PetSize"`
	PetKind            PetKind        `db:"PetKind" json:"PetKind"`
	PetTemperament     PetTemperament `db:"PetTemperament" json:"PetTemperament"`
	AverageTimeMinutes int16          `db:"AverageTimeMinutes" json:"AverageTimeMinutes"`
}

func (q *Queries) InsertServiceAverageTime(ctx context.Context, arg InsertServiceAverageTimeParams) (ServicesAverageTime, error) {
	row := q.db.QueryRow(ctx, insertServiceAverageTime,
		arg.ServiceID,
		arg.SubServiceID,
		arg.PetSize,
		arg.PetKind,
		arg.PetTemperament,
		arg.AverageTimeMinutes,
	)
	var i ServicesAverageTime
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.SubServiceID,
		&i.PetSize,
		&i.PetKind,
		&i.PetTemperament,
		&i.AverageTimeMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listServiceAverageTimesByServiceID = `-- name: ListServiceAverageTimesByServiceID :many
SELECT
    id,
    service_id,
    sub_service_id,
    pet_size,
    pet_kind,
    pet_temperament,
    average_time_minutes,
    created_at,
    updated_at
FROM
    services_average_times
WHERE
    service_id = $1
ORDER BY
    sub_service_id NULLS FIRST,
    pet_size ASC,
    pet_kind ASC,
    pet_temperament ASC
`

func (q *Queries) ListServiceAverageTimesByServiceID(ctx context.Context, serviceid pgtype.UUID) ([]ServicesAverageTime, error) {
	rows, err := q.db.Query(ctx, listServiceAverageTimesByServiceID, serviceid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServicesAverageTime
	for rows.Next() {
		var i ServicesAverageTime
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.SubServiceID,
			&i.PetSize,
			&i.PetKind,
			&i.PetTemperament,
			&i.AverageTimeMinutes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
