// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: translations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteTranslation = `-- name: DeleteTranslation :execrows
DELETE FROM translations
WHERE language_code = $1
    AND entity_table = $2
    AND entity_id = $3
    AND field = $4
`

type DeleteTranslationParams struct {
	LanguageCode string      `db:"LanguageCode" json:"LanguageCode"`
	EntityTable  string      `db:"EntityTable" json:"EntityTable"`
	EntityID     pgtype.UUID `db:"EntityID" json:"EntityID"`
	Field        string      `db:"Field" json:"Field"`
}

func (q *Queries) DeleteTranslation(ctx context.Context, arg DeleteTranslationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTranslation,
		arg.LanguageCode,
		arg.EntityTable,
		arg.EntityID,
		arg.Field,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTranslationsByEntity = `-- name: DeleteTranslationsByEntity :execrows
DELETE FROM translations
WHERE entity_table = $1
    AND entity_id = $2
`

type DeleteTranslationsByEntityParams struct {
	EntityTable string      `db:"EntityTable" json:"EntityTable"`
	EntityID    pgtype.UUID `db:"EntityID" json:"EntityID"`
}

func (q *Queries) DeleteTranslationsByEntity(ctx context.Context, arg DeleteTranslationsByEntityParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTranslationsByEntity, arg.EntityTable, arg.EntityID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTranslation = `-- name: GetTranslation :one
SELECT
    t.id,
    t.language_code,
    t.entity_table,
    t.entity_id,
    t.field,
    t.content,
    t.created_at,
    t.updated_at
FROM
    translations t
WHERE
    t.language_code = $1
    AND t.entity_table = $2
    AND t.entity_id = $3
    AND t.field = $4
LIMIT 1
`

type GetTranslationParams struct {
	LanguageCode string      `db:"LanguageCode" json:"LanguageCode"`
	EntityTable  string      `db:"EntityTable" json:"EntityTable"`
	EntityID     pgtype.UUID `db:"EntityID" json:"EntityID"`
	Field        string      `db:"Field" json:"Field"`
}

func (q *Queries) GetTranslation(ctx context.Context, arg GetTranslationParams) (Translation, error) {
	row := q.db.QueryRow(ctx, getTranslation,
		arg.LanguageCode,
		arg.EntityTable,
		arg.EntityID,
		arg.Field,
	)
	var i Translation
	err := row.Scan(
		&i.ID,
		&i.LanguageCode,
		&i.EntityTable,
		&i.EntityID,
		&i.Field,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTranslation = `-- name: InsertTranslation :one
INSERT INTO translations (language_code, entity_table, entity_id, field, content)
    VALUES (
        $1,
        $2,
        $3,
        $4,
        $5
    )
RETURNING id, language_code, entity_table, entity_id, field, content, created_at, updated_at
`

type InsertTranslationParams struct {
	LanguageCode string      `db:"LanguageCode" json:"LanguageCode"`
	EntityTable  string      `db:"EntityTable" json:"EntityTable"`
	EntityID     pgtype.UUID `db:"EntityID" json:"EntityID"`
	Field        string      `db:"Field" json:"Field"`
	Content      string      `db:"Content" json:"Content"`
}

func (q *Queries) InsertTranslation(ctx context.Context, arg InsertTranslationParams) (Translation, error) {
	row := q.db.QueryRow(ctx, insertTranslation,
		arg.LanguageCode,
		arg.EntityTable,
		arg.EntityID,
		arg.Field,
		arg.Content,
	)
	var i Translation
	err := row.Scan(
		&i.ID,
		&i.LanguageCode,
		&i.EntityTable,
		&i.EntityID,
		&i.Field,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTranslationsByEntity = `-- name: ListTranslationsByEntity :many
SELECT
    t.id,
    t.language_code,
    t.entity_table,
    t.entity_id,
    t.field,
    t.content,
    t.created_at,
    t.updated_at
FROM
    translations t
WHERE
    t.entity_table = $1
    AND t.entity_id = $2
ORDER BY
    t.language_code ASC,
    t.field ASC
`

type ListTranslationsByEntityParams struct {
	EntityTable string      `db:"EntityTable" json:"EntityTable"`
	EntityID    pgtype.UUID `db:"EntityID" json:"EntityID"`
}

func (q *Queries) ListTranslationsByEntity(ctx context.Context, arg ListTranslationsByEntityParams) ([]Translation, error) {
	rows, err := q.db.Query(ctx, listTranslationsByEntity, arg.EntityTable, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Translation
	for rows.Next() {
		var i Translation
		if err := rows.Scan(
			&i.ID,
			&i.LanguageCode,
			&i.EntityTable,
			&i.EntityID,
			&i.Field,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTranslationsByEntityAndLanguage = `-- name: ListTranslationsByEntityAndLanguage :many
SELECT
    t.id,
    t.language_code,
    t.entity_table,
    t.entity_id,
    t.field,
    t.content,
    t.created_at,
    t.updated_at
FROM
    translations t
WHERE
    t.entity_table = $1
    AND t.entity_id = $2
    AND t.language_code = $3
ORDER BY
    t.field ASC
`

type ListTranslationsByEntityAndLanguageParams struct {
	EntityTable  string      `db:"EntityTable" json:"EntityTable"`
	EntityID     pgtype.UUID `db:"EntityID" json:"EntityID"`
	LanguageCode string      `db:"LanguageCode" json:"LanguageCode"`
}

func (q *Queries) ListTranslationsByEntityAndLanguage(ctx context.Context, arg ListTranslationsByEntityAndLanguageParams) ([]Translation, error) {
	rows, err := q.db.Query(ctx, listTranslationsByEntityAndLanguage, arg.EntityTable, arg.EntityID, arg.LanguageCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Translation
	for rows.Next() {
		var i Translation
		if err := rows.Scan(
			&i.ID,
			&i.LanguageCode,
			&i.EntityTable,
			&i.EntityID,
			&i.Field,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTranslation = `-- name: UpsertTranslation :one
INSERT INTO translations (language_code, entity_table, entity_id, field, content)
    VALUES (
        $1,
        $2,
        $3,
        $4,
        $5
    )
ON CONFLICT (language_code, entity_table, entity_id, field)
    DO UPDATE SET
        content = EXCLUDED.content,
        updated_at = now()
RETURNING id, language_code, entity_table, entity_id, field, content, created_at, updated_at
`

type UpsertTranslationParams struct {
	LanguageCode string      `db:"LanguageCode" json:"LanguageCode"`
	EntityTable  string      `db:"EntityTable" json:"EntityTable"`
	EntityID     pgtype.UUID `db:"EntityID" json:"EntityID"`
	Field        string      `db:"Field" json:"Field"`
	Content      string      `db:"Content" json:"Content"`
}

func (q *Queries) UpsertTranslation(ctx context.Context, arg UpsertTranslationParams) (Translation, error) {
	row := q.db.QueryRow(ctx, upsertTranslation,
		arg.LanguageCode,
		arg.EntityTable,
		arg.EntityID,
		arg.Field,
		arg.Content,
	)
	var i Translation
	err := row.Scan(
		&i.ID,
		&i.LanguageCode,
		&i.EntityTable,
		&i.EntityID,
		&i.Field,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
