// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users_permissions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bulkInsertUserPermissions = `-- name: BulkInsertUserPermissions :execrows
INSERT INTO users_permissions(user_id, permission_id, granted_by)
SELECT
    $1,
    unnest($2::uuid[]),
    $3
`

type BulkInsertUserPermissionsParams struct {
	UserID        pgtype.UUID   `db:"UserID" json:"UserID"`
	PermissionIDs []pgtype.UUID `db:"PermissionIDs" json:"PermissionIDs"`
	GrantedBy     pgtype.UUID   `db:"GrantedBy" json:"GrantedBy"`
}

func (q *Queries) BulkInsertUserPermissions(ctx context.Context, arg BulkInsertUserPermissionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, bulkInsertUserPermissions, arg.UserID, arg.PermissionIDs, arg.GrantedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUserPermission = `-- name: DeleteUserPermission :execrows
UPDATE
    users_permissions
SET
    revoked_at = now(),
    revoked_by = $1
WHERE
    user_id = $2
    AND permission_id = $3
    AND revoked_at IS NULL
`

type DeleteUserPermissionParams struct {
	RevokedBy    pgtype.UUID `db:"RevokedBy" json:"RevokedBy"`
	UserID       pgtype.UUID `db:"UserID" json:"UserID"`
	PermissionID pgtype.UUID `db:"PermissionID" json:"PermissionID"`
}

func (q *Queries) DeleteUserPermission(ctx context.Context, arg DeleteUserPermissionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserPermission, arg.RevokedBy, arg.UserID, arg.PermissionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserPermission = `-- name: GetUserPermission :one
SELECT
    p.id,
    p.code,
    p."name",
    p.description,
    up.granted_by,
    up.granted_at,
    up.revoked_by,
    up.revoked_at
FROM
    users_permissions up
    JOIN permissions p ON up.permission_id = p.id
WHERE
    up.user_id = $1
    AND up.permission_id = $2
    AND up.revoked_at IS NULL
    AND p.deleted_at IS NULL
`

type GetUserPermissionParams struct {
	UserID       pgtype.UUID `db:"UserID" json:"UserID"`
	PermissionID pgtype.UUID `db:"PermissionID" json:"PermissionID"`
}

type GetUserPermissionRow struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Code        string             `db:"code" json:"code"`
	Name        string             `db:"name" json:"name"`
	Description pgtype.Text        `db:"description" json:"description"`
	GrantedBy   pgtype.UUID        `db:"granted_by" json:"granted_by"`
	GrantedAt   pgtype.Timestamptz `db:"granted_at" json:"granted_at"`
	RevokedBy   pgtype.UUID        `db:"revoked_by" json:"revoked_by"`
	RevokedAt   pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
}

func (q *Queries) GetUserPermission(ctx context.Context, arg GetUserPermissionParams) (GetUserPermissionRow, error) {
	row := q.db.QueryRow(ctx, getUserPermission, arg.UserID, arg.PermissionID)
	var i GetUserPermissionRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.GrantedBy,
		&i.GrantedAt,
		&i.RevokedBy,
		&i.RevokedAt,
	)
	return i, err
}

const insertUserPermission = `-- name: InsertUserPermission :execrows
INSERT INTO users_permissions(user_id, permission_id, granted_by)
    VALUES ($1, $2, $3)
`

type InsertUserPermissionParams struct {
	UserID       pgtype.UUID `db:"UserID" json:"UserID"`
	PermissionID pgtype.UUID `db:"PermissionID" json:"PermissionID"`
	GrantedBy    pgtype.UUID `db:"GrantedBy" json:"GrantedBy"`
}

func (q *Queries) InsertUserPermission(ctx context.Context, arg InsertUserPermissionParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertUserPermission, arg.UserID, arg.PermissionID, arg.GrantedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listPermissionsByUserID = `-- name: ListPermissionsByUserID :many
SELECT
    p.id,
    p.code,
    p."name",
    p.description,
    up.granted_by,
    up.granted_at,
    up.revoked_by,
    up.revoked_at
FROM
    users_permissions up
    JOIN permissions p ON up.permission_id = p.id
WHERE
    up.user_id = $1
    AND up.revoked_at IS NULL
    AND p.deleted_at IS NULL
ORDER BY
    p.code ASC
LIMIT $3
OFFSET $2
`

type ListPermissionsByUserIDParams struct {
	UserID pgtype.UUID `db:"UserID" json:"UserID"`
	Offset int32       `db:"Offset" json:"Offset"`
	Limit  int32       `db:"Limit" json:"Limit"`
}

type ListPermissionsByUserIDRow struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Code        string             `db:"code" json:"code"`
	Name        string             `db:"name" json:"name"`
	Description pgtype.Text        `db:"description" json:"description"`
	GrantedBy   pgtype.UUID        `db:"granted_by" json:"granted_by"`
	GrantedAt   pgtype.Timestamptz `db:"granted_at" json:"granted_at"`
	RevokedBy   pgtype.UUID        `db:"revoked_by" json:"revoked_by"`
	RevokedAt   pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
}

func (q *Queries) ListPermissionsByUserID(ctx context.Context, arg ListPermissionsByUserIDParams) ([]ListPermissionsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listPermissionsByUserID, arg.UserID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPermissionsByUserIDRow
	for rows.Next() {
		var i ListPermissionsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.GrantedBy,
			&i.GrantedAt,
			&i.RevokedBy,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByPermissionID = `-- name: ListUsersByPermissionID :many
SELECT
    u.id,
    u.email,
    u.is_active,
    u.created_at,
    u.updated_at,
    up.granted_by,
    up.granted_at,
    up.revoked_by,
    up.revoked_at
FROM
    users_permissions up
    JOIN users u ON up.user_id = u.id
WHERE
    up.permission_id = $1
    AND up.revoked_at IS NULL
    AND u.deleted_at IS NULL
ORDER BY
    u.email ASC
LIMIT $3
OFFSET $2
`

type ListUsersByPermissionIDParams struct {
	PermissionID pgtype.UUID `db:"PermissionID" json:"PermissionID"`
	Offset       int32       `db:"Offset" json:"Offset"`
	Limit        int32       `db:"Limit" json:"Limit"`
}

type ListUsersByPermissionIDRow struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Email     string             `db:"email" json:"email"`
	IsActive  bool               `db:"is_active" json:"is_active"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	GrantedBy pgtype.UUID        `db:"granted_by" json:"granted_by"`
	GrantedAt pgtype.Timestamptz `db:"granted_at" json:"granted_at"`
	RevokedBy pgtype.UUID        `db:"revoked_by" json:"revoked_by"`
	RevokedAt pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
}

func (q *Queries) ListUsersByPermissionID(ctx context.Context, arg ListUsersByPermissionIDParams) ([]ListUsersByPermissionIDRow, error) {
	rows, err := q.db.Query(ctx, listUsersByPermissionID, arg.PermissionID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersByPermissionIDRow
	for rows.Next() {
		var i ListUsersByPermissionIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GrantedBy,
			&i.GrantedAt,
			&i.RevokedBy,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
