// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteUser = `-- name: DeleteUser :execrows
UPDATE
  users
SET
  deleted_at = now(),
  is_active = FALSE
WHERE
  id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
  u.id,
  u.email,
  u.email_verified,
  u.email_verified_at,
  u."role",
  u.is_active,
  u.created_at,
  u.updated_at,
  u.deleted_at
FROM
  users u
WHERE
  u.email = $1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.EmailVerifiedAt,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
  u.id,
  u.email,
  u.email_verified,
  u.email_verified_at,
  u."role",
  u.is_active,
  u.created_at,
  u.updated_at,
  u.deleted_at
FROM
  users u
WHERE
  u.id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.EmailVerifiedAt,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users(email, email_verified, email_verified_at, "role", is_active)
  VALUES ($1, $2, $3, $4, $5)
RETURNING
  id, email, email_verified, email_verified_at, role, is_active, created_at, updated_at, deleted_at
`

type InsertUserParams struct {
	Email           string             `db:"email" json:"email"`
	EmailVerified   bool               `db:"email_verified" json:"email_verified"`
	EmailVerifiedAt pgtype.Timestamptz `db:"email_verified_at" json:"email_verified_at"`
	Role            UserRoleType       `db:"role" json:"role"`
	IsActive        bool               `db:"is_active" json:"is_active"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.Email,
		arg.EmailVerified,
		arg.EmailVerifiedAt,
		arg.Role,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.EmailVerifiedAt,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT
  u.id,
  u.email,
  u.email_verified,
  u.email_verified_at,
  u."role",
  u.is_active,
  u.created_at,
  u.updated_at,
  u.deleted_at
FROM
  users u
WHERE
  u.deleted_at IS NULL
  AND (u.email ILIKE '%' || $1 || '%'
    OR $1 IS NULL)
  AND (u."role" = $2
    OR $2 IS NULL)
  AND (u.is_active = $3
    OR $3 IS NULL)
  AND (u.created_at >= $4
    OR $4 IS NULL)
  AND (u.email_verified = $5
    OR $5 IS NULL)
  AND (u.email_verified_at >= $6
    OR $6 IS NULL)
ORDER BY
  u.created_at DESC
LIMIT $8
OFFSET $7
`

type ListUsersParams struct {
	Email              pgtype.Text        `db:"Email" json:"Email"`
	Role               NullUserRoleType   `db:"Role" json:"Role"`
	IsActive           pgtype.Bool        `db:"IsActive" json:"IsActive"`
	CreatedAfter       pgtype.Timestamptz `db:"CreatedAfter" json:"CreatedAfter"`
	EmailVerified      pgtype.Bool        `db:"EmailVerified" json:"EmailVerified"`
	EmailVerifiedAfter pgtype.Timestamptz `db:"EmailVerifiedAfter" json:"EmailVerifiedAfter"`
	Offset             int32              `db:"Offset" json:"Offset"`
	Limit              int32              `db:"Limit" json:"Limit"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.Email,
		arg.Role,
		arg.IsActive,
		arg.CreatedAfter,
		arg.EmailVerified,
		arg.EmailVerifiedAfter,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.EmailVerified,
			&i.EmailVerifiedAt,
			&i.Role,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersBasic = `-- name: ListUsersBasic :many
SELECT
  u.id,
  u.email,
  u.email_verified,
  u.email_verified_at,
  u."role",
  u.is_active,
  u.created_at,
  u.updated_at,
  u.deleted_at
FROM
  users u
WHERE
  u.deleted_at IS NULL
ORDER BY
  u.created_at DESC
LIMIT $2
OFFSET $1
`

type ListUsersBasicParams struct {
	Offset int32 `db:"Offset" json:"Offset"`
	Limit  int32 `db:"Limit" json:"Limit"`
}

func (q *Queries) ListUsersBasic(ctx context.Context, arg ListUsersBasicParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersBasic, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.EmailVerified,
			&i.EmailVerifiedAt,
			&i.Role,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :execrows
UPDATE
  users
SET
  email = coalesce($1, email),
  email_verified = coalesce($2, email_verified),
  email_verified_at = coalesce($3, email_verified_at),
  "role" = coalesce($4, "role"),
  is_active = coalesce($5, is_active),
  updated_at = now()
WHERE
  id = $6
`

type UpdateUserParams struct {
	Email           pgtype.Text        `db:"Email" json:"Email"`
	EmailVerified   pgtype.Bool        `db:"EmailVerified" json:"EmailVerified"`
	EmailVerifiedAt pgtype.Timestamptz `db:"EmailVerifiedAt" json:"EmailVerifiedAt"`
	Role            NullUserRoleType   `db:"Role" json:"Role"`
	IsActive        pgtype.Bool        `db:"IsActive" json:"IsActive"`
	ID              pgtype.UUID        `db:"ID" json:"ID"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUser,
		arg.Email,
		arg.EmailVerified,
		arg.EmailVerifiedAt,
		arg.Role,
		arg.IsActive,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
