// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_sessions.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveUserSessionsByUserID = `-- name: GetActiveUserSessionsByUserID :many
SELECT
    us.id,
    us.user_id,
    us.login_history_id,
    us.session_token,
    us.ip_address,
    us.user_agent,
    us.last_activity_at,
    us.expires_at,
    us.logged_out_at,
    us.logout_reason
FROM
    user_sessions us
WHERE
    us.user_id = $1
    AND us.logged_out_at IS NULL
    AND us.expires_at > NOW()
`

type GetActiveUserSessionsByUserIDRow struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	UserID         pgtype.UUID        `db:"user_id" json:"user_id"`
	LoginHistoryID pgtype.UUID        `db:"login_history_id" json:"login_history_id"`
	SessionToken   string             `db:"session_token" json:"session_token"`
	IpAddress      netip.Addr         `db:"ip_address" json:"ip_address"`
	UserAgent      string             `db:"user_agent" json:"user_agent"`
	LastActivityAt pgtype.Timestamptz `db:"last_activity_at" json:"last_activity_at"`
	ExpiresAt      pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	LoggedOutAt    pgtype.Timestamptz `db:"logged_out_at" json:"logged_out_at"`
	LogoutReason   NullLogoutReason   `db:"logout_reason" json:"logout_reason"`
}

func (q *Queries) GetActiveUserSessionsByUserID(ctx context.Context, userid pgtype.UUID) ([]GetActiveUserSessionsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getActiveUserSessionsByUserID, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveUserSessionsByUserIDRow
	for rows.Next() {
		var i GetActiveUserSessionsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LoginHistoryID,
			&i.SessionToken,
			&i.IpAddress,
			&i.UserAgent,
			&i.LastActivityAt,
			&i.ExpiresAt,
			&i.LoggedOutAt,
			&i.LogoutReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserSessionByToken = `-- name: GetUserSessionByToken :one
SELECT
    us.id,
    us.user_id,
    us.login_history_id,
    us.session_token,
    us.ip_address,
    us.user_agent,
    us.last_activity_at,
    us.expires_at,
    us.logged_out_at,
    us.logout_reason
FROM
    user_sessions us
WHERE
    us.session_token = $1
`

type GetUserSessionByTokenRow struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	UserID         pgtype.UUID        `db:"user_id" json:"user_id"`
	LoginHistoryID pgtype.UUID        `db:"login_history_id" json:"login_history_id"`
	SessionToken   string             `db:"session_token" json:"session_token"`
	IpAddress      netip.Addr         `db:"ip_address" json:"ip_address"`
	UserAgent      string             `db:"user_agent" json:"user_agent"`
	LastActivityAt pgtype.Timestamptz `db:"last_activity_at" json:"last_activity_at"`
	ExpiresAt      pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	LoggedOutAt    pgtype.Timestamptz `db:"logged_out_at" json:"logged_out_at"`
	LogoutReason   NullLogoutReason   `db:"logout_reason" json:"logout_reason"`
}

func (q *Queries) GetUserSessionByToken(ctx context.Context, sessiontoken string) (GetUserSessionByTokenRow, error) {
	row := q.db.QueryRow(ctx, getUserSessionByToken, sessiontoken)
	var i GetUserSessionByTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LoginHistoryID,
		&i.SessionToken,
		&i.IpAddress,
		&i.UserAgent,
		&i.LastActivityAt,
		&i.ExpiresAt,
		&i.LoggedOutAt,
		&i.LogoutReason,
	)
	return i, err
}

const insertUserSession = `-- name: InsertUserSession :execrows
INSERT INTO user_sessions(user_id, login_history_id, session_token, ip_address, user_agent, last_activity_at, expires_at, logged_out_at, logout_reason)
    VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertUserSessionParams struct {
	UserID         pgtype.UUID        `db:"UserID" json:"UserID"`
	LoginHistoryID pgtype.UUID        `db:"LoginHistoryID" json:"LoginHistoryID"`
	SessionToken   string             `db:"SessionToken" json:"SessionToken"`
	IPAddress      netip.Addr         `db:"IPAddress" json:"IPAddress"`
	UserAgent      string             `db:"UserAgent" json:"UserAgent"`
	LastActivityAt pgtype.Timestamptz `db:"LastActivityAt" json:"LastActivityAt"`
	ExpiresAt      pgtype.Timestamptz `db:"ExpiresAt" json:"ExpiresAt"`
	LoggedOutAt    pgtype.Timestamptz `db:"LoggedOutAt" json:"LoggedOutAt"`
	LogoutReason   NullLogoutReason   `db:"LogoutReason" json:"LogoutReason"`
}

func (q *Queries) InsertUserSession(ctx context.Context, arg InsertUserSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertUserSession,
		arg.UserID,
		arg.LoginHistoryID,
		arg.SessionToken,
		arg.IPAddress,
		arg.UserAgent,
		arg.LastActivityAt,
		arg.ExpiresAt,
		arg.LoggedOutAt,
		arg.LogoutReason,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserSession = `-- name: UpdateUserSession :execrows
UPDATE
    user_sessions
SET
    last_activity_at = COALESCE($1, last_activity_at),
    ip_address = COALESCE($2, ip_address),
    user_agent = COALESCE($3, user_agent),
    expires_at = COALESCE($4, expires_at),
    logged_out_at = COALESCE($5, logged_out_at),
    logout_reason = COALESCE($6, logout_reason)
WHERE
    session_token = $7
`

type UpdateUserSessionParams struct {
	LastActivityAt pgtype.Timestamptz `db:"LastActivityAt" json:"LastActivityAt"`
	IPAddress      *netip.Addr        `db:"IPAddress" json:"IPAddress"`
	UserAgent      pgtype.Text        `db:"UserAgent" json:"UserAgent"`
	ExpiresAt      pgtype.Timestamptz `db:"ExpiresAt" json:"ExpiresAt"`
	LoggedOutAt    pgtype.Timestamptz `db:"LoggedOutAt" json:"LoggedOutAt"`
	LogoutReason   NullLogoutReason   `db:"LogoutReason" json:"LogoutReason"`
	SessionToken   string             `db:"SessionToken" json:"SessionToken"`
}

func (q *Queries) UpdateUserSession(ctx context.Context, arg UpdateUserSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserSession,
		arg.LastActivityAt,
		arg.IPAddress,
		arg.UserAgent,
		arg.ExpiresAt,
		arg.LoggedOutAt,
		arg.LogoutReason,
		arg.SessionToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
