// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: warnings.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteWarning = `-- name: DeleteWarning :execrows
UPDATE
    warnings
SET
    deleted_at = now(),
    updated_at = now()
WHERE
    id = $1
    AND company_id = $2
    AND deleted_at IS NULL
`

type DeleteWarningParams struct {
	ID        pgtype.UUID `db:"ID" json:"ID"`
	CompanyID pgtype.UUID `db:"CompanyID" json:"CompanyID"`
}

func (q *Queries) DeleteWarning(ctx context.Context, arg DeleteWarningParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWarning, arg.ID, arg.CompanyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getWarningByID = `-- name: GetWarningByID :one
SELECT
    w.id,
    w.company_id,
    w.title,
    w.content,
    w.image_url,
    w.sender_id,
    w.is_active,
    w.created_at,
    w.updated_at,
    w.deleted_at
FROM
    warnings w
WHERE
    w.id = $1
    AND w.company_id = $2
    AND w.deleted_at IS NULL
LIMIT 1
`

type GetWarningByIDParams struct {
	ID        pgtype.UUID `db:"ID" json:"ID"`
	CompanyID pgtype.UUID `db:"CompanyID" json:"CompanyID"`
}

func (q *Queries) GetWarningByID(ctx context.Context, arg GetWarningByIDParams) (Warning, error) {
	row := q.db.QueryRow(ctx, getWarningByID, arg.ID, arg.CompanyID)
	var i Warning
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Title,
		&i.Content,
		&i.ImageUrl,
		&i.SenderID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertWarning = `-- name: InsertWarning :one
INSERT INTO warnings(company_id, title, content, image_url, sender_id, is_active)
    VALUES ($1, $2, $3, $4, $5, $6)
RETURNING
    id, company_id, title, content, image_url, sender_id, is_active, created_at, updated_at, deleted_at
`

type InsertWarningParams struct {
	CompanyID pgtype.UUID `db:"CompanyID" json:"CompanyID"`
	Title     string      `db:"Title" json:"Title"`
	Content   string      `db:"Content" json:"Content"`
	ImageURL  pgtype.Text `db:"ImageURL" json:"ImageURL"`
	SenderID  pgtype.UUID `db:"SenderID" json:"SenderID"`
	IsActive  pgtype.Bool `db:"IsActive" json:"IsActive"`
}

func (q *Queries) InsertWarning(ctx context.Context, arg InsertWarningParams) (Warning, error) {
	row := q.db.QueryRow(ctx, insertWarning,
		arg.CompanyID,
		arg.Title,
		arg.Content,
		arg.ImageURL,
		arg.SenderID,
		arg.IsActive,
	)
	var i Warning
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Title,
		&i.Content,
		&i.ImageUrl,
		&i.SenderID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listActiveWarningsByCompanyID = `-- name: ListActiveWarningsByCompanyID :many
SELECT
    w.id,
    w.company_id,
    w.title,
    w.content,
    w.image_url,
    w.sender_id,
    w.is_active,
    w.created_at,
    w.updated_at,
    w.deleted_at
FROM
    warnings w
WHERE
    w.company_id = $1
    AND w.is_active = TRUE
    AND w.deleted_at IS NULL
ORDER BY
    w.created_at DESC
LIMIT $3
OFFSET $2
`

type ListActiveWarningsByCompanyIDParams struct {
	CompanyID pgtype.UUID `db:"CompanyID" json:"CompanyID"`
	Offset    int32       `db:"Offset" json:"Offset"`
	Limit     int32       `db:"Limit" json:"Limit"`
}

func (q *Queries) ListActiveWarningsByCompanyID(ctx context.Context, arg ListActiveWarningsByCompanyIDParams) ([]Warning, error) {
	rows, err := q.db.Query(ctx, listActiveWarningsByCompanyID, arg.CompanyID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Warning
	for rows.Next() {
		var i Warning
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Title,
			&i.Content,
			&i.ImageUrl,
			&i.SenderID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWarningsByCompanyID = `-- name: ListWarningsByCompanyID :many
SELECT
    w.id,
    w.company_id,
    w.title,
    w.content,
    w.image_url,
    w.sender_id,
    w.is_active,
    w.created_at,
    w.updated_at,
    w.deleted_at
FROM
    warnings w
WHERE
    w.company_id = $1
    AND w.deleted_at IS NULL
ORDER BY
    w.created_at DESC
LIMIT $3
OFFSET $2
`

type ListWarningsByCompanyIDParams struct {
	CompanyID pgtype.UUID `db:"CompanyID" json:"CompanyID"`
	Offset    int32       `db:"Offset" json:"Offset"`
	Limit     int32       `db:"Limit" json:"Limit"`
}

func (q *Queries) ListWarningsByCompanyID(ctx context.Context, arg ListWarningsByCompanyIDParams) ([]Warning, error) {
	rows, err := q.db.Query(ctx, listWarningsByCompanyID, arg.CompanyID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Warning
	for rows.Next() {
		var i Warning
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Title,
			&i.Content,
			&i.ImageUrl,
			&i.SenderID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWarning = `-- name: UpdateWarning :execrows
UPDATE
    warnings
SET
    title = coalesce($1, title),
    content = coalesce($2, content),
    image_url = coalesce($3, image_url),
    is_active = coalesce($4, is_active),
    updated_at = now()
WHERE
    id = $5
    AND company_id = $6
    AND deleted_at IS NULL
`

type UpdateWarningParams struct {
	Title     pgtype.Text `db:"Title" json:"Title"`
	Content   pgtype.Text `db:"Content" json:"Content"`
	ImageURL  pgtype.Text `db:"ImageURL" json:"ImageURL"`
	IsActive  pgtype.Bool `db:"IsActive" json:"IsActive"`
	ID        pgtype.UUID `db:"ID" json:"ID"`
	CompanyID pgtype.UUID `db:"CompanyID" json:"CompanyID"`
}

func (q *Queries) UpdateWarning(ctx context.Context, arg UpdateWarningParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateWarning,
		arg.Title,
		arg.Content,
		arg.ImageURL,
		arg.IsActive,
		arg.ID,
		arg.CompanyID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
